### ISSUE TITLE
Snippets starting with special characters not triggered.

### ISSUE THREAD

**Issue by kozer** [neoclide/coc-snippets#10]
I'm having some js snippets, and some of them start with special characters, eg: =. The window don't even appear, and i can't trigger it.
Example of ultisnips snippet:
```
snippet => "Arrow function"
(${1:args}) => {
	return $3;
}${2:;}
endsnippet

```

Also, I have a question to ask. If we have a snippet that has multiple parts like the above, how we can auto navigate to the next one like in ultisnips? (I used to do that with tab key)

Thank you!

**Comment by chemzqm** [comment]
> The window don't even appear, and i can't trigger it.

It's because snippet completion only triggered with word character for now, you can trigger it by use trigger key.

> how we can auto navigate to the next one like in ultisnips? (

Checkout https://github.com/neoclide/coc-snippets#usage

**Comment by kozer** [comment]
@chemzqm , man do you even sleep? Are you a robot or something? :1st_place_medal:
