### ISSUE TITLE
gopls language server breaks go to next place holder

### ISSUE THREAD

**Issue by jackielii** [neoclide/coc-snippets#101]
steps to reproduce:

1. configure gopls in CocConfig:

```
  "languageserver": {
    "golang": {
      //			"command": "bingo",
      "command": "gopls",
      "initializationOptions": {
        "usePlaceholders": false,
        "completeUnimported": true,
        "hoverKind": "FullDocumentation"
      },
      "args": [
              "-rpc.trace"
      ],
      "rootPatterns": ["go.mod", ".vim/", ".git/", ".hg/"],
//      "disableWorkspaceFolders": true,
//      "requireRootPattern": true,
      "filetypes": ["go"]
    }
```

2. open a file and edit it like so:
```
package set

// orderedSet is a set that preseves the adding order
type orderedSet struct {
	index map[int32]struct{}
	data  []int32
}

func (o *orderedSet) add(k int32) {
	if o.index == nil {
		o.index = make(map[int32]struct{})
	}
	if o.data == nil {
		o.data = make([]int32, 0)
	}
	if _, ok := o.index[k]; !ok {
		o.index[k] = struct{}{}
		o.data = append(o.data, k)
	}
}

fum<tab>
```
`<tab>` would trigger completion as:
![image](https://user-images.githubusercontent.com/360983/73691991-5d8c4280-46cb-11ea-9766-ccae6d63f8fd.png)

then type on like so:
![image](https://user-images.githubusercontent.com/360983/73692034-71d03f80-46cb-11ea-9e6c-ab8750478ca3.png)

at this point hitting enter would insert the `orderedSet` from language server. Then, hitting CTRL+J should go to next place holder which is funcName but it created a line break instead:
![image](https://user-images.githubusercontent.com/360983/73692104-93312b80-46cb-11ea-8c07-aa3401ab0a8a.png)

I think this might be a gopls issue but I don't know how to report it. Here is the full language server log:
[coc.log](https://github.com/neoclide/coc-snippets/files/4150293/coc.log)

**Comment by chemzqm** [comment]
Should be problem of your keymap, try minimal vimrc.

**Comment by jackielii** [comment]
@chemzqm I'm able to reproduce the problem with the minimal config:


![coc-snippet-error](https://user-images.githubusercontent.com/360983/75776084-3157f600-5d4b-11ea-9c7f-e5f41649cfc0.gif)

Steps to reproduce:

1. minimal-coc.nvim
```
set nocompatible
set runtimepath^=/home/jackieli/.config/nvim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden
```
2. `CocConfig`
```
{
  "languageserver": {
    "golang": {
      "command": "gopls",
      "initializationOptions": {
        "usePlaceholders": false,
        "completeUnimported": true,
        "static_check": true,
        "hoverKind": "FullDocumentation"
      },
      "rootPatterns": ["go.mod", ".vim/", ".git/", ".hg/"],
      "filetypes": ["go"]
    }
  }
}
```
3. `nvim -u ~/.config/nvim/minimal-coc.vim main.go`
4. `:CocCommand snippets.editSnippets` and insert a simple snippet
```
snippet fori "for 0..N-1 { ... }"
for ${1:i} := 0; $1 < ${2:N}; $1++ {
	${0:${VISUAL}}
}
endsnippet
```
5. edit main.go like so:
```
package main

func main(){
   fori<C-n><C-y> // C-n to go to the snippet, C-y to accept the snippet
}
```
6. use <C-j> to jump to the second placeholder, and input flag.N, and then <C-y> to accept flag.Narg(), then press<C-j> to jump to the next placeholder, at this point, line break is inserted instead of jumping to the next placeholder

**Comment by jackielii** [comment]
update: exact same steps as above, but if we change `${2:N}` to `${2}` in the snippet, it works:
```
snippet fori "for 0..N-1 { ... }"
for ${1:i} := 0; $1 < ${2}; $1++ {
	${0:${VISUAL}}
}
endsnippet
```
