### ISSUE TITLE
No Snippets Loaded

### ISSUE THREAD

**Issue by ilovehans10** [neoclide/coc-snippets#103]
I am fairly certain that I have followed the installation guide properly for all of the components I am using here. I am also fairly certain that this is not a duplicate issue and I have worked close to an hour looking for ways to fix this on my own. I have also been able to duplicate the effect on my personal computer with the same vimrc.

Using `CocList extensions` shows:
```
* coc-solargraph 1.1.5
* coc-snippets 2.1.18
```
However when I edit ruby documents the only completion options I have are the single word completions. The output of `CocList snippets` is empty in different file-types. My vimrc can be found [here](https://github.com/ilovehans10/dotfiles/blob/master/.vimrc) and as far as I know all of my plugins are up to date. Any additional information

**Comment by chemzqm** [comment]
coc-solargraph doesn't have any snippets provided, please read https://github.com/neoclide/coc-snippets/blob/master/Readme.md#f.a.q

**Comment by ilovehans10** [comment]
Sorry I am still confused should I make my own ruby snippets then and if there are no ruby snippets included what is the purpose of the [ruby.snippets file](https://github.com/neoclide/coc-snippets/blob/master/tests/snippets/ruby.snippets)? Also can I just say thank you for the astonishingly quick response.

**Comment by chemzqm** [comment]
They are used for tests, you can install https://github.com/honza/vim-snippets plugin for snippets.

**Comment by ilovehans10** [comment]
Thank you so much for the amazing help! I greatly appreciate the reply times and your willingness to suggest a repository for me to use.
