### ISSUE TITLE
Manual trigger for snippets

### ISSUE THREAD

**Issue by AlaaSaadAbdo** [neoclide/coc-snippets#104]
Hello!

I wanted to know if there's a way to manually trigger a list of snippets for current file type, is that possible?

And I am awayre of `CocList snippets` but that let's me edit the snippets. I would like to just list the snippets and choose one to expand.

Thanks for the amazing tool :) I'm so very grateful for it. It has replaced a complex set up of multiple plugins to get something that coc does on its own and does it a lot faster <3 

Cheers!

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc-snippets/blob/master/Readme.md#examples

**Comment by AlaaSaadAbdo** [comment]
Thanks for the quick response. Much appreciated :)
