### ISSUE TITLE
Position of snippet preview

### ISSUE THREAD

**Issue by lervag** [neoclide/coc-snippets#105]
I'm wondering if it is possible to specify the position of the snippet preview. I've searched both docs/README and issues and can't find any options for this. The reason I'm asking is that I often work in 80 column terminal windows, in which case the preview is often not so easy to see because it is outside the window.

**Comment by chemzqm** [comment]
Do you mean snippet preview aside with completion menu?
You can't change preview window position.

**Comment by lervag** [comment]
I don't mean the preview window, but the floating window to preview the snippet expansion. Or perhaps this is also called a preview window?

A screenshot should explain better than my words:

![screen](https://user-images.githubusercontent.com/998898/78904627-1f215400-7a7d-11ea-9a3b-aa76273d687f.png)

Here you see that the snippet is previewed on the right of the completion menu. I wonder if it is possible to specify a different position for this, e.g. above the cursor at the left window margin.

**Comment by chemzqm** [comment]
No, you can't, you can use `"suggest.detailMaxLength"` in coc-settings.json to limit length of detail string in popup menu or make your vim window wilder.

You can also make `suggest.enablePreview` to true and `suggest.floatEnable` to false so you can use preview window of vim for documentation.

**Comment by lervag** [comment]
Ok, thanks.
