### ISSUE TITLE
Error installing coc-snippets

### ISSUE THREAD

**Issue by rodrigo1987macedo** [neoclide/coc-snippets#107]
## versions

vim version: NVIM v0.4.3
node version: v12.9.0
coc.nvim version: 0.0.75-d83536aa4e
term: iTerm.app
platform: darwin

## Messages
[coc.nvim] Installed extension: coc-snippets
[coc.nvim] Error on load snippets: ENOENT: no such file or directory, open '/var/folders/vh/ss87g31537n_4s1yzkcrz03h0000gn/T/coc.nvim/coc-ultisnips-6e0860be7e811959dc5e1258117cdda2.py'
## Output channel: highlight

[Info  - 04:51:14] Highlight server running in node v12.9.0

## Output channel: snippets

**Comment by tzhouhc** [comment]
Looks like the [recent commit](https://github.com/neoclide/coc-snippets/commit/a6d5129f258f389f423c352d9c92101328234ef0) changed the temp file path but the file is not there?

**Comment by fannheyward** [comment]
Try `:CocUpdate`
