### ISSUE TITLE
[coc.nvim] Error on load snippets: ENOENT: no such file or directory, open /var/folders/.../T/coc.nvim/coc-ultisnips-....py

### ISSUE THREAD

**Issue by drn** [neoclide/coc-snippets#108]
Hi there,

I'm receiving the following error message:
```
[coc.nvim] Error on load snippets: ENOENT: no such file or directory, open '/var/folders/1x/g6y4zxyx5ng59qk74qvtmq0m0000gn/T/coc.nvim/coc-ultisnips-ac95b5040c1525e5049d2a3e40f8c4c2.py'
```

The odd thing is that after the error message appears, my snippets are properly working. I tried adding the `coc-ultisnips` extension which did not appear to affect anything.

The error message disappears after setting `"snippets.ultisnips.enable": false`, but obviously my snippets do not work.

Is there a way to get rid of this error message?

Thank you!

**Comment by chemzqm** [comment]
Sorry, the code was not carefully reviewed.

**Comment by fannheyward** [comment]
My fault

**Comment by drn** [comment]
Thank you for resolving! Confirmed that it works now 👍

**Comment by ajr-dev** [comment]
How was it resolved? Do I need to update somehow?

**Comment by fannheyward** [comment]
@ajr-dev upgrade your coc.nvim
