### ISSUE TITLE
multiple snippet sources?

### ISSUE THREAD

**Issue by ywpkwon** [neoclide/coc-snippets#111]
### background
I was using `coc-snippets` and `coc-python`. `coc-python` was providing python snippets like `for`.
Meanwhile, I realized I don't have any snippets for c/cpp, so I installed 'honza/vim-snippets' as recommended. I was able to enjoy c/cpp snippets.

### question
Now then, I realized that there are multiple snippets in python (`coc-python` and `honza/vim-snippets`). Here is the `CocList snippets` results for `for` in a python file:
![image](https://user-images.githubusercontent.com/18429284/76404865-703a0d00-6344-11ea-8514-e416d612550f.png)

Is it normal to have several snippets for the same word? (even `honza/vim-snippets` alone has two `for` snippets (`vim-snippets/snippets`, `vim-snippets/UltiSnips`)). Or is there a way to organize this better? Then, how?
Could you please advice?

**Comment by chemzqm** [comment]
Remove the snippet files that you don't need or use configuration https://github.com/neoclide/coc-snippets#options
