### ISSUE TITLE
auto-trigger snippets should have priority / prevent coc-pairs activation

### ISSUE THREAD

**Issue by jeysal** [neoclide/coc-snippets#117]
Consider the following ultisnip:
```
snippet "import {" "import named" bA
import { $2 } from '$1';
endsnippet
```
Both https://github.com/neoclide/coc-snippets and https://github.com/neoclide/coc-pairs are in use. In the following examples, `_` represents the cursor.

Actual behavior (coc-pairs triggers before coc-snippets):
`import {_` => coc-pairs triggers => `import {_}` => coc-snippets auto-triggers => `import { } from '_';}`

Expected behavior (coc-snippets triggers, coc-pairs trigger is prevented):
`import {_` => coc-snippets auto-triggers => `import { } from '_';`

A fix could be documented as an advantage of coc-pairs over auto-pairs for coc-snippets users.

**Comment by chemzqm** [comment]
It's not possible since coc-pairs uses key-mapping.
