### ISSUE TITLE
Unexpected cursor positioning with snippet that uses vim interpolation.

### ISSUE THREAD

**Issue by tartansandal** [neoclide/coc-snippets#118]
The problem is with completing the following simple UltiSnips snippet that uses simple vim interpolation:

```
snippet ddate "## Day DD Month, YYYY" b
## `!v strftime("%a %d %b, %Y")`
endsnippet
```
![coc-snippet-bug](https://user-images.githubusercontent.com/3327775/78634549-8907f500-78e7-11ea-8c6a-137b27f9fd98.gif)

On completing the trigger word "ddate", the cursor is positioned at column 6 in insert mode. Pressing any other key (including Ctrl) moves the cursor to the end of the completion.

I get the same effect with Python and Shell interpolation.

Some details:

vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 30 2020 00:00:00)
node version: v12.16.1
coc.nvim version: 0.0.77-817efd5108
term: dumb
platform: linux

**Comment by chemzqm** [comment]
Fixed on latest coc.nvim.
