### ISSUE TITLE
What's the command to set ultisnips directories?

### ISSUE THREAD

**Issue by eduardoarandah** [neoclide/coc-snippets#119]
I've seen in readme options available, but it's not clear how to set them in .vimrc

These don't work:

```
let snippets.ultisnips.directories = [ $HOME."/scripts/vim/ultisnips" ]
:CocCommand snippets.ultisnips.directories = [ $HOME."/scripts/vim/ultisnips" ]
```

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/wiki/Using-the-configuration-file

**Comment by ovidius72** [comment]
Are those configuration meant to set the location where you want to save your snippet files or they are additional directories to search from ?
I want to change the default location where snippets are saved ?
Thanks.

**Comment by fish895623** [comment]
> Are those configurations meant to set the location where you want to save your snippet files or they are additional directories to search from ? I want to change the default location where snippets are saved. Is that possible ? Thanks.

Add your snippet directory on 

coc-settings

```json
...
"snippets.userSnippetsDirectory": "__ Your own directory in full path :) __"
...
```
