### ISSUE TITLE
python code not working inside of coc-snippets

### ISSUE THREAD

**Issue by douglas86** [neoclide/coc-snippets#123]
python code doesn't seem to be working inside of coc-snippets.
even when I am using,
global !p
def upperfirst(t):
  return t.title()
endglobal

const [${1}, set$1`!p snip.rv=upperfirst(t[1])`] = useState($2)

**Comment by chemzqm** [comment]
It won't work because coc-snippets doesn't calculate python code on placeholder change.

**Comment by douglas86** [comment]
Will coc-snippets ever add support for this type of feature in the future, or can I ask someone to add this type of feature.

**Comment by chemzqm** [comment]
Maybe，you can fork the code

**Comment by douglas86** [comment]
Just one quick question when fork code, what is the best way to add changes to a file, 
should I start a new file entirely and then submit my changes or how would you go about 
achieving that.

**Comment by chemzqm** [comment]
I don't know, for this feature to work maybe lots of changes needed for coc.nvim and coc-snippets.

**Comment by esetnik** [comment]
Having the same issue with the `useState` snip. See https://github.com/honza/vim-snippets/blob/master/UltiSnips/javascript_react.snippets#L17

**Comment by douglas86** [comment]
what sort of issues are you having with the useState hook

**Comment by esetnik** [comment]
Same issue as originally reported by you. ``set`!p snip.rv=t[1].title()` `` is not evaluated by `coc-snippets` so snippet expands to 

```
const [test, set] = useState(default)
```
not 

```
const [test, setTest] = useState(default)
```

**Comment by douglas86** [comment]
try using vim-snippets, I have rectified the problem there.

**Comment by esetnik** [comment]
> try using vim-snippets, I have rectified the problem there.

I am using `vim-snippets`. See https://github.com/honza/vim-snippets/blob/master/UltiSnips/javascript_react.snippets#L17

**Comment by douglas86** [comment]
Are you using coc-snippets as well as vim-snippets

**Comment by douglas86** [comment]
Cause mine works on my side.

**Comment by esetnik** [comment]
> Are you using coc-snippets as well as vim-snippets

Yes, that's my setup.

![coc-snippets](https://user-images.githubusercontent.com/664434/81728338-47bfb380-9458-11ea-9d92-8f9d2a757108.gif)

**Comment by douglas86** [comment]
try doing that same snippet in a .js file, then see what happens.

**Comment by esetnik** [comment]
> try doing that same snippet in a .js file, then see what happens.

Same issue whether I use ts or js as it's the same snippet that's getting expanded. I thought that @chemzqm said this was a known issue https://github.com/neoclide/coc-snippets/issues/123#issuecomment-612341702.

Here's how it looks with a JS file.
![May-12-2020 15-26-39](https://user-images.githubusercontent.com/664434/81736717-01248600-9465-11ea-9bb8-412c8150752c.gif)

**Comment by douglas86** [comment]
take a screenshot of the actual file within 
path to file
vim-snippets/Ultisnips/javascript_react.snippets
then I will see if I can help you out.

**Comment by esetnik** [comment]
![image](https://user-images.githubusercontent.com/664434/81738287-785b1980-9467-11ea-99ea-ea821f895a9b.png)

**Comment by esetnik** [comment]
![image](https://user-images.githubusercontent.com/664434/81738436-b6583d80-9467-11ea-9b1f-ccf52e305252.png)

**Comment by esetnik** [comment]
And the `rfc` Ultisnips snippet https://github.com/honza/vim-snippets/blob/master/UltiSnips/javascript_react.snippets#L2 doesn't work at all whereas the `rfc` vim snippet https://github.com/honza/vim-snippets/blob/master/snippets/javascript/javascript-react.snippets#L45 does work

**Comment by douglas86** [comment]
What completion engine are you using coc.nvim or youcompleteme.

**Comment by esetnik** [comment]
> What completion engine are you using coc.nvim or youcompleteme.

coc.vim

**Comment by douglas86** [comment]
I am wondering if it, isn't your completion engine, that doesn't support python interpolation. Try changing to youcompleteme, just to see if it is the engine.

**Comment by esetnik** [comment]
I don't understand. This package is `coc-snippets` which is built for  `coc.nvim`. So how would I use it with youcompleteme?

**Comment by douglas86** [comment]
As far as I know, coc.nvim doesn't support python interpolation. Cause, I use youcompleteme as my engine and it works fine. The snippets are working correctly on my side. The only way you will really now the cause is if you try it, coc-snippets you can't use with youcompleteme but vim-snippets you can.

**Comment by esetnik** [comment]
Ok thanks for your help. This issue is created in the `coc-snippets` repository and is only relevant for `coc.nvim` so I think it's not relevant to discuss other completion engines here.

**Comment by douglas86** [comment]
Ok, hope that it helps. Cause, if that is not the cause then I don't know what is.

**Comment by chemzqm** [comment]
```

# Functional components
snippet rfc "react functional component" b
import React, {useState} from "react"

function ${1:`!p snip.rv = snip.basename`}(${2}){
	return(
		<div>
			${3:<p>Body</p>}
		</div>
		)
}

export default $4`!p snip.rv = snip.basename`
endsnippet
```
The snip object from coc-snippets doesn't have attribute like `basename` which is not in document, will fix it.

**Comment by douglas86** [comment]
snip.basename works with vim-snippets and youcompleteme. It just doen't work with coc.nvim.

**Comment by chemzqm** [comment]
You can use https://www.npmjs.com/package/coc-ultisnips with ultisnips.vim for full fetaure of ultisnips.

**Comment by esetnik** [comment]
@chemzqm is using coc-ultisnips together with coc-snippets recommended for full support of ultisnips?

**Comment by chemzqm** [comment]
> is using coc-ultisnips together with coc-snippets recommended 

coc-ultisnips works with ultisnips.vim, it's not a good idea to use coc-ultisnips and coc-snippets at the same time.

**Comment by esetnik** [comment]
I thought maybe you were suggesting using the two together with `snippets.ultisnips.enable: false` so that `coc-snippets` would handle the vscode snippets and `coc-ultisnips` would handle the ultisnips.

**Comment by chemzqm** [comment]
No, my suggestion is not use coc-ultinsips and coc-snippets at the same time, unless you want to confuse yourself.

**Comment by esetnik** [comment]
>No, my suggestion is not use coc-ultinsips and coc-snippets at the same time, unless you want to confuse yourself.

Ok, thanks for your help.

> The snip object from coc-snippets doesn't have attribute like `basename` which is not in document, will fix it.

Would you like me to open a separate issue for this since it's not directly related to #123?

**Comment by chemzqm** [comment]
Sure, to help me remind this issue.

**Comment by kbrs-miaha** [comment]
Thanks to this discussion I understand why my UltiSnips weren't working.  Given the `wontfix` label, is it worthwhile making it clearer in the `README.md! that python interpolation isn't supported?

**Comment by chemzqm** [comment]
Could work now, but placeholder of the same index would remains the same value.
