### ISSUE TITLE
coc-snippets always raise error when starting nvim (os: windows, msys2 + nvim-qt)

### ISSUE THREAD

**Issue by cjun714** [neoclide/coc-snippets#124]
coc-snippets worked fine on msys2 + nvim-qt before.
But recently, it keep raising error when I starting nvim-qt.
snapshots:
![issue1](https://user-images.githubusercontent.com/12163580/79064106-b46c5480-7cd8-11ea-9da5-411aac373390.jpg)

![issue2](https://user-images.githubusercontent.com/12163580/79064110-bc2bf900-7cd8-11ea-8a40-c8dff056a2f6.jpg)

The issue happened 1-2 weeks ago I think, after a certain coc autoupdate someday when I starting nvim.
Now it raises error every time I start nvim.
But it's seemed coc-snippets can still work to expand snippet.

My env:
Window10, msys64, nvim-qt v0.5.0 233, mingw-w64-x86_64-python3

CocConfig:
``` json
{
  "snippets.ultisnips.directories": [
    "my_snippets"
  ],
  "snippets.priority": 100,
  "snippets.shortcut": "S",
  "snippets.autoTrigger": true,
  "snippets.triggerCharacters": [],
  "snippets.loadFromExtensions": false,
  "snippets.ultisnips.enable": true,
  "snippets.ultisnips.usePythonx": false,
  "snippets.snipmate.enable": false,

  "suggest.noselect": false,
  "suggest.triggerCompletionWait": 50,
  "suggest.floatEnable": false,
  "suggest.minTriggerInputLength": 2,
  "diagnostic.signOffset": 0,
  "languageserver": {
    "golang": {
      "command": "gopls",
      "rootPatterns": ["go.mod", ".vim/", ".git/", ".hg/"],
      "filetypes": ["go"],
      "initializationOptions": {
        "usePlaceholders": true,
        "deepCompletion": false,
        "completeUnimported": true,
        "watchFileChanges": true
      }
    }
}
```

Please help, thanks a lot!

**Comment by chemzqm** [comment]
Should be problem of your python, chechout where that code comes from and remove it.

**Comment by cjun714** [comment]
It's worked fine before.
This issue just appear when I start Nvim and coc then execute a autoupdate someday.
I didn't change anything to python or msys or any env parameters.

And I have a totally clean msys2 environment, it can reproduce this issue.

**Comment by cjun714** [comment]
I think direct cause is that you recently added  below code in ultisnipsProvider.ts which will be finaly compiled into ~/AppData/Local/coc/extensions/node_modules/coc-snippets/index.js :
``` typescript
  private async executePythonCode(pythonCode: string): Promise<void> {
    try {
      let dir = path.join(os.tmpdir(), `coc.nvim-${process.pid}`)
      if (!fs.existsSync(dir)) fs.mkdirSync(dir)
      let tmpfile = path.join(os.tmpdir(), `coc.nvim-${process.pid}`, `coc-ultisnips-${uid()}.py`)
      fs.writeFileSync(tmpfile, pythonCode, 'utf8')
      await workspace.nvim.command(`exe '${this.pyMethod}file '.fnameescape('${tmpfile}')`)
      pythonCodes.clear()
    } catch (e) {
      workspace.showMessage(`Error on execute python script: ${e.message}`, 'error')
    }
  }
```
It always fail in executing coc-ultisnips-xxxxxxxxxx.py in /tmp.
This .py is composited by ultisnips.py and some other code fragments.

I don't know the usage of executePythonCode().
This func always fail and keep raising error on windows+msys2 env, but coc-snippets still can work.
I am not familiar with python and nodejs, so I can't dig further to find out root cause.
The err msg shows  it's a gbk codec error caused by executing tmp .py generated by coc, so perhaps it's still a coc issue.
Please have a check.

**Comment by chemzqm** [comment]
Can't help,it's error from your python code in snippet

**Comment by cjun714** [comment]
``` vimscript
let g:UltiSnipsSnippetDirectories=["UltiSnips", "my_snippets"]
```
On my pc, above line is the cause.
I have disabled Ultisnips plugin, but forget to comment above line.
I think coc reads this parameter and combine some files(honza/vim-snippets
maybe?) with ultisnips.py to generate the problem coc-ultisnips-xxxxxxxxxx.py(27k size).
On window that caused error.

It's nothing about py env, even `let g:UltiSnipsSnippetDirectories=["UltiSnips"]` will also cause same issue and generate same problem tmp .py.

Another way is to disable `Plug 'honza/vim-snippets'`, that also work.

Both 2 solution will cause coc to generate 8k tmp .py  which is as same as ultisnips.py, then no error happened.

**Comment by Neur1n** [comment]
Same issue here, but if I enable the `Beta: Use Unicode UTF-8 for worldwide language support` option, then the error is gone. This workaround was found [here](https://github.com/google/tangent/issues/11#issuecomment-455910041) but I don't understand why, and I can't find a solution/workaround for Linux yet.

![image](https://user-images.githubusercontent.com/17579247/79625605-a1d0a000-815c-11ea-9d3e-2cc05d73715b.png)

**Comment by chemzqm** [comment]
Should be fixed by ec6097a

**Comment by Neur1n** [comment]
Doesn't work for me on Windows 10.

**Comment by fcying** [comment]
> Same issue here, but if I enable the `Beta: Use Unicode UTF-8 for worldwide language support` option, then the error is gone. This workaround was found [here](https://github.com/google/tangent/issues/11#issuecomment-455910041) but I don't understand why, and I can't find a solution/workaround for Linux yet.
> 
> ![image](https://user-images.githubusercontent.com/17579247/79625605-a1d0a000-815c-11ea-9d3e-2cc05d73715b.png)

改这个后不报错了, 不过很多原来正常的软件 乱码了.

**Comment by fcying** [comment]
modify `python_path\Lib\site-packages\pynvim\plugin\script_host.py` +105 can work.
```python
with open(file_path, 'rb') as f:        #with open(file_path, 'rb') as f: 
```
