### ISSUE TITLE
Expanding some Python snippets from vim-snippets is very slow

### ISSUE THREAD

**Issue by IceNature** [neoclide/coc-snippets#125]
I use the snippets from [vim-snippets](https://github.com/honza/vim-snippets)
The expand operation of snippets `#!` and `#!3` is so slow that Vim is no responding for about **half a minute** and then the snippets will be expanded with a `0` behind `#!`.
For example, `#!3` should be expanded to `#!/usr/bin/env python3`, but it is expanded to `#!0/usr/bin/env python3` actually.

vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr  8 2020 11:33:10)
Include patch: 1-529
node version: v13.7.0
coc.nvim version: 0.0.78-fc983ce6dd
OS: Windows 10 1909 x64 18363.720
Python: 3.7.3 x64
I installed coc-python plugin

I tried Neovim and it does not have this problem. It expands these snippets fast without the useless `0`.

## Steps to reproduce
1. Create a vimrc

```viml
set nocompatible
set runtimepath^=<coc plugin path>
set runtimepath^=<vim-snippets plugin path>
filetype plugin indent on
syntax on
set hidden
if has('patch8.1.1068')
    " Use `complete_info` if your (Neo)Vim version supports it.
    inoremap <silent><expr> <CR> complete_info()["selected"] != "-1" ? "\<C-y>" :
                \ coc#expandable() ? "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand',''])\<CR>" :
                \ "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
else
    imap <silent><expr> <CR> pumvisible() ? "\<C-y>" :
                \ coc#expandable() ? "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand',''])\<CR>" :
                \ "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
endif
function! s:check_back_space() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~# '\s'
endfunction
let g:coc_snippet_next = '<tab>'
let g:coc_snippet_prev = '<s-tab>'
```
1. Run vim with this vimrc `gvim.exe -u minivimrc.vim`
1. Create or edit a Python file, and input `#!3<Enter>`, Vim will be frozen
* There is no error message in `CocInfo` and `:messages` and I do not write any coc-snippets configuration in CocConfig

**Comment by chemzqm** [comment]
Please provide snippet you're using.

**Comment by IceNature** [comment]
Python snippets `#!` `#!3` from vim-snippets
https://github.com/honza/vim-snippets/blob/master/snippets/python.snippets#L1
https://github.com/honza/vim-snippets/blob/master/snippets/python.snippets#L6

```snippets
snippet #!
	#!/usr/bin/env python3
snippet #!2
	#!/usr/bin/env python2
	# -*- coding: utf-8 -*-
snippet #!3
	#!/usr/bin/env python3
```

**Comment by wrvsrx** [comment]
I met this problem too. Open vim, type "date" and press \<c-j\> or \<c-l\> (I map \<c-j\> to coc-snippets-expand-jump and \<c-l\> to coc-snippets-expand), then vim will stuck for dozens seconds.

However, if I use \<c-n\> to select the snippet then use \<c-y\> to confirm, it works well.

I have tested it with minimal vimrc.

## CocInfo

vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr  4 2020 13:23:00)
node version: v13.13.0
coc.nvim version: 0.0.78-14de259601
term: dumb
platform: linux

## snippet

```
snippet date "YYYY-MM-DD" w
`!v strftime("%Y-%m-%d")`
endsnippet
```

## vimrc

```vim
set nocompatible
set runtimepath^=~/.vim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden
imap <c-j> <Plug>(coc-snippets-expand-jump)
imap <c-l> <Plug>(coc-snippets-expand)
```

**Comment by wrvsrx** [comment]
During sticking I killed vim and I get following output.
![image](https://user-images.githubusercontent.com/42770726/79449911-a68b3c00-8016-11ea-915c-e328f15a5977.png)

I hope that can help you to find the bug.

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
