### ISSUE TITLE
"No `vimsnipets` module" error in installation

### ISSUE THREAD

**Issue by lyh970817** [neoclide/coc-snippets#126]
```
[coc.nvim] Error on execute python script: request error nvim_comma
nd - Vim(return):Error invoking 'python_execute_file' on channel 4
(python3-script-host):
Traceback (most recent call last):
  File "/tmp/coc.nvim-8249/coc-ultisnips-OH7MTlCpbm.py", line 514,
in <module>
    from vimsnippets import complete
ModuleNotFoundError: No module named 'vimsnippets'
```
The above error appears immediately after installation.

**Comment by praveendhawan** [comment]
I can see this not only on installation but every time vim opens up even after installing.

**Comment by lyh970817** [comment]
> I can see this not only on installation but every time vim opens up even after installing.

Yes, I see it every time too. It would be gone if I `:CocRemove coc-snippets`.

**Comment by gibfahn** [comment]
Seeing a similar error:

```
[Info 14:14:48] Using ultisnips directories: UltiSnips /Users/gib/.config/coc/ultisnips
[Info 14:14:48] Using ultisnips python command: pyx
Error on execute python script:
request error nvim_command - Vim(return):Error invoking 'python_execute_file' on channel 4 (python3-script-host):
Traceback (most recent call last):
  File "/var/folders/zt/kmdk_ldx5ygcrbz9k6px6kqh0000gn/T/coc.nvim-9418/coc-ultisnips-8xHkZ8obA3.py", line 271, in <module>
    from vimsnippets import get_comment_format
ModuleNotFoundError: No module named 'vimsnippets'
```

Looks like it comes from:

https://github.com/honza/vim-snippets/blob/b62dfce8449d8a8196720ddd3cfecbca8bb7fe45/UltiSnips/all.snippets#L13

I worked around it by installing honza/vim-snippets myself using vim-plug:

https://github.com/gibfahn/dot/commit/81ef27171c313864b6e8a66349dbc239371c5d96

**Comment by notaduck** [comment]
I'm seen the same error here. @gibfahn did you remove snippets from coc? or just installed honza/vim-snippets alongside coc-snippets?

**Comment by gibfahn** [comment]
I installed vim-snippets, see the link to the commit above (https://github.com/gibfahn/dot/commit/81ef27171c313864b6e8a66349dbc239371c5d96)

**Comment by praveendhawan** [comment]
I removed the snippets which were causing the issue. after that it works. I guess it was related to - https://github.com/neoclide/coc-snippets/issues/123

**Comment by thepenguinthatwants** [comment]
If installing honza/vim-snippets fix this.. I guess its fine but bloat AF.

**Comment by thepenguinthatwants** [comment]
Is this still not fixed? daaarn

**Comment by Kunkgg** [comment]
This error is caused by you are using snippets which included `vimsnippets` python module.
But your neovim python provider can't find it.
`vimsnippets.py` is come from [honza/vim-snippets](https://github.com/honza/vim-snippets). It locates in `honza/vim-snippets/pythonx`.

some code from `honza/vim-snippets/UltiSnips/all.snippets`:
```
##############
# NICE BOXES #
##############
global !p
from vimsnippets import foldmarker, make_box, get_comment_format // !! This line cause the error.!!
LOREM = """
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod \
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At \
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, \
no sea takimata sanctus est Lorem ipsum dolor sit amet.
"""
endglobal
```
To fix this error, you should copy the files in `honza/vim-snippets/pythonx` to your neovim python3 provider environment site-packages directory. 
Or don't use the any snippets which include `vimsnippets.py`.
Or install the `honza/vim-snippets` vim plug.

**Comment by IvanAquino** [comment]
I resolve this problem 
[coc.nvim] Error on execute python script: request error nvim_command - Vim(return):Error invoking 'python_execute_file' on channel 4 (python2-script-host):

pip3 install neovim

**Comment by coderj001** [comment]
I resolve this problem,
```bash
pip3 install neovim
```
then add the following lines to coc-settings.json
```json
    "snippets.ultisnips.directories": [
        "UltiSnips",
        "~/.config/nvim/snips"
    ]
```

**Comment by ayoubelmhamdi** [comment]
i'm update pip by 
```
/path/to/python3 -m pip install --upgrade pip
```
and i'm install Plug 'honza/vim-snippets'  
and i'm deleting ~/.vim/vendor/vim-snippets/{ultisnipets,snippets}  
because i want modified and i dont want update by PlugUpdate

**Comment by omercsp** [comment]
It seems there's no need to actually install the vim-snippets package for things to work. A simpler solution is to copy the entire `pythonx` directory from vim-snippets plugin (it contains 2 files: `vimsnippets.py` and `javascript_snippets.py`) to the where ever you coc plugin is installed. (In my case it's `/home/XXX/.vim/pack/coc/opt/coc.nvim/pythonx` as I'm using optional vim8 package). 
Everything is loaded, working, and no additional package is installed.

**Comment by chemzqm** [comment]
> It seems there's no need to actually install the vim-snippets package for things to work. A simpler solution is to copy the entire `pythonx` directory from vim-snippets plugin (it contains 2 files: `vimsnippets.py` and `javascript_snippets.py`) to the where ever your coc.nvim plugin is installed. (In my case it's `/home/XXX/.vim/pack/coc/opt/coc.nvim/pythonx` as I'm using optional vim8 package).
> Everything is loaded, working, and no additional package is installed.

vim-snippets also provide the function `vim_snippets#Filename` in https://github.com/honza/vim-snippets/blob/master/autoload/vim_snippets.vim#L9, make vim load vim-snippets is recommended, don't copy files to folder of coc.nvim.
