### ISSUE TITLE
vscode svelte: coc doesn't match snippet suggestions that start with `s-`

### ISSUE THREAD

**Issue by cjnucette** [neoclide/coc-snippets#128]
Hi, if you type `s-if`, for example, no suggestion is shown, but if you type a plain `if` it is shown, but you have to go through the list and select it.

vscode svelte: https://github.com/fivethree-team/vscode-svelte-snippets.git

**Comment by chemzqm** [comment]
The completion is triggered by word before cursor, so you have to add `-` to your `&iskeywords` for now.

**Comment by cjnucette** [comment]
Yep. That was it.
