### ISSUE TITLE
Does the coc-snippet plugin supports  those snippets files containing the statement "context "math()""? 

### ISSUE THREAD

**Issue by hrzyhm** [neoclide/coc-snippets#129]
#####################################################################
global !p
texMathZones = ['texMathZone'+x for x in ['A', 'AS', 'B', 'BS', 'C', 'CS', 'D', 'DS', 'E', 'ES', 'F', 'FS', 'G', 'GS', 'H', 'HS', 'I', 'IS', 'J', 'JS', 'K', 'KS', 'L', 'LS', 'DS', 'V', 'W', 'X', 'Y', 'Z']]
texIgnoreMathZones = ['texMathText']
texMathZoneIds = vim.eval('map('+str(texMathZones)+", 'hlID(v:val)')")
texIgnoreMathZoneIds = vim.eval('map('+str(texIgnoreMathZones)+", 'hlID(v:val)')")

ignore = texIgnoreMathZoneIds[0]
def math():
	synstackids = vim.eval("synstack(line('.'), col('.') - (col('.')>=2 ? 1 : 0))")
	try:
		first = next(i for i in reversed(synstackids) if i in texIgnoreMathZoneIds or i in texMathZoneIds)
		return first != ignore
	except StopIteration:
		return False
endglobal
context "math()"
snippet =< "implied by" Ai
\impliedby
endsnippet
#######################################################
The above is part of my snippt file. But the coc-snippet plugin  does not work, while the ultisnipts plugin works well .

**Comment by chemzqm** [comment]
Please provide the code and how to trigger this snippet.

**Comment by hrzyhm** [comment]
################################################
let mapleader=","
imap ,f <Plug>(coc-snippets-expand-jump)
 "Use <C-k> for select text for visual placeholder of snippet.
vmap ,f <Plug>(coc-snippets-select)
" Use <C-k> for jump to previous placeholder, it's default of coc.nvim
let g:coc_snippet_prev = '<c-k>'
"Make <tab> used for trigger completion, completion confirm, snippet expand and jump like VSCode.
let g:coc_snippet_next = '<tab>'
#####################################################
The above is part of my _vimrc file.

**Comment by chemzqm** [comment]
I need source code and cursor position that should trigger this snippet.

**Comment by hrzyhm** [comment]
![1](https://user-images.githubusercontent.com/53509306/80375709-4d9b8d80-88cb-11ea-9217-21761b3e37f2.gif)
![1](https://user-images.githubusercontent.com/53509306/80375808-76bc1e00-88cb-11ea-9ee8-b8b12e5c3083.png)
![2](https://user-images.githubusercontent.com/53509306/80375812-7885e180-88cb-11ea-8d51-bac025c708bf.png)

**Comment by hrzyhm** [comment]
The snippet “lll” works well, while the snippet "mcal" does not work.

**Comment by hrzyhm** [comment]
![1](https://user-images.githubusercontent.com/53509306/80445042-e0790e00-8945-11ea-88fe-3142454034f7.jpg)

**Comment by chemzqm** [comment]
Should be fixed now.

**Comment by fecet** [comment]
The same problem for me
