### ISSUE TITLE
Features for 2.0

### ISSUE THREAD

**Issue by chemzqm** [neoclide/coc-snippets#13]
* [x] Context of snippet.
* [x] Load snipmate snippet.
* [x] Load VSCode snippets from folders contains snippets.
* [x] Standalone user snippets.
* [x] Completion and diagnostics support for snippets file.

**Comment by oblitum** [comment]
One feature that seems cool from UltiSnips is that you can use the regex snippets matching group inside the snippet as argument. For example, this can be used to expand table5 to a table of 5 columns:

```
snippet "table(\d+)" "latex table that provides some flexibility" r
\begin{table}[ht]
\begin{tabular}{|`!p snip.rv = '|'.join(['c'] * int(match.group(1)))`|}
\cline{1-`!p snip.rv = int(match.group(1))`}
${1}{@} `!p snip.rv = '& {@} ' * (int(match.group(1)) - 1)` \\\\
\cline{1-`!p snip.rv = int(match.group(1))`}
\end{tabular}
\end{table}
endsnippet
```

**Comment by chemzqm** [comment]
@oblitum the snippet should works, what result would you expect?

**Comment by oblitum** [comment]
@chemzqm It didn't expand after table5, also, I had to remove quotes, leaving `snippet table(\d+)`, `snippet "table(\d+)"` cause the popup to contain the quote characters on completion.

**Comment by chemzqm** [comment]
> It didn't expand after table5

It expand for me, you need manual trigger expand, completion won't work.

**Comment by oblitum** [comment]
It doesn't expand for me, I just mentioned the completion popup because completion is wrong when there's quotes, I didn't expand from popup, just used it for completion of the word table.

**Comment by chemzqm** [comment]
>  because completion is wrong when there's quotes

What does wrong means, I can't reproduce it.

**Comment by chemzqm** [comment]
Maybe you're using old version of coc-snippets.

**Comment by oblitum** [comment]
I'm on coc-snippets 1.0.19. Bad behavior with quotes is this:

![1](https://user-images.githubusercontent.com/1269815/54078982-83d61200-42b1-11e9-8c07-624841d54100.gif)

No expansion (with or without quotes):

![2](https://user-images.githubusercontent.com/1269815/54078986-95b7b500-42b1-11e9-96e0-5ead14d22251.gif)

**Comment by chemzqm** [comment]
@oblitum What nodejs version are you using? It seems like problem of unsupported regex.

**Comment by oblitum** [comment]
@chemzqm I'm running nodejs 11.11.

**Comment by BonaBeavis** [comment]
Transformations would be nice too.

https://asciinema.org/a/R9rQxfPObLo3g9Az93Imy2nPY

Example is from the ultisnip docs.

**Comment by mnrce** [comment]
**Support for placeholder without tabstop:**

[VSCode-Angular-TypeScript-Snippets](https://github.com/BeastCode/VSCode-Angular-TypeScript-Snippets]) has snippets like:
```json
{
    "prefix": "ng-if-then-else",
    "description": "v4: If then else directive: *ngIf=\"expression; then; else\"",
    "types": "typescript, html",
    "body": [
      "<ng-container *ngIf=\"${expression}; then ${thenTemplate}; else ${elseTemplate}\"></ng-container>",
      "<ng-template #${thenTemplate}>",
      " $1",
      "</ng-template>",
      "<ng-template #${elseTemplate}>",
      " $2",
      "</ng-template>",
      "$0"
    ]
}
```
In VSCode, I can jump to ${expression}, ${thenTemplate} and ${elseTemplate} to change them. But coc-snippets just replace them with empty string.

**Comment by chemzqm** [comment]
@mnrce fixed on latest coc.nvim.
