### ISSUE TITLE
<Plug>CocRefresh in every placeholder

### ISSUE THREAD

**Issue by idopshik** [neoclide/coc-snippets#130]
newly installed Coc and coc-snippets. 
I type "html" then press `<c-e>` to expand  - snipped expands successfully but in every placeholder - <Plug>CocRefresh. 

all my vimrc is:

filetype off                  " required
call plug#begin('~/.vim/plugged')
Plug 'mhinz/vim-startify'             
Plug 'honza/vim-snippets'             

Plug 'neoclide/coc.nvim', {'branch': 'release'} "" Use release branch (Recommend)

Plug 'morhetz/gruvbox'
call plug#end() " }}}
filetype on

imap` <C-e>` `<Plug>`(coc-snippets-expand)

set background=dark
set guifont=Iosevka\ Expanded\ 19
colorscheme gruvbox

**Comment by chemzqm** [comment]
You should not remap `<C-e> `，since plugins have to use it for cancel completion
