### ISSUE TITLE
No "python3" provider found

### ISSUE THREAD

**Issue by numToStr** [neoclide/coc-snippets#131]
When I try to install `coc-snippets` via `let g:coc_global_extensions`, I get this error:

![Screenshot_20200503_193411](https://user-images.githubusercontent.com/24727447/80916283-58479e00-8d75-11ea-9117-f165c5226fd1.png)

Result of `:checkhealth provider`

![Screenshot_20200503_193832](https://user-images.githubusercontent.com/24727447/80916344-b1afcd00-8d75-11ea-98b5-cfcde1de4f46.png)

My system has both python2 and python3, but I guess both are latest that's why I am getting this error.

```bash
$ python2 --version
Python 2.7.18

$ python3 --version
Python 3.8.2
```

## OS
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        20.0
Codename:       Lysia

**Comment by chemzqm** [comment]
Checkout `:h provider-python`
