### ISSUE TITLE
Can't set snippets to highest priority

### ISSUE THREAD

**Issue by cjun714** [neoclide/coc-snippets#132]
My environment:
neovim v0.5.0 + coc  + coc-snippets + clangd-9 on LinuxMint 19.1

Here is the issue:

I use `ic` to expand `#include \<XXX\>", it can work correctly at first:
![1](https://user-images.githubusercontent.com/12163580/81169133-e8caec00-8fca-11ea-884e-5825d565084d.jpg)

But after inserting `#include <string>`, I input a new `ic`, suggestion menu appear lots of new records:
![2](https://user-images.githubusercontent.com/12163580/81169151-f2545400-8fca-11ea-9b2a-79131cb62077.jpg)
You can see snippet `ic` has a very low priority and lies at bottom.
Even "include" from buffer has a higher priority then `ic`.

Below is my CocConfig, `snippets.priority` has been set to 200, and `suggest.languageSourcePriority` has been set to 10, but it still doesn't work:
``` json
{
  "snippets.ultisnips.directories": [
    "snippets-plus"
  ],
  "snippets.priority": 200,
  "snippets.shortcut": "S",
  "snippets.autoTrigger": true,
  "snippets.triggerCharacters": [],
  "snippets.loadFromExtensions": false,
  "snippets.ultisnips.enable": true,
  "snippets.ultisnips.usePythonx": false,
  "snippets.snipmate.enable": false,

  "suggest.noselect": false,
  "suggest.autoTrigger": "always",
  "suggest.triggerCompletionWait": 50,
  "suggest.floatEnable": false,
  "suggest.minTriggerInputLength": 2,
  "diagnostic.signOffset": 99999,

  "suggest.languageSourcePriority": 10,

  "languageserver": {
    "clangd": {
      "command": "clangd",
      "rootPatterns": ["compile_flags.txt", "compile_commands.json"],
      "filetypes": ["c", "cpp", "objc", "objcpp"]
    }
  }
}
```
Please help, thanks a lot!

**Comment by chemzqm** [comment]
Please provide the snippet.

**Comment by cjun714** [comment]
Here is the snippet:
_cpp.snippets_
``` python
# Snippets for CPP

priority 100

snippet /^ic/ "#include <XXX>"
#include <${1:name}>
endsnippet
```
Below is the snippet path:
![3](https://user-images.githubusercontent.com/12163580/81174578-ab6b5c00-8fd4-11ea-9a54-3d310444658a.jpg)

**Comment by chemzqm** [comment]
Use `snippet /^ic/ "#include <XXX>" r` instead, otherwise it's not considered as regex.

**Comment by cjun714** [comment]
Thank you very much, it's my fault of using wrong snippet.
It works perfectly now, thank you!
