### ISSUE TITLE
Snippet won`t write the same symble at the same time

### ISSUE THREAD

**Issue by jidibinlin** [neoclide/coc-snippets#133]
###  example
* snippet expaneded
![1](https://user-images.githubusercontent.com/38578679/81253500-4dce2280-905b-11ea-9ccb-0b00bcd5fb51.png)
* snippet editted but with an exception
![2](https://user-images.githubusercontent.com/38578679/81253537-60485c00-905b-11ea-84a5-eac6ddf0b1fc.png)
* snippet working expected
![2020-05-07_12-04](https://user-images.githubusercontent.com/38578679/81253637-9980cc00-905b-11ea-993d-c58ae089b379.png)

### here is the java snippet 
``` jason
  "newObject": {
    "prefix": "new",
    "body": ["${0:Object} ${1:foo} = new ${0:Object}();"],
    "description": "Create new Object"
  },

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
