### ISSUE TITLE
Error when triggering in-word trigger options

### ISSUE THREAD

**Issue by lygamac** [neoclide/coc-snippets#136]
As  

> Position check of trigger option, including `b`, `w` and `i`.

 is checked and both `b` and `w` works, I suppose that `i` would work too.

However, when trying to trigger in-word, I got the following error:

```
Error on request (doKeymap): Vim(return):Error invoking 'doKeymap' on channel 3 (coc):                            
undefined is not iterable (cannot read property Symbol(Symbol.iterator))
```

Any ideas?

**Comment by lygamac** [comment]
Found the problem.

I have set the jump priority higher than the expand priority as following
```
\ coc#expandableOrJumpable() ? "\<C-r>=coc#rpc#request('doKeymap', ['snippets-jump-expand',''])\<CR>" :
```

Setting the expand before jump solves the problem, but I would like to prioritize jump rather than expand as sometimes the tab introduces unwanted snippets when jumping around with a variable that has similar name to the snippets name.

Any solutions?

**Comment by chemzqm** [comment]
`g:coc_snippet_next` and `let g:coc_snippet_prev` have higher priority since they're buffer key-mappings, configure them with same key.
