### ISSUE TITLE
conflict with vimIM

### ISSUE THREAD

**Issue by Freed-Wu** [neoclide/coc-snippets#137]
when the plugin is used with [vimim](https://github.com/vimim/vimim), a plugin of chinese input method making user can press a hotkey to toggle chinese input mode and english input mode, sometimes they  will conflict, when user is in chinese input mode, it can not input chinese, and popup a complete menu. 

thanks!

**Comment by chemzqm** [comment]
Sorry, you have to make the choice.

**Comment by Freed-Wu** [comment]
so, how can user disable this warning?
![image](https://user-images.githubusercontent.com/32936898/82724002-6b5ee580-9d05-11ea-996b-0ce582bdd2cb.png)

**Comment by chemzqm** [comment]
Disable suggest of coc.nvim, read doc

**Comment by Freed-Wu** [comment]
i have `let b:coc_suggest_disable = 1` but the warning still exists. why?
