### ISSUE TITLE
Visual selected texts have been used several times in visual placeholder

### ISSUE THREAD

**Issue by againxx** [neoclide/coc-snippets#139]
When I select some texts in visual mode and cut them to make them appear in snippet's visual placeholder. The selected texts will be used at least twice, when I continually insert snippets containing visual placeholder. More interestingly, if I insert a snippet that doesn't have normal tabstop, the selected text will be used forever.

I used these two snippets for testing.

![coc-snippets](https://user-images.githubusercontent.com/22728604/82758387-dd741f00-9e18-11ea-9f52-d3faf5d1095e.png)

There are two screenshots for what I have described.

Three print statements have been used twice

![coc_snip1](https://user-images.githubusercontent.com/22728604/82758450-3479f400-9e19-11ea-8aef-3f3a49427a57.gif)
 
The selected texts can never be cleaned up.

![coc_snip2](https://user-images.githubusercontent.com/22728604/82758465-4491d380-9e19-11ea-8336-5e3645586148.gif)

**Comment by againxx** [comment]
My CocInfo:

```
vim version: NVIM v0.5.0-504-g55b62a937
node version: v13.14.0
coc.nvim version: 0.0.78-0c973a7a47
coc.nivm directory: /home/ustc-1314/.vim/plugged/coc.nvim
term: tmux-256color
platform: linux
coc-snipptes: v2.1.26
```

**Comment by chemzqm** [comment]
It always used latest selected text

**Comment by againxx** [comment]
It there a way to wipe out the selected text, if I just want to use it once?

**Comment by chemzqm** [comment]
It should be only used once.
Fixed on latest release branch of coc.nvim.

**Comment by newptcai** [comment]
I still see this behaviour with the latest installation.
