### ISSUE TITLE
Loading causes cursor to flash

### ISSUE THREAD

**Issue by nhooyr** [neoclide/coc-snippets#142]
Hi!

My minimal `init.vim`:

```vim
call plug#begin(stdpath('data') . '/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'neoclide/coc-snippets', {'do': 'yarn install --frozen-lockfile'}
call plug#end()
```

Upon running that and launching `nvim -u /tmp/init.vim`, I see my cursor flash at startup.

Removing `Plug 'neoclide/coc-snippets',` gets rid of the flash.

Any ideas?

**Comment by chemzqm** [comment]
Try minimal vimrc.

**Comment by nhooyr** [comment]
@chemzqm I'm using neovim v0.5.0 so that might be an issue.

Can you reopen though. This is def an issue and I've been able to reproduce it with my minimal `init.vim` with `nvim -u /tmp/init.vim`.

**Comment by chemzqm** [comment]
No

**Comment by nhooyr** [comment]
Can confirm reproduction on `v0.4.3`.

@chemzqm Please reopen!
