### ISSUE TITLE
I have to press <c-j> twice to expand snippets

### ISSUE THREAD

**Issue by wrvsrx** [neoclide/coc-snippets#143]
## CocInfo

vim version: VIM - Vi IMproved 8.2 8020814
node version: v14.3.0
coc.nvim version: 0.0.78-d5471449bf
coc.nivm directory: /home/mars/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Reproduce

1. Use a minimal vimrc with mappings added
```vim
set nocompatible
set runtimepath^=~/.vim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden
imap <c-l> <Plug>(coc-snippets-expand)
vmap <c-j> <Plug>(coc-snippets-select)
imap <c-j> <Plug>(coc-snippets-expand-jump)
```
2. edit all.snippets
```
snippet date "YYYY-MM-DD" w
`!v strftime("%Y-%m-%d")`
endsnippet
```
2. input "date"
3. press \<c-j\>, nothing happens
4. press \<c-j\>, it expands

**Comment by wrvsrx** [comment]
It can also be reproduced in neovim

**Comment by chemzqm** [comment]
Try minimal vimrc

**Comment by wrvsrx** [comment]
As I have written in the post, I just added three mappings into minimal vimrc. Without them, I can't use <c-j>.

**Comment by fannheyward** [comment]
Tested with your minimal vimrc, and same `~/.config/coc/ultisnips/all.snippets`, can't reproduce. `C-j` only once to expand snippet.

**Comment by wrvsrx** [comment]
@fannheyward @chemzqm I'm sorry. I tested it on neovim again and I found that this problem only appears on vim. Besides, sometimes it works well when expanding a snippet at the first time, after that it need to press two times to expand.

**Comment by fannheyward** [comment]
Reproduced with vim 8.2.0900
