### ISSUE TITLE
[Noob Question] Does "choice" syntax from Ultisnips work with coc-snippets? If so, how?

### ISSUE THREAD

**Issue by willfindlay** [neoclide/coc-snippets#146]
Hi, apologies for the noob question. Also not 100% on the correct terminology for what I'm referring to, so I will provide an example.
One of the Ultisnips snippets I got from vim-snippets is like this:
```
    \begin{t(?1:abular)(?2:rray)}{c}
    (?1: & )
    \end{t(?1:abular)(?2:rray)}
```
Presumably there should be a way to choose between option 1 (tabular) and option 2 (array).
Does coc-snippets support this? If so, how does it work?

Here are the bindings I have in my init.vim:
```vim
" Use <C-l> for trigger snippet expand.
imap <C-l> <Plug>(coc-snippets-expand)

" Use <C-j> for select text for visual placeholder of snippet.
vmap <C-j> <Plug>(coc-snippets-select)

" Use tab for trigger completion with characters ahead and navigate.
" Use command ':verbose imap <tab>' to make sure tab is not mapped by other plugin.
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<C-t>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-d>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction
```

**Comment by chemzqm** [comment]
It has support of snipmate choice https://microsoft.github.io/language-server-protocol/specifications/specification-current/#snippet_syntax

**Comment by willfindlay** [comment]
So this more complex choice syntax is not currently support then. Got it, thanks for the info.

**Comment by chemzqm** [comment]
Don't know how that snippet with choice regex works, but we do support choice placeholder of ultisnip, like:
```
snippet q
Your age: ${1|<18,18~60,>60|}
Your height: ${2|<120cm,120cm~180cm,>180cm|}
endsnippet
```

**Comment by chemzqm** [comment]
Choice in regex transform is fixed on lastest coc.nvim and coc-snippets, so your example could work.
