### ISSUE TITLE
Tab mapping on readme only allows selecting the first autocomplete item

### ISSUE THREAD

**Issue by dylan-chong** [neoclide/coc-snippets#147]
```
inoremap <silent><expr> <TAB>
      \ pumvisible() ? coc#_select_confirm() :
      \ coc#expandableOrJumpable() ? "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand-jump',''])\<CR>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
```

When the autocomplete menu is showing 2 or more options, i press tab and the first item is selected but the menu disappears so i can't select other options

**Comment by chemzqm** [comment]
It's expectef

**Comment by dylan-chong** [comment]
Hi, Thanks for your response.
Unfortunately it is inconsistent with autocomplete behaviour with coc.nvim and basically all other autocomplete engines. It is also quite a disruptive user experience, so it would be much appreciated if it could be avoided

**Comment by chemzqm** [comment]
@dylan-chong You should understand what the code does before using it https://github.com/neoclide/coc.nvim/wiki/Completion-with-sources#use-tab-or-custom-key-for-trigger-completion

**Comment by chemzqm** [comment]
明明写的 `coc#_select_confirm` 就是做确认补全的操作，你非要说它不会选中下一项，看看代码能不能动点脑子？
