### ISSUE TITLE
:CocList snippets works but snippets.editSnippet does not

### ISSUE THREAD

**Issue by lpanebr** [neoclide/coc-snippets#149]
I had ultisnippets installed

then I've `:CocInstall coc-snippets` and restarted.

But the none of commands below worked:
 - `:CocList snippets`
 - `:CocCommand snippets.editSnippets`
 - `:CocCommand snippets.openSnippetFiles`

Then I just commented `" Plug 'SirVer/ultisnips'` in my init.vim.
And still nothing worked..

I noticed that `:CocCommand workspace.showOutput snippets` worked and outputs: 
```
[Info 11:45:36 AM] Using ultisnips directories: UltiSnips /home/myuser/.config/coc/ultisnips
[Info 11:45:36 AM] Using ultisnips python command: pyx
```

However none of the other commands work..

I then for no particluar reason I did `npm install` in `/home/myuser/.config/coc/extensions/`

**I believe it's them when things started to partially work:**
 - `:CocList snippets` shows the list of snippets I have in `/home/myuser/.config/nvim/UltiSnips/`
 - `:CocCommand snippets.editSnippets` returns **[coc.nvim] Command: snippets.editSnippet not found**
 - `:CocCommand snippets.openSnippetFiles` **shows the following:**
```
:CocCommand snippets.openSnippetFiles
choose snippet file::
1. /home/myuser/.config/nvim/UltiSnips/vimwiki.snippets
Type number and <Enter> or click with mouse (empty cancels):
```

The completion is working for snippets I currently have but I can't use `:CocCommand snippets.editSnippets` 

Please, how can I fix or what additional information I need to provide?

**Comment by chemzqm** [comment]
It's `snippets.editSnippets`

**Comment by lpanebr** [comment]
> It's `snippets.editSnippets`

Yes. `:CocCommand snippets.editSnippets` is not working. It returns **E492: Not an editor command: snippets.editSnippets**

**Comment by chemzqm** [comment]
Use `:CocList extensions` to make sure coc-snippets is activated.

**Comment by lpanebr** [comment]
I think it's loaded, but I don't know what the `[RTP]` stands for. **Is it the problem?**
```
  * coc-snippets [RTP] 2.1.28 ~/.config/coc/extensions/node_modules/coc-snippets
  * coc-ultisnips 1.2.3 ~/.config/coc/extensions/node_modules/coc-ultisnips
  * coc-snippets 2.1.28 ~/.config/coc/extensions/node_modules/coc-snippets
```

![image](https://user-images.githubusercontent.com/129185/85138334-f786fe80-b218-11ea-8929-e6084088ddd7.png)

**Comment by gbinux** [comment]
I had the same issue and figured it out after reading the [readme and docs from `coc-snippets`](https://github.com/neoclide/coc-snippets): 1. install `pynvim` via pip and make python3 can be found in $PATH; 2. Install the `SirVer/ultisnips` plugin. After this setup, `:CocCommand snippets.editSnippets` worked.
