### ISSUE TITLE
Where do I store snippets?

### ISSUE THREAD

**Issue by joereynolds** [neoclide/coc-snippets#15]
I've tried looking in `:help :coc`, the wiki, and this readme but it doesn't tell you anywhere where to store them.

Where is the correct place?
Thanks!

**Comment by chemzqm** [comment]
You can create a folder with ultisnips snippets and and add absolute path of folder to `snippets.ultisnips.directories`.

**Comment by chemzqm** [comment]
There now default location for store user snippets, use command 
```
:CocCommand snippets.editSnippets
```
to open the snippet file for current filetype.
