### ISSUE TITLE
Cursor flick when using coc-snippets?

### ISSUE THREAD

**Issue by tmpm697** [neoclide/coc-snippets#150]
Produce:
```
install this plugin with neovim
open nvim with/without a file
flick cursor (e.g cursor is _ , then when open file cursor appears then disappear then appear again --> flick)
```
NVIM v0.4.3
archlinux up-to-date

I tested with and without this plugin.

**Comment by Alexey104** [comment]
Have the same behavior on Arch. After opening any file the cursor disappears, and nvim freezes for a couple of seconds until the cursor appears again. No such behavior with 'vim-snippets' disabled.

**Comment by chemzqm** [comment]
It because neovim could be blocked when loading python provider https://github.com/neovim/neovim/issues/5728
