### ISSUE TITLE
Documentation clarification on textmate/VSCode snippet installation

### ISSUE THREAD

**Issue by marcusorjames** [neoclide/coc-snippets#152]
Could I get some clarity on how to get vscode snippets installed.

For example these snippets https://github.com/dsznajder/vscode-es7-javascript-react-snippets

My coc config is as follows:
```json
{
  "snippets.extends": {
    "javascriptreact": ["javascript"],
    "typescriptreact": ["javascript"],
    "typescript": ["javascript"]
  },
  "snippets.textmateSnippetsRoots": [
      "~/.vim/plugged/vscode-es7-javascript-react-snippets/snippets"
  ]
}
```

My output from `CocCommand workspace.showOutput snippets` is:

```
[Info 11:28:00 AM] Using ultisnips directories: UltiSnips /home/marcus/.config/coc/ultisnips
[Info 11:28:00 AM] Using ultisnips python command: pyx
```

And no snippets are showing at all in javascript files.

Thank you

**Comment by chemzqm** [comment]
Use `CocInstall` for snippet extension.

**Comment by marcusorjames** [comment]
Thank you.

So for clarity to install a vscode snippet extension the following worked for me:
```
CocInstall <vscode-extension-uri>
``` 
e.g. 
```
CocInstall https://github.com/dsznajder/vscode-es7-javascript-react-snippets
```

Keep in mind that you may need to yarn install and compile:
```
yarn install --frozen-lockfile && yarn compile //(from extension readme)
```

Another way would be to use a vim plugin manager, which I found in the readme
```
Plug 'dsznajder/vscode-es7-javascript-react-snippets', { \ 'do': 'yarn install --frozen-lockfile && yarn compile' }
```
