### ISSUE TITLE
Loading snippets at start blocks input

### ISSUE THREAD

**Issue by ronakg** [neoclide/coc-snippets#154]
Hi,

I find there's a split second delay in input the first time neovim is opened. Narrowed this down to `coc-snippets` loading the snippets. Uninstalling `coc-snippets` removed the delay for me.

Let me know what kind of logs/data I should capture to help with the investigation.

Edit: The same delay is negligible in vim. However, neovim has a noticeable delay at the start.

**Comment by chemzqm** [comment]
Duplicate of #150
