### ISSUE TITLE
CocAction('deactivateExtension', 'coc-snippets') still proposes snippet completions

### ISSUE THREAD

**Issue by antoinemadec** [neoclide/coc-snippets#156]
First, thanks for the great plugin.

I am currently playing with [vim-visual-multi](https://github.com/mg979/vim-visual-multi) and I would like to disable snippets when entering multi-cursor mode.

So I used:
```vim
:call CocAction('deactivateExtension', 'coc-snippets')
```

The extension appears as **deactivated** but the snippets are still featured in the autocompletion menu.
Is this a bug or am I missing something?

Thanks in advance,
Antoine

**Comment by chemzqm** [comment]
Snippets complete items could come from language servers
