### ISSUE TITLE
Cannot go to previous snippet location.

### ISSUE THREAD

**Issue by ludwj61** [neoclide/coc-snippets#161]
Snippet navigation with binds like c-j & c-k does not seem to be completely working on the current version. I don't know when it stopped working, but with the current release version of COC and this plugin, only the coc-snippet-expand/select/jump is working. The bind associated with g:coc_snippet_prev does nothing.

For example, I am using the "default"/recommended config with: 

```vim
" Use <C-l> for trigger snippet expand.
imap <C-l> <Plug>(coc-snippets-expand)

" Use <C-j> for select text for visual placeholder of snippet.
vmap <C-j> <Plug>(coc-snippets-select)

" Use <C-j> for jump to next placeholder, it's default of coc.nvim
let g:coc_snippet_next = '<c-j>'

" Use <C-k> for jump to previous placeholder, it's default of coc.nvim
let g:coc_snippet_prev = '<c-k>'

" Use <C-j> for both expand and jump (make expand higher priority.)
imap <C-j> <Plug>(coc-snippets-expand-jump)
```
and only c-j and c-l do anything. C-k is essentially unbound.

I am using latest nightly neovim.

**Comment by void-m4110c** [comment]
Why did you close this? Found a solution? I have the same problem

**Comment by chemzqm** [comment]
Check log to  see if snippet session is cancelled

**Comment by void-m4110c** [comment]
Ok, will need to find out how. Will get back to you...

**Comment by void-m4110c** [comment]
```
2020-12-03T17:24:57.066 INFO (pid:8712) [completion-complete] - Results from: snippets,yank,emmet-javascriptreact,around,buffer
2020-12-03T17:25:04.723 INFO (pid:8712) [snippets-session] - Jump to final placeholder, cancelling snippet session
2020-12-03T17:25:05.654 WARN (pid:8712) [Handler] - signature help provider not found!
```

**Comment by chemzqm** [comment]
Final placeholder can be last one or not.
