### ISSUE TITLE
Unable to expand snippet in txt and md files

### ISSUE THREAD

**Issue by yonathanF** [neoclide/coc-snippets#163]
Snippet expansion like ``date`` works fine in files like python and scala, but it breaks in markdown and plaintext files. When I type date, I see the popup options, I can scroll through them using tab and for some I see the preview window (e.g. date~ has 2020-08-13). If I press enter, however, I end up with ``date\n`` i.e. the word "date" followed by a newline. 

Here is my nvim info if it helps: 
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5

Let me know if I can provide more information to help.

**Comment by chemzqm** [comment]
Try minimal vimrc
