### ISSUE TITLE
user snippet break

### ISSUE THREAD

**Issue by grimgort** [neoclide/coc-snippets#164]
my personal snippet is broken when I complete it. I don't know why. my vimrc is available at https://github.com/grimgort/vimrc-bashrc/tree/master/forWindows

ex :
snippet fr_json_string_item "" w
${1:variable} = cJSON_GetObjectItemCaseSensitive(${2:object}, "$1");
if (cJSON_IsString($1) && $1->valuestring != NULL) {
	${3:zev_remplissage}
}
endsnippet

**Comment by chemzqm** [comment]
I've checked it, works as expected.
