### ISSUE TITLE
Snippet doesn’t work after the dot

### ISSUE THREAD

**Issue by foreverLoveWisdom** [neoclide/coc-snippets#166]
I can trigger the snippet for Ruby development if I type the snippet right away *without* the dot. However, it doesn’t work for when  I use with the dot.

For example: 
1. Type *rej* will trigger the snippet (reject method in ruby)

2. Type *random_obj.req* doesn’t trigger the snippet at all. 

So, how can I make the snippets work with the dot syntax. Does it mean that I need to create my own custom snippets for Ruby and all the languages I want to use? I think there should be a better way without me creating my own custom snippets (basically the same) just for it to work with the dot.

**Comment by chemzqm** [comment]
You have to type `.reject` for 
```
snippet "(\S+)\.reject" ".reject do <key>,<value>| <block> end" r
`!p snip.rv=match.group(1)`.reject do |${1:key},${2:value}|
	$0
end
endsnippet
```
completion can't work for it for now.
