### ISSUE TITLE
Ultisnips snippet with "Regular expression" snippet options are not displayed in PUM, but work

### ISSUE THREAD

**Issue by promisedlandt** [neoclide/coc-snippets#17]
UltiSnips snippets with "regular expression (r)" option are not displayed in the PUM. They are expanded 100% correctly (including jumping to placeholders).

Example snippet:

```
 snippet "(\S+)\.det" "<elements>.detect do |<element>| <block> end" r                                                              `!p snip.rv=match.group(1)`.detect do |${1}|
  $0
end
endsnippet
```

If I expand this in an empty line nothing happens, which is correct.
If I expand this after e.g. `[]`, I can get items in the PUM from other sources, like buffer, but not from snippet source. But, when expanding the item, it works fine.

Seems like not high priority bug because I can work with it fine, it's just display issue.

From UltiSnips docs:

>    r   Regular expression - With this option, the tab trigger is expected to
       be a python regular expression. The snippet is expanded if the recently
       typed characters match the regular expression. Note: The regular
       expression MUST be quoted (or surrounded with another character) like a
       multi-word tab trigger (see above) whether it has spaces or not. A
       resulting match is passed to any python code blocks in the snippet
       definition as the local variable "match".

**Comment by chemzqm** [comment]
Because for most of regex patterns, it's not possible to know what should be inserted with complete item, so can't show them in pum.

**Comment by promisedlandt** [comment]
Sure, that makes sense. Also, no problem for me :)

**Comment by danihodovic** [comment]
> Because for most of regex patterns, it's not possible to know what should be inserted with complete item, so can't show them in pum.

@chemzqm Is it possible to enable this behavior anyway? I have a bunch of regex snippets from Ultisnips and I want them to show in the completion menu. If they're not shown I forget they exist.

**Comment by nomasprime** [comment]
Just ran into this. Doubt anyone can remember all their snippets so pretty much makes regex option unusable.

Going to stick with UltiSnips because the short description's helpful but will start refactoring any that use regex.
