### ISSUE TITLE
Hard to understand readme

### ISSUE THREAD

**Issue by nomasprime** [neoclide/coc-snippets#171]
- Not clear what the purpose of `vmap <C-j> <Plug>(coc-snippets-select)` is
- `imap <C-l> <Plug>(coc-snippets-expand)` and `imap <C-j> <Plug>(coc-snippets-expand-jump)` seem to do the same thing

**Comment by chemzqm** [comment]
It's used for select text for `${VISUAL}` placeholder.

**Comment by chemzqm** [comment]
You can select text then invoke snippet like:
```
snippet if "if statement" b
if (${1:true}) {
	${VISUAL}$0
}
endsnippet
```
to make if surrond it.

**Comment by nomasprime** [comment]
@chemzqm niiice!

And what's the difference between `expand` and `expand-jump`?

**Comment by chemzqm** [comment]
`expand-jump` does jump when can't expand at current position.

**Comment by nomasprime** [comment]
@chemzqm I've tried with various snippets and the behaviour appears the same. Would you mind giving an example I can reproduce?

Of course, I'll add to the readme to make it clear for others.

**Comment by nomasprime** [comment]
Could really use an example, everything I've tried they behave the same.

**Comment by jandudulski** [comment]
> Not clear what the purpose of vmap <C-j> <Plug>(coc-snippets-select) is

It was hard for me too but finally get it. If you have a snippet with `${VISUAL}` you can select a block, press `<C-j>` which would remove the block. Then select a snippet and removed block will appear in `${VISUAL}` placeholder.
