### ISSUE TITLE
"once" snippet does not work if it's the first snippet

### ISSUE THREAD

**Issue by gbcwbz** [neoclide/coc-snippets#173]
"once" snippet from[honza/vim-snippets](https://github.com/honza/vim-snippets) in c.snippets 
https://github.com/honza/vim-snippets/blob/master/UltiSnips/c.snippets#L52-L66
```shell
snippet once "Include header once only guard"
#ifndef ${1:`!p
if not snip.c:
	import random, string
	name = re.sub(r'[^A-Za-z0-9]+','_', snip.fn).upper()
	rand = ''.join(random.sample(string.ascii_letters+string.digits, 8))
	snip.rv = ('%s_%s' % (name,rand)).upper()
else:
	snip.rv = snip.c`}
#define $1

${VISUAL}$0

#endif /* end of include guard: $1 */
endsnippet
```
 * If I use "once" snippet after open a file, it will not work, just append "0" to "once"
 * If I use other snippet ("func" for example), and then use "once" snippet it will work perfectly

**Comment by chemzqm** [comment]
Fixed on latest coc-snippets.
