### ISSUE TITLE
Load snippets on demand aka "vendor snippets" for frameworks (e.g. vim-snippets/snippets/rails.vim) 

### ISSUE THREAD

**Issue by jdsutherland** [neoclide/coc-snippets#174]
[vim-snippets](https://github.com/honza/vim-snippets) mentions [vendor snippets](https://github.com/honza/vim-snippets#vendor-snippets) for frameworks like rails where it doesn't make sense to load by default for a filetype. For example, https://github.com/tpope/vim-rails detects rails and loads rails.snippets using `:UltiSnipsAddFiletypes rails`.

How to do this in coc-snippets?

**Comment by chemzqm** [comment]
Not implemented yet.

**Comment by chemzqm** [comment]
You can configure `snippets.extends` in your folder configuration https://github.com/neoclide/coc.nvim/wiki/Using-the-configuration-file
