### ISSUE TITLE
Use snippets, disable completion suggestions

### ISSUE THREAD

**Issue by mb720** [neoclide/coc-snippets#179]
Hi and thanks a lot for CoC snippets!

I'd like to disable CoC's completion suggestions that pop up when I write text, but keep CoC snippets available.

I'm editing a lot of files that are not source code: In these files I use CoC snippets often (I keep them in `nvim/UltiSnips`) but don't want to see the word completion suggestions while writing prose.

For the source code files (Haskell, Rust, Java) I edit, I do like to get completion suggestions (maybe not already after typing the first letter, but that's a nitpick for another time).

From [this issue](https://github.com/neoclide/coc.nvim/issues/349), I know that I can disable CoC entirely with `:CocDisable` but that way I also lose the CoC snippets.

Is there a way to disable only the completion suggestions?

**Comment by chemzqm** [comment]
`autocmd User CocNvimInit call CocAction('toggleSource', 'snippets')`

**Comment by mb720** [comment]
Thanks for your quick reply.

> `autocmd User CocNvimInit call CocAction('toggleSource', 'snippets')`

Could you explain a bit what this command does? When I execute it in a buffer, it doesn't seem to have an effect: I still get completion suggestions. Same when I put it into `init.vim`.

**Comment by mb720** [comment]
I added this to my `init.vim` to disable the suggestions but have the snippets enabled:

    augroup CocSnippetsGroup
      autocmd!
      autocmd BufNew,BufRead * execute "CocDisable"
      autocmd User CocNvimInit call CocAction('toggleSource', 'snippets')
      autocmd BufNew,BufEnter *.java,*.vim,*.haskell,*.rs execute "silent! CocEnable"
    augroup end


This does what I want but incurs a delay of about half second when opening a file, including empty ones.
