### ISSUE TITLE
Snippets contain "endsnippet"

### ISSUE THREAD

**Issue by kollektiv** [neoclide/coc-snippets#181]
Hello, I have coc.nvim 0.0.78 installed with the latest coc-snippets. When I expand a snippet, it includes the actual string`endsnippet` in the expansion. My snippet file is located at `~/.vim/snippets/go.snippets` with

```
# if inline error
snippet ife "If with inline error"
if err := ${1:condition}; err != nil {
	${0:${VISUAL}}
}
endsnippet
```

Autocomplete open
![image](https://user-images.githubusercontent.com/85360/96611487-9304aa80-12b1-11eb-93ed-0d1b893daf4c.png)

After completing
![image](https://user-images.githubusercontent.com/85360/96611946-0efef280-12b2-11eb-8a90-a7734ad43166.png)

My `~/.vimrc` contains

```
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-y>" :
      \ coc#expandableOrJumpable() ? "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand-jump',''])\<CR>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction
```

**Comment by jsteiner** [comment]
I'm seeing this too, with the stock ruby snippets defined here: https://github.com/honza/vim-snippets/blob/master/UltiSnips/ruby.snippets

coc is showing two versions of the same snippet.

The one with quotes around the description inserts the `endsnippet`:

<img width="862" alt="Screen Shot 2020-10-27 at 9 55 49 PM" src="https://user-images.githubusercontent.com/466493/97381298-2f751100-189f-11eb-8852-1693055217e1.png">

The one without quotes acts as it should:

<img width="859" alt="Screen Shot 2020-10-27 at 9 56 04 PM" src="https://user-images.githubusercontent.com/466493/97381317-3865e280-189f-11eb-97ba-a5f2bb166af3.png">

### Versions:
`coc`: `6a1e9c9`
`coc-snippets`: `2.2.2`

**Comment by chemzqm** [comment]
Files in `snippets` folders are considered as snipmate snippets, not ultisnips

**Comment by kristus123** [comment]
So exactly what are we supposed to do when we endounter this error?

**Comment by Elite-zx** [comment]
I encountered the same problem, this is how I solved it:

1. disable snipmate
2. specify ultisnips directory
```
{
 "snippets.ultisnips.directories": ["~/.vim/snippets"],
 "snippets.snipmate.enable":false,
}
```

**Comment by kristus123** [comment]
thank you @Elite-zx
