### ISSUE TITLE
coc complanis all the time about "pattern not found"

### ISSUE THREAD

**Issue by noib3** [neoclide/coc-snippets#183]
While I'm editing, every once in a while I see a bright red error in my commandline complaining about `Pattern not found`, like the following:

![2020-Nov-08@01:44:23](https://user-images.githubusercontent.com/59321248/98454357-f3c22d00-2163-11eb-920c-531099ea10d2.png)

the simplest way to reproduce this is with the following ultisnips snippet:

```
snippet md "Make dollar" A
$$1$
endsnippet
```

After I type `m`, if I select `md` from the completion menu coc doesn't complain, but if I type the remaining `d`, the snippet will expand but the error message will be shown. How can I turn this off?

**Comment by chemzqm** [comment]
Try minimal vimrc

**Comment by noib3** [comment]
@chemzqm The following vimrc should reproduce the issue

```vim
call plug#begin('~/.config/nvim/plugged')
  Plug 'neoclide/coc.nvim'
  Plug 'lervag/vimtex'
call plug#end()

set noshowmode

let g:tex_flavor = "latex"

let g:coc_global_extensions = [
\   "coc-snippets",
\   "coc-vimtex",
\ ]

" coc-snippets
imap <Tab> <Plug>(coc-snippets-expand-jump)
let g:coc_snippet_prev = "<S-Tab>"
```

Without `set noshowmode` no warning is displayed.
