### ISSUE TITLE
How to use S-TAB jump to prev.

### ISSUE THREAD

**Issue by orlandoxu** [neoclide/coc-snippets#185]
![image](https://user-images.githubusercontent.com/8287723/99034878-25e6eb00-25b9-11eb-97ef-aa4c3fbf7e74.png)

How can we use <S-TAB> jump to prev if it'is jumpable?
Now my <S-TAB> is:
```viml
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
```

Thx!!!

**Comment by chemzqm** [comment]
You should not use same key-mappings for completion and snippet jump.
