### ISSUE TITLE
How do I use this extension if I'm not using vim-plug?

### ISSUE THREAD

**Issue by NathanKleekamp** [neoclide/coc-snippets#187]
I'm using Neovim's native package manager, but all the documentation assumes you're using vim-plug. I was able to figure out how to create custom mappings by calling Coc actions for coc.nvim by tracing `coc-definition` to `coc-action-jumpDefinition`, for example, in the help documentation. I'm really struggling with how to do the same thing for the coc-snippets extension, particularly for `coc-snippets-expand` and `coc-snippets-select`, since I haven't been able to find any similar documentation for coc-snippets.

Any help would be greatly appreciated.

**Comment by chemzqm** [comment]
Configuration have nothing to do with how you install coc.nvim

**Comment by NathanKleekamp** [comment]
@chemzqm My question has nothing to do with how to install coc.nvim. I'm trying to understand how to configure mappings for the coc-snippet extension if I'm not using vim-plug.

My references to coc.nvim were only to illustrate how I was able to figure it out on my own using the help docs, which I'm not able to do for this extension

**Comment by varac** [comment]
> I'm using Neovim's native package manager, but all the documentation assumes you're using vim-plug

How do I *install* coc-snippets using Plug ?

**Comment by varac** [comment]
Nevermind, found out myself: `Plug 'neoclide/coc-snippets', {'do': 'yarn install --frozen-lockfile && yarn build'}`
