### ISSUE TITLE
coc-snippets keep reporting "no python3 provider found"

### ISSUE THREAD

**Issue by SamuelDSR** [neoclide/coc-snippets#196]
I have installed **coc-snippets** for neovim. However, it keep reporting "no python3 provider found" when i open neovim.
While i have both `python` and `python3` properly configured using `checkHealth`.
- `CocOpenLog` gives the following information:
```bash
2020-12-27T13:11:42.562 INFO (pid:6815) [plugin] - coc.nvim 0.0.80-7642d233d6 initialized with node: v12.16.1 after 82ms
2020-12-27T13:11:42.610 ERROR (pid:6815) [node-client] - request error on "nvim_command" [
  "exe 'pyxfile '.fnameescape('/tmp/nvimyHfPSz/coc.nvim-6815/coc-ultisnips-fVX0Gj4JWn.py')"
] Vim(pyxfile):E319: No "python3" provider found. Run ":checkhealth provider" Error
    at NeovimClient.request (/home/xxx/.cache/vimfiles/repos/github.com/neoclide/coc.nvim_release/build/index.js:15401:21)
    at NeovimClient.command (/home/xxx/.cache/vimfiles/repos/github.com/neoclide/coc.nvim_release/build/index.js:16329:21)
    at UltiSnippetsProvider.executePythonCode (/home/xxx/.config/coc/extensions/node_modules/coc-snippets/lib/index.js:9002:45)
    at UltiSnippetsProvider.init (/home/xxxx/.config/coc/extensions/node_modules/coc-snippets/lib/index.js:8680:20)
    at async Promise.all (index 0)
    at async ProviderManager.init (/home/xxx/.config/coc/extensions/node_modules/coc-snippets/lib/index.js:6153:9)
```

- `checkHealth`:
```bash
health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - INFO: pyenv: Path: /home/linuxbrew/.linuxbrew/Cellar/pyenv/1.2.21_1/libexec/pyenv
  - INFO: pyenv: $PYENV_ROOT is not set. Infer from `pyenv root`.
  - INFO: pyenv: Root: /home/xxx/.pyenv
  - INFO: Using: g:python_host_prog = "/home/xxx/.pyenv/versions/nvim-py2/bin/python"
  - INFO: Executable: /home/xxx/.pyenv/versions/nvim-py2/bin/python
  - INFO: Python version: 2.7.18
  - INFO: pynvim version: 0.4.2
  - OK: Latest pynvim is installed.

## Python 3 provider (optional)
  - INFO: pyenv: Path: /home/linuxbrew/.linuxbrew/Cellar/pyenv/1.2.21_1/libexec/pyenv
  - INFO: pyenv: $PYENV_ROOT is not set. Infer from `pyenv root`.
  - INFO: pyenv: Root: /home/xxx/.pyenv
  - INFO: Using: g:python3_host_prog = "/home/xxx/.pyenv/versions/3.8.6/envs/nvim/bin/python3.8"
  - INFO: Executable: /home/xxx/.pyenv/versions/3.8.6/envs/nvim/bin/python3.8
  - INFO: Python version: 3.8.6
  - INFO: pynvim version: 0.4.2
  - OK: Latest pynvim is installed.

```

**Comment by chemzqm** [comment]
No idea, it's error from neovim, you can try pyxfile command to see if it works.

**Comment by nvblanco** [comment]
In the case you have not resolved this issue yet, this worked for me
`python3 -m pip install --user --upgrade pynvim`

**Comment by h-des** [comment]
> In the case you have not resolved this issue yet, this worked for me
> `python3 -m pip install --user --upgrade pynvim`

Also worked for me, more details:
https://neovim.io/doc/user/provider.html

**Comment by fred2458** [comment]
> In the case you have not resolved this issue yet, this worked for me
> `python3 -m pip install --user --upgrade pynvim`

Thanks !!

**Comment by devup2332** [comment]
Thanks nvblanco

**Comment by chemzqm** [comment]
You have to install python provider for neovim, or disable ultisnips by `"snippets.ultisnips.enable": false`

**Comment by chemzqm** [comment]
You have to install python provider for neovim, or disable ultisnips by `"snippets.ultisnips.enable": false`

**Comment by tranquanki28** [comment]
Thanks @nvblanco

**Comment by hathawayANdRX105** [comment]
thank~ @nvblanco

**Comment by AniketS01** [comment]
> In the case you have not resolved this issue yet, this worked for me `python3 -m pip install --user --upgrade pynvim`

works fine !

**Comment by ldanielcolmenaresm** [comment]
> En el caso de que aún no haya resuelto este problema, esto funcionó para mí `python3 -m pip install --user --upgrade pynvim`

donde coloco ese comando ?

**Comment by nasdevs** [comment]
> python3 -m pip install --user --upgrade pynvim

thanks bro.

**Comment by pmventura** [comment]
Thanks broo @nvblanco. Also works for me.

**Comment by alexventuraio** [comment]
> In the case you have not resolved this issue yet, this worked for me `python3 -m pip install --user --upgrade pynvim`

Thanks buddy @nvblanco it worked for me. I do not have Python experience so, I'm wondering what this command is doing?

**Comment by nvblanco** [comment]
> > In the case you have not resolved this issue yet, this worked for me `python3 -m pip install --user --upgrade pynvim`
> 
> Thanks buddy @nvblanco it worked for me. I do not have Python experience so, I'm wondering what this command is doing?

The command just installs a python package called pynvim, which is basically a bridge to connect Neovim and Python. In this way, you can use add Neovim plugins developed in Python, as required by Coc-snippets

**Comment by cwfparsonson** [comment]
The above didn't work for me, I had to run `apt install python3-neovim`
