### ISSUE TITLE
Coc-snippets fails with honza/vim-snippets for latex

### ISSUE THREAD

**Issue by sidmadala** [neoclide/coc-snippets#197]
- `nvim --version`: NVIM v0.5.0-dev+nightly
- coc-snippets version:  2.3.1
- `:checkhealth` result: All green
- Operating system/version: MacOS Catalina 10.15.4
- Terminal name/version: Alacritty 0.6.0

### How to reproduce the problem from neovim startup

Normal coc.nvim and coc-snippets install from marketplace.

<details>
<summary>plugins.lua</summary>

```lua
--[[
Packer plugin configuration
--]]

-- Only required if you have packer in your `opt` pack
vim.cmd [[packadd packer.nvim]]

vim.cmd [[ autocmd BufWritePost plugins.lua PackerCompile ]]

require("packer").startup(function()

	-- Essential
	use {"wbthomason/packer.nvim", opt = true}		-- Packer can manage itself as an optional plugin
	use {"svermeulen/vimpeccable"}

        -- LSP
        use {"neoclide/coc.nvim", branch = "release", run = "yarn install --frozen-lockfile", config = 'require("plugins.coc")'}
        use {"antoinemadec/coc-fzf", branch = "release"}
end)
```
</details>

### Actual behaviour

I get the following snippet bug when using coc snippets in latex. The Ultisnips snippets show up with their regular expressions instead of resolving when I use them. I have to fall back to the normal snippet examples.

Ultisnips using coc-snippets:
<img width="951" alt="Screen Shot 2020-12-30 at 6 14 06 PM" src="https://user-images.githubusercontent.com/22417141/103386244-f8ec8a00-4acb-11eb-97fc-202c52b60466.png">

Normal Snippets:
<img width="448" alt="Screen Shot 2020-12-30 at 6 14 10 PM" src="https://user-images.githubusercontent.com/22417141/103386245-f9852080-4acb-11eb-94ec-7d62fbd8a7af.png">

It also fails to place the brackets required for imports in Latex:
<img width="431" alt="Screen Shot 2020-12-30 at 6 26 48 PM" src="https://user-images.githubusercontent.com/22417141/103386394-9e9ff900-4acc-11eb-8200-35d6d8d2c52c.png">

Expected: `\usepackage[options]{package}`

### Expected behaviour

coc-snippets would support these Ultisnips snippets properly and resolve them when used.

**Comment by 3ddiddE** [comment]
I have run into the same problem, for now I have reinstalled the ultisnips
plugin and remapped the trigger mapping to <s-tab> since I am using <tab> for
coc.nvim completion.
A better solution would be a fix of coc-snippets though.

**Comment by 3ddiddE** [comment]
There is also a problem with some snippets that are not even recognized by coc-snippets
For example: ```gentbl(\d+)x(\d+)``` which is a dynamic snippet and works as expected when using the ultisnip shortcut, but fails to show in the suggestions of coc

**Comment by chemzqm** [comment]
The python regex `\L` `\E` can't convert to javascript regex.

**Comment by MatteoGaetzner** [comment]
Is this planned to get fixed anytime soon? Having the same issue.

**Comment by MatteoGaetzner** [comment]
You can find a good workaround here: https://github.com/neoclide/coc-snippets/issues/255

**Comment by chemzqm** [comment]
Need support `UltiSnips-replacement-string` on coc.nvim, will fix that.

**Comment by chemzqm** [comment]
Fixed on latest coc.nvim and coc-snippets.
