### ISSUE TITLE
Cannot load snippets from vim-go

### ISSUE THREAD

**Issue by sebiwi** [neoclide/coc-snippets#199]
Hello,

I just updated all my vim plugins today, and coc-snippets cannot find the vim-go snippets anymore.

I already have this configuration on my coc config:
```
snippets.ultisnips.directories: [
  "UltiSnips",
  "gosnippets/UltiSnips"
],
```

This is the debugging information I have:
```
[Info 12:54:16] Using ultisnips directories: UltiSnips gosnippets/UltiSnips /Users/sebacace/.config/coc/ultisnips
[Info 12:54:16] Using ultisnips python command: pyx
```

Thanks!

**Comment by chemzqm** [comment]
Make sure folder of `vim-go` in your `&runtimepath`
