### ISSUE TITLE
Unrelated text between $ and ; gets removed if using nested snippets and custom mapping

### ISSUE THREAD

**Issue by pjio** [neoclide/coc-snippets#202]
First, thank you for the great plugin!

It might affect other snippet sources as well but I've only tested with an UltiSnips snippet.

This is how I reproduced and narrowed it down:

![coc-snippets-bug](https://user-images.githubusercontent.com/6034781/105329503-843fd380-5bd1-11eb-90e1-c0b557cfe87b.gif)

reprod.vim
```vimscript
call plug#begin('~/.vim/extensions')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
let g:coc_start_at_startup = 1
let g:coc_global_extensions = ['coc-snippets']
call plug#end()
imap <s-tab> <Plug>(coc-snippets-expand)

" this custom mapping triggers the bug:
inoremap ;; ;<cr>
```

UltiSnips/all.snippets
```snippets
snippet snip
---
$1
---
endsnippet
```

the command
```bash
nvim -u reprod.vim reprod.vim UltiSnips/all.snippets -c vsplit -c b2
```
Used versions:
- nvim v0.5.0-dev+950-g5ce328df4
- coc-snippets 2.4.0

I hope it's helpful and maybe someone can confirm, if it affects other versions or configurations!

**Comment by chemzqm** [comment]
Bug of coc.nvim, `$foo` considered as placeholder during insert.

**Comment by chemzqm** [comment]
Fixed on latest master branch of coc.nvim.
