### ISSUE TITLE
Weird expansion with Python Ultisnips 

### ISSUE THREAD

**Issue by acdifran** [neoclide/coc-snippets#204]
For certain python ultisnips, there is additional output added on expansion that should not be there. For example, when tab expanding the "class" snippet via ultisnips, it outputs the template correctly. However, when selecting the same snippet via this plugin, it adds additional output. In this case it looks like it's adding some of the default placeholders to the list of arguments passed to both the class definition and the init method definition, which is causing the extra `MyClass.__init__(self)` call and the weird instance variable definition `self._Docstring for MyClass. = Docstring for MyClass.`

![snippet](https://user-images.githubusercontent.com/25591626/106372857-d9de5380-6328-11eb-89f6-65a46d8e0e57.gif)

I'm guessing this is due to either some incompatibility with python regex or lack of support for an ultisnips feature, but just wondering if there is anyway to fix this. If not, is it possible to disable certain snippets?

Thanks for all the great work!

**Comment by arunanshub** [comment]
Reported this error; follow #230 for reference.

**Comment by chemzqm** [comment]
Fixed by  6e44dcc
