### ISSUE TITLE
Snippet preview window and completion dropdown menu overlap in gnvim

### ISSUE THREAD

**Issue by newptcai** [neoclide/coc-snippets#206]
![Screenshot from 2021-02-17 22-43-38](https://user-images.githubusercontent.com/982197/108302296-ae08fd80-7171-11eb-9240-5a242d4d8fae.png)

When I use tab to finish `for`, I get a menu of possible completions, e.g., "for, fori, ...". But when I use up and down arrow to navigate through the menu, the snippet preview window is hidden behind the completion drop down menu.

**Comment by chemzqm** [comment]
Limitation of your neovim. You have to disable external pupup menu.

**Comment by newptcai** [comment]
Is there a Nemvim GUI which doesn’t have this problem that you know of?
