### ISSUE TITLE
move to previous

### ISSUE THREAD

**Issue by fabriziobertoglio1987** [neoclide/coc-snippets#208]
`<c-j>` to go to `next` works, but `prev` does not work

```
" Use <C-j> for jump to next placeholder, it's default of coc.nvim
let g:coc_snippet_next = '<c-j>'

" Use <C-k> for jump to previous placeholder, it's default of coc.nvim
let g:coc_snippet_prev = '<c-k>'
```

**<details><summary>CLICK TO OPEN TESTS RESULTS</summary>**
<p>

| **Typescript** | 
|:-------------------------:|
| <video src="https://user-images.githubusercontent.com/24992535/108568254-0ffc6b00-730a-11eb-942f-af56a21dbe1b.mp4" /> |

| **Java** | 
|:-------------------------:|
| <video src="https://user-images.githubusercontent.com/24992535/108568706-d5df9900-730a-11eb-9b04-a0b383ca311c.mp4" /> |

</p>
</details>

**Comment by chemzqm** [comment]
Try minimal vimrc

**Comment by fabriziobertoglio1987** [comment]
@chemzqm please reopen as it is not environment issue

as you can see from the videos I have minimal vimrc, I can reproduce with both ubuntugnome and suckless terminal.. Thansk a lot

**<details><summary>CLICK TO OPEN TESTS RESULTS</summary>**
<p>

| **gnome terminal** | 
|:-------------------------:|
| <video src="https://user-images.githubusercontent.com/24992535/108606181-d6366d80-73b8-11eb-9915-99e650c62c33.mp4" width="700" height="" /> |

| **suckless terminal** | 
|:-------------------------:|
| <video src="https://user-images.githubusercontent.com/24992535/108606237-31686000-73b9-11eb-8d5b-a9992ddbfe38.mp4" width="700" height="" /> |

</p>
</details>

**Comment by chemzqm** [comment]
Jump to previous placeholder won't work when you jump to final placeholder, same as VSCode.

**Comment by fabriziobertoglio1987** [comment]
thanks @chemzqm 

I created a custom snipped and find out the reason
with this one I can move back from the body to the main function
```
snippet ta [ "FLog.w(TESTING..)" ]
Object tag = ${1:view}.getTag(R.id.view_tag_native_id);
if (tag instanceof String && (tag.equals("${2:1}") || tag.equals("${3:1}"))) {
	FLog.w("TESTING::", "tag: " + (tag));
	${4}
}
endsnippet
```

because I move to the body with `${4}` while the snippet above mentioned moved to the body with `${0}` and automatically uses insert mode. I was able to reproduce this by using `${0}` instead of `${4}`.

https://github.com/honza/vim-snippets/blob/a8ac81b8922ac621e7043813d98e69ad0ac265a4/snippets/typescript.snippets#L32-L35

```
snippet tfun "ts function"
	function ${1}(${2}): ${3:any} {
		${0}
	}
```
For me would be more smart not using `${0}` and instead of ${4}.

Related https://github.com/honza/vim-snippets/issues/1269
