### ISSUE TITLE
loading snipmate files - what dir?

### ISSUE THREAD

**Issue by chrismazanec** [neoclide/coc-snippets#209]
Hi, what's the correct directory to put snipmate files to be loaded?

ultisnips configs load from `~/.config/coc/ultisnips/` but I cannot seem to find the right dir for snipmate

I did not find this info anywhere.

thanks

**Comment by chemzqm** [comment]
Snipmate snippets are loaded from `snippets` insider folders of your `&runtimepath`, we don't recommended to use it since it's quite limited.
