### ISSUE TITLE
Context snippet not working

### ISSUE THREAD

**Issue by fdschmidt93** [neoclide/coc-snippets#21]
Hi,

the context snippet below defines the math mode context within latex, s.t. relevant snippets are only auto-triggered in math mode (cf. `norm` below). While the below snippet code works within plain UltiSnips, context-sensitive snippets such as `norm` are triggered irrespective of the context with coc-snippets. Not sure whether it's an issue with coc-snippets or the context would have to be reformulated.

Many thanks in advance!

edit: context works also as intended when merely coc-ultisnips is installed

Context snippet:

    global !p
    texMathZones = ['texMathZone'+x for x in ['A', 'AS', 'B', 'BS', 'C', 'CS', 'D', 'DS', 'E', 'ES', 'F', 'FS', 'G', 'GS', 'H', 'HS', 'I', 'IS', 'J', 'JS', 'K', 'KS', 'L', 'LS', 'DS', 'V', 'W', 'X', 'Y', 'Z']]

    texIgnoreMathZones = ['texMathText']
    texMathZoneIds = vim.eval('map('+str(texMathZones)+", 'hlID(v:val)')")
    texIgnoreMathZoneIds = vim.eval('map('+str(texIgnoreMathZones)+", 'hlID(v:val)')")

    ignore = texIgnoreMathZoneIds[0]

    def math():
        	synstackids = vim.eval("synstack(line('.'), col('.') - (col('.')>=2 ? 1 : 0))")
	        try:
		        first = next(i for i in reversed(synstackids) if i in texIgnoreMathZoneIds or i in texMathZoneIds)
		        return first != ignore
	        except StopIteration:
		        return False
    endglobal

Norm snippet with context math():

    context "math()"
    snippet norm "norm" iA
    \|$1\|$0
    endsnippet

CocInfo:

    ## versions
    vim version: NVIM v0.4.0-450-g2d50bf349
    node version: v10.15.3
    coc.nvim version: 0.0.64
    term: screen-256color-bce
    platform: linux
    coc-snippets: 2.0.6

**Comment by chemzqm** [comment]
The problem is it's expect `e` options to be exists for context.
