### ISSUE TITLE
Jump does not behave correctly

### ISSUE THREAD

**Issue by aebkea** [neoclide/coc-snippets#210]
I have the following relevant binding in my init.vim: `imap <tab> <Plug>(coc-snippets-expand-jump)` and the snippet
```snippet
snippet begin "begin{} / end{}" b
\begin{$1}$2
    $0
\end{$1}
endsnippet
```
Using this snippet works as expected when jumping using either <tab> or <c-j> from $1 to $2, then typing anything that's not an open curly brace `{`, but when I type an open curly brace at $2, then it puts the same just after `\end{$1}`, like this
```tex
\begin{problem}{<cursor>}
    
\end{problem}{}
```
where `<cursor>` indicates the location of the cursor. The closing bracket is automatically added by delimitMate or coc-pairs, it doesn't matter which. From this point on, any character that I type will be copied into the bottom, then pressing <tab> or <c-j> puts the cursor precisely at the end of that first line, almost as if it thinks we were still operating in the $1 location. This doesn't happen with square brackets, angle brackets, or alphanumerics. This problem doesn't come up when using the same snippet with Ultisnips instead.

**Comment by chemzqm** [comment]
Fixed on coc.nvim
