### ISSUE TITLE
Explanation for wont-implement features

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [neoclide/coc-snippets#213]
Can you explain why features like `t[1]` and others mentioned in the docs cannot be implemented?

**Comment by chemzqm** [comment]
Because the snippets are converted to textmate snippets which doesn't support update of placeholder and require sync update of snippet (not possible for python code since it needed to be requested from vim)

**Comment by aureooms** [comment]
Thanks!

**Comment by chemzqm** [comment]
Eval for python code is now supported by coc.nvim, try lastest coc.nvim and coc-snippets.
