### ISSUE TITLE
it will dismiss the intro message when activated

### ISSUE THREAD

**Issue by cdnil** [neoclide/coc-snippets#22]
https://github.com/neoclide/coc-snippets/blob/92c2bc612e5d59388fee6869f53906d3805e63c4/src/index.ts#L152

`redraws` command will dismiss the intro message when the window has a status line.
In my opinion, there's no need to disturb user when loading snippets. Usually, it only lasts a little while.

**Comment by chemzqm** [comment]
Use `vim -u NORC` or `nvim -u NORC` if you want to see them.

**Comment by cdnil** [comment]
thanks for your response :)
