### ISSUE TITLE
coc-snippets not loading properly

### ISSUE THREAD

**Issue by dwdwdan** [neoclide/coc-snippets#224]
I've been using coc-snippets for a while but it's suddenly stopped working on my computer. I don't think coc is loading it properly, as when I run `CocList extensions` coc-snippets has a different symbol (`+`) compared to other, working coc extensions (`*`). I have been unable to find documentation on what these symbols mean. I've tried running `CocInstall coc-snippets` but that hasn't made a difference, and it didn't throw any errors. I am able to press `enter` on the working ones to toggle the symbol (I'm assuming this toggles the extensions on and off) but this does nothing for coc-snippets.

Any help would be appreciated

**Comment by fannheyward** [comment]
- `+` means extension is loaded, but not activated for current buffer
- `*` means loaded and activated
- `-` means disabled

Is there any snippets listed in `:CocList snippets`? Is there any error in `:CocCommand workspace.showOutput snippets`?

**Comment by dwdwdan** [comment]
`:CocList snippets` gives the error `List snippets not found`. `:CocCommand workspace.showOutput snippets` opens an empty buffer so no.

**Comment by fannheyward** [comment]
Looks like your coc-snippets is not installed correctly, what's the content of `~/.config/coc/extensions/package.json`?

**Comment by dwdwdan** [comment]
```
{
  "dependencies": {
    "coc-explorer": ">=0.17.2",
    "coc-git": ">=2.3.1",
    "coc-json": ">=1.3.4",
    "coc-snippets": ">=2.4.2",
    "coc-vimtex": ">=1.0.4"
  }
}
```

**Comment by fannheyward** [comment]
Have no idea about this, `:CocCommand workspace.showOutput snippets` should show something like `Loaded 5 snippets from xxxx`.

**Comment by dwdwdan** [comment]
Could it be that it's not finding any snippet file so isn't loading any snippets? Is there a way to uninstall it completely and reinstall it to see if that fixes it?

**Comment by fannheyward** [comment]
If it can't find any snippets, it will list empty in `:CocList snippets`, not an error.

Try `:CocUninstall coc-snippets` and `:CocInstall coc-snippets` again.

**Comment by dwdwdan** [comment]
That hasn't worked, no change in output for any of the commands

**Comment by fannheyward** [comment]
I've try to uninstall and install coc-snippets, works as expected.

**Comment by chemzqm** [comment]
Check log of coc.nvim, seems coc-snippets can't activated, https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim

**Comment by dwdwdan** [comment]
I'm slightly confused what you want me to do @chemzqm, I've installed yarn, cloned the repo and switched to master, but `yarn install` is throwing an error `No such file or directory: 'install'`.

**Comment by chemzqm** [comment]
Fix your yarn first https://yarnpkg.com/getting-started

**Comment by dwdwdan** [comment]
The issue was that I had a broken symlink where it was looking for snippets. I also somehow removed the neovim package from my python install (not sure how I did that) but it seems to be fixed now. Found the error from `:CocOpenLog`
