### ISSUE TITLE
How can I use tab to navigate to the next complete item in the first placeholder?

### ISSUE THREAD

**Issue by gh-liu** [neoclide/coc-snippets#225]
I use <tab> for trigger completion and navigate to the next complete item and for trigger snippet expand and jump to next placeholder. 
When I expand a snippet and want use <tab> to navigate to the next complete item in the first placeholder, it's not work, the cursor jump to next placeholder.

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/wiki/Completion-with-sources#use-tab-or-custom-key-for-trigger-completion
