### ISSUE TITLE
Incorrect ulti snippet expansion

### ISSUE THREAD

**Issue by Avi-D-coder** [neoclide/coc-snippets#23]
![ezgif-4-63d21db9112e](https://user-images.githubusercontent.com/29133776/56073809-a1e2d680-5d77-11e9-9d12-50a50f76dbac.gif)

**Comment by chemzqm** [comment]
Please paster your `:CocInfo`

**Comment by chemzqm** [comment]
And I can't understand how did you make the arrow inserted after current cursor.

**Comment by Avi-D-coder** [comment]
It comes from vim-snippets ultisnips. Pressing space after `)` should add the text `-> `before the cursor.
```rust
snippet pfn "pub fn name(?) -> ? {}"
pub fn ${1:function_name}($2)${3/..*/ -> /}$3 {
	${VISUAL}$0
}
```

**Comment by Avi-D-coder** [comment]
vim version: NVIM v0.4.0-583-gd08692a82
node version: v10.15.3
coc.nvim version: 0.0.65
term: xterm-256color
platform: linux

**Comment by chemzqm** [comment]
Bug of coc.nvim, it should use position cursor to none transform placeholder and adjust cursor position after change.

**Comment by chemzqm** [comment]
Fix on master of coc.nvim.

**Comment by Avi-D-coder** [comment]
thanks
