### ISSUE TITLE
Error on load snippets

### ISSUE THREAD

**Issue by kN1e1ght** [neoclide/coc-snippets#234]
### os
* win 10 20H2
### nvim
* newest nightly
### When I start my nvim i got 
`[coc.nvim] Error on load snippets: files2 is not iterable`
### I did not get any error.

Confusing.help me dalao

**Comment by chemzqm** [comment]
Seems something wrong with your nodejs

**Comment by kN1e1ght** [comment]
> Seems something wrong with your nodejs

how can I get further more info?

**Comment by kN1e1ght** [comment]
Is there something like log files?

**Comment by kN1e1ght** [comment]
And I got another error here:
when i run :coclist extensions I got:
`[coc.nvim] Error on list create: request error nvim_call_function - Vim(buffer):E16: Invalid range: 3buffer`
