### ISSUE TITLE
Snippets in "snippets.userSnippetsDirectory" not suggested

### ISSUE THREAD

**Issue by ChocolateOverflow** [neoclide/coc-snippets#240]
In my `CocConfig`, I have `"snippets.userSnippetsDirectory": "~/git/dotfiles/snippets/"` set, and inside that directory I have python snippets from [honza/vim-snippets](https://github.com/honza/vim-snippets/blob/master/snippets/python.snippets) as suggested, saved as `python.snippets`. With a python file opened, `:CocCommand workspace.showOutput snippets` seems to load the snippets, seeing as `Using ultisnips directories: UltiSnips /home/user/git/dotfiles/snippets/` is in its output. Running `:CocCommand snippets.editSnippets` also does open the correct snippets file `python.snippets`. However, the snippets from that file aren't suggested at all, and only snippets from the extension `coc-python` are suggested.

What am I doing wrong that my snippets aren't suggested?

My dot files: https://github.com/ChocolateOverflow/dotfiles_arch/tree/master/config/nvim

**Comment by chemzqm** [comment]
Many snippets of vim-snippets requires python environment offered by vim-snippets, you have to make sure vim-snippets is loaded as vim plugin.

**Comment by chemzqm** [comment]
We've fixed error catch on vim8, you will get error for this case:

<img width="1252" alt="Screen Shot 2021-08-23 at 16 16 35" src="https://user-images.githubusercontent.com/251450/130414101-37b02559-ac84-4c8f-b86e-540eb517d365.png">
