### ISSUE TITLE
Can I stop the auto extend when the trigger words are fully inserted?

### ISSUE THREAD

**Issue by QuarterHeaven** [neoclide/coc-snippets#241]
For example, there are two snippets:
![image](https://user-images.githubusercontent.com/41909950/129516137-058a4bca-74a4-420c-8208-5b218697f1b0.png)
![image](https://user-images.githubusercontent.com/41909950/129516467-b4ffdf00-1bda-4e3b-a3ae-381d91b316c7.png)
When I typed them, they are extended automatically:
![a](https://user-images.githubusercontent.com/41909950/129525556-b3b273f2-9b62-4579-98ba-dc183b1f45df.gif)
But I want it extends only when I press \<CR\>. Is there any setting to do this?

**Comment by chemzqm** [comment]
You have to remove `A` from snippet option.

**Comment by QuarterHeaven** [comment]
> You have to remove `A` from snippet option.

I got that, Thanks！
