### ISSUE TITLE
Not handling extends

### ISSUE THREAD

**Issue by sQVe** [neoclide/coc-snippets#25]
Hey,

I run my `nvim` setup with [`vim-polyglot`](https://github.com/sheerun/vim-polyglot) which sets `typescript => typescript.jsx` and `javascript => javascript.jsx`. According to `:h g:coc_filetype_map@en` these filetypes get mapped to `javascriptreact` or `typescriptreact`.

My `javascript.snippets` file extends `react.snippets` (which holds specific react snippets) but I cannot for the life of me get them to load. I've tried the following:
  - Create a `javascriptreact.snippets` file that extends `javascript.snippets`
  - Create a `javascriptreact.snippets` file that extends `javascript.snippets` and `react.snippets`
  - Create a `javascript.jsx.snippets` file that extends `javascript.snippets`
  - Create a `javascript.jsx.snippets` file that extends `javascript.snippets` and `react.snippets`
  - `"snippets.extends": { "javascript": ["react"] }`
  - `"snippets.extends": { "javascriptreact": ["react"] }`
  - `"snippets.extends": { "javascriptreact": ["javascript", "react"] }`
  - `"snippets.extends": { "javascript.jsx": ["react"] }`
  - `"snippets.extends": { "javascript.jsx": ["javascript", "react"] }`

As soon as I run `:set ft=javascript` they load fine (but without jsx support).

How am I supposed to get this to work properly?

My snippets files are available here: https://github.com/sQVe/dotfiles/tree/kodama/config/coc/ultisnips

**Comment by chemzqm** [comment]
Should use:
```
  "snippets.extends": {
    "typescript": ["javascript"],
    "javascriptreact": ["javascript"]
  },
```
but it still doesn't work since multiple level inheritance is not supported yet.

Better solution should be rename `react.snippets` to `javascriptreact.snippets` and remove the `extends` line.

**Comment by sQVe** [comment]
@chemzqm Renaming `react.snippets` to `javascriptreact.snippets` does add the react specific snippets but that's it...

The current inheritance implementation seems very broken when having `javascript.jsx`, `typescript.jsx` or `typescript.tsx`. Removing all `extends` lines in my `*.snippets` and using: 

```json
  "snippets.extends": {
    "typescript": ["javascript"],
    "typescriptreact": ["javascript"]
  }
```
This setting does not give me my `javascript.snippets`.

**Comment by sQVe** [comment]
@chemzqm Cheers for the quick fix! Works like a charm now. :pray: :beers:
