### ISSUE TITLE
Snippet expansion on C-l

### ISSUE THREAD

**Issue by bergercookie** [neoclide/coc-snippets#250]
Hi there,

In the README there's the following snippet:

```vim
" Use <C-l> for trigger snippet expand.
imap <C-l> <Plug>(coc-snippets-expand)
```

As far as I can tell, this means that when I have selected the snippet that I want in the popup, it will write the snippet content to the buffer. However, that doesn't seem to work.

I've checked `:verbose imap <c-l` and it has indeed been set to the right directive.

Anything I'm missing?

**Comment by chemzqm** [comment]
It does expand with trigger input, not select snippet in pum.
