### ISSUE TITLE
What is `pythonx`?

### ISSUE THREAD

**Issue by unphased** [neoclide/coc-snippets#251]
I hit the error 

```
[coc.nvim] Error on execute python script: request error nvim_command - Vim(pyxfile):SyntaxError: invalid syntax
```

From the readme: 
> `snippets.ultisnips.usePythonx`: use `pythonx` for eval python code when possible, default `true`.

Please enlighten me. What is `pythonx`? All google knows is that it is a Plasma Cutting Fabrication System™. 

pythonx does not execute a program under any shell environment of mine. 

I have recently had need (to make MacVim work) move my $PATH shenanigans from `~/.zshrc` into `~/.zprofile` and it breaks my vim configuration in this way. I can't figure out why. 

After setting the setting to `false`, 

```
[coc.nvim] Error on execute python script: request error nvim_command - Vim(py3file):E837: This Vim cannot execute :py3 after using :python
```

**Comment by fannheyward** [comment]
Check `:h pythonx`.

**Comment by unphased** [comment]
Ah thank you, it is a vimL specific construct. OK.

**Comment by unphased** [comment]
Something wonky afoot. Mostly with this apple silicon homebrew-supplied vim (not neovim) binary. I'll close this.
