### ISSUE TITLE
Can't load customized snippets in ~/.config/coc/ultisnips/

### ISSUE THREAD

**Issue by damiannmm** [neoclide/coc-snippets#253]
I've tried using [honza/vim-snippets](/honza/vim-snippets) through [junegunn/vim-plug](/junegunn/vim-plug)'s `:PlugInstall` and everything works fine.

But problem started when I'm customizing the snippets,

- When [honza/vim-snippets](/honza/vim-snippets) is still installed,
  + `:CocCommand snippets.openSnippetFiles` prompt both files
  + `:CocList snippets` shows lines of snippets, but none from my custom snippet file  
    (everything are located at `~/.config/nvim/plugged/vim-snippets/snippets/cpp.snippets`)
  + `:CocCommand snippets.editSnippets` reveals my custom snippet  
    (shows `~/.config/coc/ultisnips/cpp.snippets`)
- After uninstalled (it was just for testing after all),
  + `:CocCommand snippets.openSnippetFiles` prompt only custom file
  + `:CocList snippets` shows lines shows nothing
  + `:CocCommand snippets.editSnippets` still reveals my custom snippet

Was it a case sensitive problem in `snippets.ultisnips.directories`?  
I still can't find how to change this though.

**Comment by chemzqm** [comment]
Please checkout output https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel.
Could be python version too old.

**Comment by damiannmm** [comment]
`:checkhealth` shows I'm,

- no using Python2
- no Ruby found
- Python3 ver 3.8.10
- pynvim 0.4.1

**Comment by damiannmm** [comment]
Did check using `:CocCommand workspace.showOutput`, and it shows the custom file (`Using ultisnips directories: ...`) despite the lines of snippet can't be called.

Now, I'm not sure what happened (), but multiple install-uninstall and restarting shell, and now it seems to work! Been bashing my head for 2 hours with this...

Thanks for the quick reply. I'll double check everything and if the problem can no longer be found, I'll close this issue.

**Comment by damiannmm** [comment]
Yep, problem can no longer be found. I can't even replicate this now. The only thing I did that haven't before was checking the workspace output.

Anyway, before closing this issue, are **[Options variables](/neoclide/coc-snippets#options)** located at `coc-settings.json`? As in,

```json
{
  "snippets.priority": 90,
  "snippets.shortcut": "S",
  "snippets.autoTrigger": true
}
```
