### ISSUE TITLE
Coc-snippets doesn't load latex snippets correctly

### ISSUE THREAD

**Issue by khdlr** [neoclide/coc-snippets#255]
I've run into a very weird issue, where coc-snippets would work for all filetypes except latex `.tex` files, using the snippets provided by [honza/vim-snippets](https://github.com/honza/vim-snippets). When opening e.g. a Python file, the snippets works as expeceted, and also show in `:CocList snippets`. However, for `.tex` files, no snippets specific to the file type were loaded (only generic ones show up, like license snippets).

After hopelessly trying to debug this for quite a while, I made an interesting find by accident: When renaming the `tex.snippets` file to `latex.snippets`, everything works as expected. That is, coc-snippets will correctly load snippets from `snippets/latex.snippets`, but not from `snippets/tex.snippets`. This is unexpected as vim uses `tex` for the filetype of latex files, and snippet sources like honza/vim-snippets follow this convention.

I don't know enough about the workings of this plugin, it might well be that the error stems from the combination with another plugin. I posted my reduced `init.vim` below.

Versions and Packages used:
```
nvim: v0.6.1
node: v17.3.0
coc.nvim: 0.0.80-c7a20c8e1f
coc-snippets: 2.4.7
vimtex: latest (84bc5aeb1d6c07f892b39ae99e356d7ab7012476)
coc-vimtex: latest (bcef8f8e02230b782be89306fb80e4c9ead96fec)
```

**Comment by khdlr** [comment]
Here's a minimal `init.vim` which consistently reproduces this behaviour for me:

```vim
set runtimepath+=~/.local/share/dein/repos/github.com/Shougo/dein.vim
if dein#load_state('~/.local/share/dein')
  call dein#begin('~/.local/share/dein')
  call dein#add('~/.local/share/dein/repos/github.com/Shougo/dein.vim')

  call dein#add('neoclide/coc.nvim', {'build': 'yarn install --frozen-lockfile', 'branch': 'release', 'merged': 0})

  " Snippets:
  call dein#add('neoclide/coc-snippets', {'build': 'yarn install --frozen-lockfile'})
  call dein#add('honza/vim-snippets')

  " LaTeX:
  call dein#add('lervag/vimtex', {'on_ft': ['tex', 'plaintex']})
  call dein#add('neoclide/coc-vimtex', {'build': 'yarn install --frozen-lockfile'})

  call dein#end()
  call dein#save_state()
endif

if dein#check_install()
  call dein#install()
endif
```

**Comment by FabianUntermoser** [comment]
I have the same issue. Renaming the files enables my latex snippets again.

**Comment by sdrap** [comment]
I have the same issue after a recent updates of the vimtex and coc plugins. Could not fix it so far. @FabianUntermoser  what do you mean by "Renaming the files enables my latex snippets again."?

**Comment by FabianUntermoser** [comment]
@sdrap As I used the workaround provided by @khdlr, which means renaming the already provided latex snippets from [honza/vim-snippets](https://github.com/honza/vim-snippets). 

In my system they could be found under the `~/.vim/plugged/vim-snippets/snippets` directory. Depending on where you install your plugins, it might be a different directory. I renamed the `tex.snippets` file to `latex.snippets`. Now nvim correctly loads the latex snippets.

**Comment by FabianUntermoser** [comment]
@sdrap Note that without renaming the snippet file, it also shows up in `CocCommand workspace.showOutput snippets``, but it still doesn't work.

**Comment by Littledarren** [comment]
![image](https://user-images.githubusercontent.com/20529233/148240550-caafe18c-be03-4f0b-990f-77f400cb0194.png)

This works for me without editing any specific plugin.

**Comment by FabianUntermoser** [comment]
@Littledarren Adding this configuration in the `coc-settings.json` has made it working for me as well. Thanks! :smile:

**Comment by sdrap** [comment]
I just renamed my `tex.snippets` to `latex.snippets` and now everything is working like a charm :) Thanks @FabianUntermoser

**Comment by erlonbie** [comment]
@khdlr thank you so much for this issue! I was getting crazy for 2 days trying to solve this issue. First I thought it was a Ultisnips issue, but seeing [this](https://github.com/SirVer/ultisnips/issues/490#issuecomment-104385403) I started to look at coc itself, latter I ended up here. I was about to give up

**Comment by chemzqm** [comment]
Caused by [[f7bda319c](https://github.com/neoclide/coc.nvim/commit/f7bda319c0c5a965ed071657108962a381e47336)](https://github.com/neoclide/coc.nvim/commit/f7bda319c0c5a965ed071657108962a381e47336)
