### ISSUE TITLE
feature: remove vscode only script for better Compatibility

### ISSUE THREAD

**Issue by IndexXuan** [neoclide/coc-snippets#26]
some vscode snippets extension use vscode only syntax!
extension like: https://github.com/sdras/vue-vscode-snippets/blob/master/package.json#L16 won't work in coc, since the npm script `vsce` and so on
after remove the npm scripts，it works in coc. (i fork it to my own repo)

so, anyway to take care of that ?

Thanks a lot for coc.nvim

**Comment by chemzqm** [comment]
Fixed

**Comment by IndexXuan** [comment]
Thanks a lot ! life changing ~
