### ISSUE TITLE
snippets with python only work after delay

### ISSUE THREAD

**Issue by ihasdapie** [neoclide/coc-snippets#263]
The following snippet breaks when triggered *fast*, i.e. when typing `1/` it produces 

![image](https://user-images.githubusercontent.com/54821716/156323461-9f467263-2e52-4ef4-82c1-e108dd85035c.png)

and this error in the workspace output
```
[Error 2:11:26 a.m.] Error on get trigger snippets of ultisnips: request error nvim_call_function - Vim(return):Error invoking 'python_eval' on channel 6 (python3-script-host):
error caught in request handler 'python_eval ['snip.rv']':
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pynvim/plugin/script_host.py", line 167, in python_eval
    return eval(expr, self.module.__dict__)
  File "<string>", line 1, in <module>
AttributeError: 'ContextSnippet' object has no attribute 'rv'
```
However if I wait a second or two until the coc.nvim completion menu pops up, i.e. `1<wait a second>/`, it works perfectly fine.
Although it is totally plausible to just wait a few seconds very time before triggering this snippet it becomes rather frustrating while trying to take live lecture notes and find that one's intended `\frac{1}{2}` becomes `\frac{ error message ... }{...`

```
context "math()"
snippet '((\d+)|(\d*)(\\)?([A-Za-z]+)((\^|_)(\{\d+\}|\d))*)/' "symbol frac" wrAe
\\frac{`!p snip.rv = match.group(1)`}{$1}$0
endsnippet
```
This error can be reproduced with this (somewhat) [minimal vimrc](https://raw.githubusercontent.com/ihasdapie/dotfiles/main/nvim/.config/nvim/minimal.vim)

**Comment by ihasdapie** [comment]
```
def math():
	return vim.eval('vimtex#syntax#in_mathzone()') == '1'
```

**Comment by chemzqm** [comment]
Try upgrade your coc.nvim and coc-snippets.

**Comment by ihasdapie** [comment]
I just tried that and the issue persists. Here's a screencapture of the issue:

 https://asciinema.org/a/v9gMvUIYIxXY4BGL3KfttK6vf

The issue is largely nonexistent when I'm working on a desktop or on my laptop while plugged in (and therefore in performance mode) but is really noticeable while I have power management settings set to power saving and with a capped CPU clock rate.
