### ISSUE TITLE
ultisnips "regular expression" snippets duplicated in versions >= 2.5.0

### ISSUE THREAD

**Issue by bartels** [neoclide/coc-snippets#264]
With ultisnips snippets, one can add  `priority` to a snippets file. For example, putting `priority 1`at the top of a snippets file would allow a user's custom snippets in that file to override snippets from other files that have a lower priority. Since the default priority is 0, it means a user can override snippets from e.g. `vim-snippets` with their own versions.

The correct behavior, when there are multiple snippets with the same trigger, is to use the snippet from the file with the highest priority and ignore other snippets with the same trigger from files with a lower priority.  This worked correctly, but has stopped working as of v2.5.0. Now coc-snippets shows a `choose snippet::` popup with a numbered list of choices.

**Comment by chemzqm** [comment]
Try lastest coc-snippets.

**Comment by bartels** [comment]
@chemzqm Yes, the issue is still present in the latest version (2.5.7). Sorry, I should have said the problem started with 2.5.0.  Version 2.4.10 is the last version where `priority` works

**Comment by bartels** [comment]
Closing this since it seems the bug is quite different than I originally thought.
