### ISSUE TITLE
Duplicated snippets with setting `snippets.userSnippetsDirectory` set to `UltiSnips`

### ISSUE THREAD

**Issue by bartels** [neoclide/coc-snippets#265]
I ran into a bit of an edge-case bug here that started in version `2.5.0`

When expanding a "regular expression" snippet, the `choose snippet:` menu is shown but both choices are the same snippet. BUT... this only seems to happen when the setting `snippets.userSnippetsDirectory` set to `UltiSnips` (camel case)

To replicate:

coc-settings.json:
```json
  "snippets.userSnippetsDirectory": "~/.config/nvim/UltiSnips",
```

Then create a regular expression snippet

all.snippets:
```snippet
snippet "foo(bar)?" "foobar test snippet" r
foo bar...
endsnippet
```

If you now expand on `foo` you will get a menu `choose snippet:` shown with two choices. However both choices are the same snippet listed twice.

I suspect this is just an edge-case due to the camel case directory spelling of `UltiSnips` in my settings. It turns out if i remove the setting, everything will work. fine.  And actually, coc-snippets  finds custom snippets in `UltiSnips` directory as well as `ultisnips`, so either spelling works.

The duplication bug shows up if explicitly setting `userSnippetsDirectory` to `UltiSnips` as shown above. It's a bit of an edge-case as most users will probably not have this setting. I had it since I moved to coc-snippets from UltiSnips, and that's the directory it uses.

**Comment by chemzqm** [comment]
Check for same file should consider case-insensitive filepath.
