### ISSUE TITLE
I found it supports VIM and SHELL script, but not python.

### ISSUE THREAD

**Issue by sloppydevil** [neoclide/coc-snippets#267]
My env:
Mac M1, brew vim.

In the README.md, it's said none (vim, shell, python) are supported.
but I tried vim script and shell, it worked.

So maybe it can update a little bit. 😜

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc-snippets#ultisnips-features
https://github.com/neoclide/coc.nvim/pull/3682
