### ISSUE TITLE
Help with example

### ISSUE THREAD

**Issue by AlecMcCutcheon** [neoclide/coc-snippets#269]
Can someone tell me how to make this work:

```
inoremap <silent><expr> <TAB>
      \ pumvisible() ? coc#_select_confirm() :
      \ coc#expandableOrJumpable() ? "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand-jump',''])\<CR>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction
```

let g:coc_snippet_next = '<tab>'

So I have what I think is a LSP? popup when I start typing and I can tab through the results and with the LSP? snippets I see a preview of the code and if I hit enter it writes the snippet, atm coc also gives me snippets in that popup but no preview and it doesn't write the snippet then I click enter. I'm a noob at this stuff and just started messing with neovim a week ago, but I've already gotten a config setup so I'm getting there, just don't know how to get this mapped the same way as the LSP? popup menu. I also don't know if getting this code working will even give me the result I want. I tried to run this in a lua script using vim.cmd and that gave me an error of (using < SID > not in a script context) so I'm hopelessly lost. just point me in the right direction at least

**Comment by AlecMcCutcheon** [comment]
I will note though, if I type "foreach" for example and it has a snippet then I can map a key to coc-snippets-expand then it will write the snippet so its working but I just want it in the menu like the others

**Comment by chemzqm** [comment]
> Make <tab> used for trigger completion, completion confirm, snippet expand and jump like VSCode.

It's explained in readme, read https://github.com/neoclide/coc.nvim/wiki/Completion-with-sources to understand how to make completion work for you.
