### ISSUE TITLE
will this extension working if i set "snippets.ultisnips.enable: false"

### ISSUE THREAD

**Issue by chenjie199234** [neoclide/coc-snippets#276]
i don't have python,so i use the config to disable the ultisnips
i can use :CocCommand snippets.editSnippets to edit my snippets
but it show empty when i use :CocList snippets

**Comment by fannheyward** [comment]
Yes, `coc-snippets` will work with `snippets.ultisnips.enable` to false.

> empty when i use :CocList snippets

You need to install something like `honza/vim-snippets` or `friendly-snippets` to provide snippets.

**Comment by chemzqm** [comment]
You have to install plugin that provide textmate snippets or snipmate snippets, read FAQ.
