### ISSUE TITLE
This extension no longer works for dynamic snippets

### ISSUE THREAD

**Issue by theniceboy** [neoclide/coc-snippets#277]
Normal snippets still work, but for dynamic ones like `datetime`, it expands to
```
`!v strftime("%Y-%m-%d %H:%M")`
```
seems to have stopped working recently

**Comment by chemzqm** [comment]
please upgrade to the latest release branch of coc.nvim.

**Comment by theniceboy** [comment]
Awesome! That fixed it. Thanks!
