### ISSUE TITLE
Help set up a tab key

### ISSUE THREAD

**Issue by D1mon** [neoclide/coc-snippets#28]
I want to press the <tab> key to show me a list with auto-completion and snippet. When you click on the <tab>, it switched to the next line of auto-completion (snippet) and the <Enter> key was used to confirm the required confirmation line. If a snippet is selected, then when you click on the <tab> it will switch to the next field for editing.
* neosnippet
* cquery (autocomplete for c/c++)

If these extensions do not fit, I can install other

**Comment by chemzqm** [comment]
No, neosnippet is not supported.

**Comment by D1mon** [comment]
How to do this in UltiSnips?

**Comment by chemzqm** [comment]
Read readme.
