### ISSUE TITLE
Regex match is replaced in all snippets even if I'm out of them. 

### ISSUE THREAD

**Issue by jfab-123** [neoclide/coc-snippets#281]
Consider the following snippet:
```  
snippet '(\d+)/' "digit frac" rAe 
\frac{`!p snip.rv = match.group(1)`}{$1}$0
endsnippet
```

It expands 1/2 into \frac{1}{2}. Now suppose I type 

```1/2 <tab> 2/3```

This should get converted to 
```\frac{1}{2} \frac{2}{3} ```
however, it is converted to 
```\frac{2}{2} \frac{2}{3}```. 

When I type ```1/2<tab>``` the snippet is expanded correctly to ```\frac{1}{2}```, but **then when I type 2/3** 
the snippet is expanded again to \frac{2}{3}, **however the last placeholder of the previous snippet is _also_  changed to 
2** so \frac{1}{2} becomes \frac{2}{2} which is not what I want, and probably not the expected behaviour

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
