### ISSUE TITLE
Python regex match always points to first match in line, not triggered snippet 

### ISSUE THREAD

**Issue by apilat** [neoclide/coc-snippets#283]
When there are multiple matches in a single line, the `match` object received in Python will point the first match in a line instead of the match the triggered the snippet.

Minimal example:
```
snippet "[ab]" "test" rw
`!p snip.rv = match.group(0).upper()`
endsnippet
```

Type `a b` and expand with cursor after `b`.
I would expect the result to be `a B` but instead we get `a A`.

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
