### ISSUE TITLE
Snippet of ultisnips with context does not work on version ^3.0.6

### ISSUE THREAD

**Issue by relastle** [neoclide/coc-snippets#288]
Thanks for developing and maintaining coc.nvim and other great extensions.

## Summary

From [this commit](https://github.com/neoclide/coc-snippets/commit/b0ab744ab73b599b24276d87f3d80f37cf76f0e8), (possibly [changes around here](https://github.com/neoclide/coc-snippets/commit/b0ab744ab73b599b24276d87f3d80f37cf76f0e8#diff-e0e6d91455eef50c5793e300039e5cdc7e6d372707172b639564495e4fa0a2f3L134) ), ultisnips' snippets with context are not shown in completion menu.

| 3.0.5 | 3.0.6 |
| --- | --- |
| ![Screen Shot 2022-04-29 at 0 12 02](https://user-images.githubusercontent.com/6816040/165787004-387ea9bf-ff0f-49bd-8365-c639262aeb20.png) | ![Screen Shot 2022-04-29 at 0 12 32](https://user-images.githubusercontent.com/6816040/165787048-1a757f44-0956-4ccb-9cb2-c6994de9db08.png)|

#### `~/.config/nvim/init.vim`

(using [vim-plug](https://github.com/junegunn/vim-plug) )

```vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'SirVer/ultisnips'
call plug#end()


let g:coc_global_extensions = [
  \ 'coc-snippets@3.0.6',
  \ ]

let g:UltiSnipsSnippetDirectories = ['UltiSnips']
```

#### `~/.config/nvim/Ultisnips/python.snippets`

```
global !p
def is_always_true() -> bool:
	return True
endglobal

snippet foo "sample snippet" "is_always_true()" be
bar bar bar
endsnippet
```

---

Regards,

**Comment by chemzqm** [comment]
It’s expected https://github.com/neoclide/coc-snippets/blob/master/CHANGELOG.md#306
The check for context requires execute python code on vim and affect completion experience

**Comment by chemzqm** [comment]
You can still expand them after type trigger

**Comment by relastle** [comment]
@chemzqm 

Sorry, I missed the change log.

Then, I want to use 3.0.5.
However, even if I fixed the version of `coc-snippets` like this

```vim
let g:coc_global_extensions = [
  \ 'coc-snippets@3.0.6',
  \ ]
```

`:CocUpdate` command update it to the latest version.

Is there any way to avoid this ?
(In other words, `CocUpdate` updates extensions without version tag into the latest, but leaves extensions with version tag as they are.)

**Comment by chemzqm** [comment]
You have to lock the version before update
