### ISSUE TITLE
Python global snippets not working

### ISSUE THREAD

**Issue by MatteoGaetzner** [neoclide/coc-snippets#289]
Dear coc-snippets team, first of all: I really love this plugin!
Nevertheless, I stumbled across a feature that seems to be missing.
I'm not sure whether it is known to be missing, or whether I've miss configured something, and need your help!

**Behaviour:**
1. Define a global snippet like so:
```
global !p
def foo():
	return 'bar'
endglobal
```
2. Define a normal snippet like so:
```
snippet normal_snip "description"
`!p snip.rv = foo()`
endsnippet
```
3. Result: Snippet 'fails', so coc-snippet detects that there is a snippet called normal_snip (in suggestion list), but upon tab completing it, the the typed text 'normal_snip' vanishes, and there is no output.

**Expected:**
Upon tab-completing normal_snip, 'bar' should be there.

**Comment by chemzqm** [comment]
Check verbose output and make sure your global script is loaded.
