### ISSUE TITLE
Can't get <tab> mapping from Readme to work for snippet expansion

### ISSUE THREAD

**Issue by promisedlandt** [neoclide/coc-snippets#29]
Hello,

I'm trying the "Make <tab> used for trigger completion, completion confirm, snippet expand and jump like VSCode." example from the readme, but the snippet expansion odes not work for me.
Triggering completion etc. work fine, only the call with `coc#rpc#request('doKeymap', ['snippets-expand-jump',''])` does not work. If I replace it with "teststring", that gets inserted. So the correct action gets called in the mapping.
Also, if instead of pressing <tab> I do `<c-r>=coc#rpc#request('doKeymap', ['snippets-expand-jump','']) <cr>`, the snippet gets expanded as expected.
I have another mapping, `imap <c-j> <Plug>(coc-snippets-expand-jump)`, which expands the snippet completely as expected.

Do you have any ideas? 
Unfortunately, even with `NVIM_COC_LOG_LEVEL=debug` snippet completion seems to not be logged. `CocCommand workspace.showOutput snippets` is also empty.

It happens even if CoC is the only plugin, and with minimal vim config.

`verbose imap <tab>`:
```
i  <Tab>       * pumvisible() ? coc#_select_confirm() : coc#expandableOrJumpable() ? coc#rpc#request('doKeymap', ['snippets-expand-jump','']) : <SNR>3_check_back_space() ? "\<Tab>" : coc#refresh()
```
I also have `let g:coc_snippet_next = "<tab>"` set.

```
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 22 2019 12:55:04)
node version: v10.14.2
coc.nvim version: 0.0.65-f7874ec7d7
term: dumb
platform: linux

## Error messages

## Output channel: snippets
```

**Comment by chemzqm** [comment]
Something wrong on vim8.

**Comment by chemzqm** [comment]
The example is broken, you should create map like:
```
inoremap <silent><expr> <TAB>
      \ pumvisible() ? coc#_select_confirm() :
      \ coc#expandableOrJumpable() ? "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand-jump',''])\<CR>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
```
