### ISSUE TITLE
Is there a way to expand a snippet in a snippet?

### ISSUE THREAD

**Issue by TruncatedDinosour** [neoclide/coc-snippets#290]
HI,

I'm making some assembly snippets for myself and syscalls are just one more line 
every one argument, so I wanted to ask, is there a way to expand a snippet in a
snippet?

I want to nest them

example:

```vim
snippet a
    mov rax, 0
endsnippet

snippet b
    {EXPAND SNIPPET a}
    mov rdi, 0
endsnippet

snippet c
    {EXPAND SNIPPET b}
    syscall
endsnippet
```

**Comment by chemzqm** [comment]
No, copy the code instead

**Comment by TruncatedDinosour** [comment]
> No, copy the code instead

Suc, okay, thanks for the reply :)
