### ISSUE TITLE
Nested snippets with python & contexts appends match text to snippet

### ISSUE THREAD

**Issue by ihasdapie** [neoclide/coc-snippets#291]
This issue came up when I recently updated to 3.0.9 and was not an issue before then ( I do not recall what version I was previously on but it was >3.0.0 ) I think this issue is best illustrated with examples:

This is what was entered after typing in 
`eqna/b<ESC>A<CR>a/b` which first triggers the `eqn` and and a regex fraction snippet. (All snippets are included below)

```
\begin{equation}
  \frac{a}{b}a/
  \frac{a}{b}
\end{equation}
```
Note how the matched group appears on the tail end of the snippet.

The desired output would look like this:

```
\begin{equation}
  \frac{a}{b}
  \frac{a}{b}
\end{equation}
```

If I try to trigger the snippet repeatedly on the same line, this is what I get

```
...
  \frac{a}{b}a/  \frac{a}{b}a/   \frac{a}{b}a/ ...
...
```

So it seems to only affect the first time I trigger the snippet and *only* on the the line for which the snippet was first triggered, up until it is deleted 

For example if I get to this state:

```
\begin{equation}
  \frac{a}{b}a/
  \frac{a}{b}
\end{equation}
```
and then delete the second line

```
\begin{equation}
  \frac{a}{b}
\end{equation}
```
and try `a/b` again on that line, we get the intended result
```
\begin{equation}
  \frac{a}{b}
   \frac{a}{b}
\end{equation}
```

Also, this issue goes away if I remove the `math` context from the symbol frac snippet, though it is not apparent to me *why* this would be the case. 

As a summary: 

- `math` context and nested snippet: issue exists
- no `math` context and nested snippet: issue *does not exist*
- `math` context and no nested snippet: issue *does not exist*
- no `math` context and no nested snippet: issue *does not exist*

Here are the snippets in question 

```
def math():
	return vim.eval('vimtex#syntax#in_mathzone()') == '1'
```

```
context "math()"
snippet '((\d+)|(\d*)(\\)?([A-Za-z]+)((\^|_)(\{\d+\}|\d))*)/' "symbol frac" wrAe
\\frac{`!p snip.rv = match.group(1)`}{$1}$0
endsnippet
```

Note that when I edit the above snippet to use a hardcoded string instead of the match group i.e.

```
context "math()"
snippet '((\d+)|(\d*)(\\)?([A-Za-z]+)((\^|_)(\{\d+\}|\d))*)/' "symbol frac" wrAe
\\frac{`!p snip.rv = "asdf"`}{$1}$0
endsnippet
```

The match group is still appended to the snippet, i.e. 
```
\begin{equation}
  \frac{asdf}{b}a/
  \frac{asdf}{b}
\end{equation}
```

```
snippet eqn "equation" wA
\begin{equation}
	$1
\end{equation}
$0
endsnippet
```

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
