### ISSUE TITLE
vscode snippets are only recognized when i rename the file as typescript.json

### ISSUE THREAD

**Issue by bokonist** [neoclide/coc-snippets#293]
I installed the VSCode snippet extension like this:
`Plug 'dsznajder/vscode-es7-javascript-react-snippets', { 'do': 'yarn install --frozen-lockfile && yarn compile' }`

My relevant coc-settings.json looks like this:
![image](https://user-images.githubusercontent.com/23412356/171471259-3cdcb59f-4379-46ca-a5fa-a91fb3b7c12d.png)

The absolute path to the snippets file is `"/home/jay/.config/nvim/plugged/vscode-es7-javascript-react-snippets/src/snippets/generated.json"`

I made a duplicate of the file and renamed it `"/home/jay/.config/nvim/plugged/vscode-es7-javascript-react-snippets/src/snippets/typescript.json"`

The plugin only seems to pickup the snippets when it rename the generated,json to typescript.json, and only seems to be working in ts or tsx files.

`CocCommand workspace.showOutput snippets` output when i run it on a tsx buffer
![image](https://user-images.githubusercontent.com/23412356/171469112-dfe5053c-b5bb-4e78-b05d-69fdbd0483eb.png)

`CocCommand workspace.showOutput snippets` output when i run it on a ts buffer
![image](https://user-images.githubusercontent.com/23412356/171469551-861f8456-80ef-4e5b-b61e-d8017de21094.png)

`CocCommand workspace.showOutput snippets` output when i run it on a jsx buffer.
This is a weird output because it says it loaded the snippets but I'm not getting any snippets triggered in jsx.

![image](https://user-images.githubusercontent.com/23412356/171470219-f63a20e8-002c-474c-af15-7b0dd106e1b7.png)

I'm not really sure if I installed it wrong or some setting i'm missing here that's causing this behaviour.

I am able to get the snippets in jsx and js files when i repeat the same process:
Make a duplicate of generated.json, rename it to javascript.json in the same directory.

**Comment by bokonist** [comment]
I should've read the (heh)  README more closely.

`For VSCode snippets, create ${filetype}.json in your "snippets.textmateSnippetsRoots"`

Is there a way to just use the generated.json file to work with all ts,js,tsx,jsx files? There's a property inside every snippet object as well: `    "scope": "typescript,typescriptreact,javascript,javascriptreact"` in the generated.json

Seems wasteful to duplicate the file for every filetype. Would I have to segregate the snippets into multiple files?

**Comment by chemzqm** [comment]
You should not add the path to `"snippets.textmateSnippetsRoots"` and change the filename.

It works as expected for me:
```
[Info  - 22:44:13.480] Loaded 175 textmate snippets from /vim-dev/vscode-react-javascript-snippets/lib/snippets/generated.json
[
  "javascript",
  "javascriptreact",
  "typescript",
  "typescriptreact"
]
```
