### ISSUE TITLE
Setting coc_filetype_map prevents snippets from loading

### ISSUE THREAD

**Issue by humpangle** [neoclide/coc-snippets#298]
`NVIM v0.7.0`

`eelixir` is the filetype of the elixir template file - it is a supertype of html. So I have this setting so I can use emmet and other html goodies:

```vim
let g:coc_filetype_map = {'eelixir': 'html'}
```

Now snippets declared in `eelixir.json` file are not loaded. If I remove the filetype_map setting, the snippets are loaded.

**Comment by chemzqm** [comment]
Use `"snippets.extends"` configuration.

**Comment by humpangle** [comment]
Thanks for your response @chemzqm. I forgot to mention I currently use that setting as a workaround. I have this in my `coc-settings.json` file: 

```json
{
  "snippets.extends": {
    "html": ["eelixir"]
  }
}
```

But then snippets for `eelixir` files now show up in regular `html` files.
