### ISSUE TITLE
duplicate snippets

### ISSUE THREAD

**Issue by ElcomJ** [neoclide/coc-snippets#302]
Good morning, I recently started using coc-snippets for python, however I noticed that there is a visual bug in the autocomplete menu that displays the same snippet twice, this only happens when I use the `endsnippet` command to be able to work the snippet indentation.

I'll show you some screenshots below to show you what I'm talking about:

File with the snippets:
![03](https://user-images.githubusercontent.com/37147897/182601047-47ec0bbc-88d5-4464-9590-8527f7704828.png)

Snippet without indentation:
![02](https://user-images.githubusercontent.com/37147897/182601072-d87c5cd9-99c0-4748-8072-f81ef3b96c00.png)

Snippet with indentation:
![01](https://user-images.githubusercontent.com/37147897/182601089-c49667a7-5a96-44f5-bf45-c60284dcd8e0.png)

I am using `snippets.userSnippetsDirectory` to be able to indicate the directory of the file with the snippets.

Is there any way to solve this problem?

**Comment by chemzqm** [comment]
You can disable the snippets by configuration like `"snippets.excludePatterns": ["**/coc-python/*.snippets"]`
