### ISSUE TITLE
ultisnips feature of coc-snippets requires pyx support on vim

### ISSUE THREAD

**Issue by Zemelware** [neoclide/coc-snippets#305]
Every time I launch vim I get this error:
`[coc.nvim] Error: Error on execute :pyx command, ultisnips feature of coc-snippets requires pyx support on vim.`

I'm running Kali Linux and I have the latest version of vim and coc-snippets. I don't understand the cause of this error, but after doing some research and seeing that I need to have pynvim installed, I installed it via pip. However, that didn't fix the issue.

Not sure what's going on here since on my Mac, I have the same vim setup and .vimrc file and I'm not getting any error.

**Comment by mnahinkhan** [comment]
Do you have vim compiled with python support?

Try vim --version | grep python

I am facing the same issue right now. I personally do not want to compile vim with python support, and I do not need the "ultisnips" feature.

So can I suppress this error message somehow?

**Comment by chemzqm** [comment]
You can disable ultisnip support

**Comment by Zemelware** [comment]
> Do you have vim compiled with python support?
> 
> Try vim --version | grep python
> 
> I am facing the same issue right now. I personally do not want to compile vim with python support, and I do not need the "ultisnips" feature.
> 
> So can I suppress this error message somehow?

Yes, my vim is compiled with python support, which I need. And I'm assuming the ultisnips feature is what makes the snippets work, in which case I need that feature as well.

**Comment by Zemelware** [comment]
> 



> You can disable ultisnip support

But would that also remove the snippets?

**Comment by Zemelware** [comment]
I got rid of the error by reinstalling vim from source and making sure the python3 patch was included. I don't know if that's what specifically fixed the issue, but I'm no longer getting the error message.

**Comment by mnahinkhan** [comment]
> You can disable ultisnip support

Apologies if this is clearly documented somewhere, is there a variable I can set for that?

**Comment by sqlmap3** [comment]
your coc-settings.json configuration:                                                                                                                                                                            `{
  "snippets.ultisnips.enable": false,
  "snippets.ultisnips.directories": [
    "/your/vim-snippets/snippets"
  ]
}`


1. "snippets.ultisnips.enable": false // Disable UltiSnips support
2."snippets.ultisnips.directories"  // Only use the specified vim-snippets directory
