### ISSUE TITLE
Snippet blue highlight not showing up

### ISSUE THREAD

**Issue by Zemelware** [neoclide/coc-snippets#307]
> Follow latest readme or doc if you have upgrade your coc.nvim. Follow [neoclide/coc.nvim#3886](https://github.com/neoclide/coc.nvim/discussions/3886) for break changes.

I read `h: coc-completion` and I used the example code which fixed the issue for the most part. Now the only problem is the currently selected snippet isn't highlighted (see video below). This is the code I used:
```vim
inoremap <silent><expr> <TAB>
      \ coc#pum#visible() ? coc#_select_confirm() :
      \ coc#expandableOrJumpable() ? "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand-jump',''])\<CR>" :
      \ CheckBackSpace() ? "\<TAB>" :
      \ coc#refresh()

function! CheckBackSpace() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

let g:coc_snippet_next = '<tab>'
```

On my other computer, I get a blue highlight to show the currently selected snippet, however, I don't get this on my Linux machine. How can I fix this? The video below shows the behaviour I want:

https://user-images.githubusercontent.com/61860124/186195067-4095b17e-5cab-4a73-8084-82f025feeb8a.mp4

_Originally posted by @Zemelware in https://github.com/neoclide/coc-snippets/issues/306#issuecomment-1224215373_

**Comment by chemzqm** [comment]
Builtin menu not used, you can create highlight for`CocMenuSel`
