### ISSUE TITLE
new coc popup windows are not used on coc snippets

### ISSUE THREAD

**Issue by otavioschwanck** [neoclide/coc-snippets#308]
<img width="512" alt="image" src="https://user-images.githubusercontent.com/9551316/188285922-c33e0c0e-bf15-4668-921c-b7eaa686b7aa.png">

When snippet has multiple options, it uses the neovim common popup instead of new awesome coc popup.

Snippet:
```
snippet numericality: "numericality: { | }" i
numericality: { ${2|greater_than,greater_than_or_equal_to,less_than,less_than_or_equal_to,equal_to,other_than|}: ${3:100} }
endsnippet
```

**Comment by chemzqm** [comment]
Yes, use the custom popop menu would be too complicated for such case, we can use dialog menu instead.

**Comment by otavioschwanck** [comment]
The problem with the dialog menu is that uses different keybindings for it, so its very annoying.

**Comment by chemzqm** [comment]
I think the buliltin popupmenu is good enough for choices placeholder.

**Comment by otavioschwanck** [comment]
> I think the buliltin popupmenu is good enough for choices placeholder.

The problem is: i use C-j and C-k to navigate on menu.  If the popupmenu appears on snippets, i cannot use =/

**Comment by chemzqm** [comment]
You can remap key-mappings to use them.
