### ISSUE TITLE
Snippets Shortcut

### ISSUE THREAD

**Issue by ElcomJ** [neoclide/coc-snippets#309]
Good afternoon.

I would like to know if there is a configurable command to open a list of only the snippets in order to select them.

Because sometimes I forget the abbreviation I gave for my snippet and I would like to open a list of all my snippets where I can select it.

Congratulations on the Plugin, I look forward to hearing from you :)

**Comment by chemzqm** [comment]
`:CocLIst snippets` opens up a CocList with snippets used by current buffer.

**Comment by ElcomJ** [comment]
Thanks, but how do I select it to open in the buffer?

When I select it with Enter, it opens the buffer where the snippet is written.

**Comment by chemzqm** [comment]
It's used for edit snippets, you need type the trigger

**Comment by ElcomJ** [comment]
I did it, thanks for the help.

I'll be closing the issue now :)
