### ISSUE TITLE
visual snippet trigger after (

### ISSUE THREAD

**Issue by tofulm** [neoclide/coc-snippets#31]
I use coc-snippet with visual snippet : html.json
I don't trigger after '('
With ultsnips, I've option : Position check of trigger option, including b, w and i

Is it possible to add option in json ?

**Comment by chemzqm** [comment]
> Is it possible to add option in json ?

No, json are used for textmate format snippets, which doesn't have that support, use ultisnip snippet instead.

**Comment by tofulm** [comment]
thanks
