### ISSUE TITLE
Unknown function coc#pum#visible

### ISSUE THREAD

**Issue by parthokr** [neoclide/coc-snippets#312]
I am using 

`inoremap <silent><expr> <TAB>
      \ coc#pum#visible() ? coc#_select_confirm() :
      \ coc#expandableOrJumpable() ? "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand-jump',''])\<CR>" :
      \ CheckBackSpace() ? "\<TAB>" :
      \ coc#refresh()

function! CheckBackSpace() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

let g:coc_snippet_next = '<tab>'`
this in my init.vim file.

While using tab on suggestion it shows 

Unknown function coc#pum#visible

**Comment by fannheyward** [comment]
What's your `CocInfo`? Please make sure you're using the latest coc.nvim.

**Comment by parthokr** [comment]
> What's your `CocInfo`? Please make sure you're using the latest coc.nvim.

Solved. Thank you for your response.
