### ISSUE TITLE
Incompatible snippet shows up as an empty snippet

### ISSUE THREAD

**Issue by Avi-D-coder** [neoclide/coc-snippets#32]
From vim-snippets haskell

ultisnips
```
snippet impq "Qualified import"
import qualified ${1:Data.Text} as ${0:`!p snip.rv = t[1].split(".")[-1]`}
endsnippet
```
snipmate
```
snippet impq
	import qualified ${1:Data.Text} as ${0:T}
```

Completing `impq` inserts nothing else.
Since the ultisnips snippet did not parse the snipmate one should be used.
If I rename the snipmate snippet I can use it, but the broken ultisnips snippet remains.

**Comment by chemzqm** [comment]
Can't reproduce, both snippets works as expected for me.

**Comment by Avi-D-coder** [comment]
```vim
call plug#begin()
Plug 'neoclide/coc.nvim', {'do': 'yarn install'}
Plug 'honza/vim-snippets'
let g:coc_global_extensions=["coc-snippets"]
call plug#end()
```

`nvim -u minirc.vim test.hs`

reproduce the problem for me.

I don't have coc-ultisnips installed, could that be the difference?

**Comment by chemzqm** [comment]
No, maybe you're using old version of coc-snippets.

**Comment by Avi-D-coder** [comment]
I'm on `2.0.16`

**Comment by chemzqm** [comment]
Don't know the reason, you can debug it https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim.

**Comment by Avi-D-coder** [comment]
Does this require neovim python 2 bindings?

**Comment by Avi-D-coder** [comment]
Installing python 2 neovim bindings fixed it. Python 3 was not cutting it.
