### ISSUE TITLE
<Plug>(coc-snippets-expand) and <Plug>(coc-snippets-expand-jump) don't work

### ISSUE THREAD

**Issue by ohmyhilbert** [neoclide/coc-snippets#322]
These two keymaps are no longer exist in imap list when using latest version of coc-snippets. As a result, \<C-j>, which is mapped to \<Plug>(coc-snippets-expand-jump) for example, just print the text "\<Plug>(coc-snippets-expand-jump)" instead of calling a function.

**Comment by renatoram** [comment]
Confirmed, I'm seeing the same behavior.

There are other problems with snippet completion that seem to have appeared recently but I suspect they might have the same origin.

**Comment by chemzqm** [comment]
Should be fixed on latest release branch of coc.nvim.

**Comment by firstmover** [comment]
Does it mean these two functions are no longer supported in the future version? I still prefer a different trigger for <Plug>(coc-snippets-expand) (such as <C-f> instead of using <tab> which must wait until the completion preview appears). How should I configure my vimrc?
