### ISSUE TITLE
Snippets item with wrong selected priority in suggestion menu

### ISSUE THREAD

**Issue by cjun714** [neoclide/coc-snippets#326]
Neovim 0.83
Ubuntu 22.04

:CocConfig
``` json
{
  "snippets.ultisnips.directories": ["snippets-plus"],
  "snippets.priority": 99,
  "snippets.shortcut": "S",
  "snippets.triggerCharacters": ["."],
  "snippets.ultisnips.enable": true,

  "suggest.languageSourcePriority": 50,

  "languageserver": {
    "golang": {
      "command": "gopls",
      "rootPatterns": ["go.mod", ".vim/", ".git/", ".hg/"],
      "filetypes": ["go"],
      "initializationOptions": {
        "usePlaceholders": true,
        "deepCompletion": false,
        "completeUnimported": true
      }
    }
  }
}
```
 
![image](https://user-images.githubusercontent.com/12163580/224688043-ecf30483-bdb4-4ea4-b7d5-d04f498d4ae9.png)

`le` `lee` is my local ultisnips snippets,
when I type `le`, suggestion menu shows `le~` as the 1st item and `lee~` as the 2nd item, that's right.
but the selected item is automatic focused on `len~` which is provided by lsp, and that is the 3rd item which should never automatically be selected.

When I type `l`, same issue happened, coc automatically focus on `log~`
![image](https://user-images.githubusercontent.com/12163580/224689752-60dbd8c0-dbfd-4950-9f28-4369ff9c5792.png)

I can't find any new configuration for this issue, please help
thanks

**Comment by chemzqm** [comment]
Use configuration `"suggest.enablePreselect": false` to disable preselect, or use `<Plug>(coc-snippets-expand)` to expand snippet without select.
