### ISSUE TITLE
[Request] Implment snip.expand_anon

### ISSUE THREAD

**Issue by SeniorMars** [neoclide/coc-snippets#327]
Hello, could this be implemented: expand_anon from ultisnippets?

The reference is here: https://github.com/SirVer/ultisnips/blob/0ad238b1910d447476b2d98f593322c1cdb71285/pythonx/UltiSnips/text_objects/python_code.py#L54 and here: https://github.com/SirVer/ultisnips/blob/0ad238b1910d447476b2d98f593322c1cdb71285/pythonx/UltiSnips/snippet_manager.py#LL297

Implementing this would allow snippets like:

```py
global !p
def create_matrix_placeholders(snip):
	# Create anonymous snippet body
	anon_snippet_body = ""

	# Get start and end line number of expanded snippet
	start = snip.snippet_start[0]
	end = snip.snippet_end[0]

	# Append current line into anonymous snippet
	for i in range(start, end + 1):
		anon_snippet_body += snip.buffer[i]
		anon_snippet_body += "" if i == end else "\n"

	# Delete expanded snippet line till second to last line
	for i in range(start, end):
		del snip.buffer[start]

	# Empty last expanded snippet line while preserving the line
	snip.buffer[start] = ''

	# Expand anonymous snippet
	snip.expand_anon(anon_snippet_body)

def create_matrix(cols, rows, sep, start, end):
	res = ""
	placeholder = 1
	for _ in range(0, int(rows)):
		res += start + f"${placeholder} "
		placeholder += 1
		for _ in range(0, int(cols) - 1):
			res += sep + f" ${placeholder} "
			placeholder += 1
		res += end
	return res[:-1]
endglobal

post_jump "create_matrix_placeholders(snip)"
snippet 'arr(\d+),(\d+)' "LaTeX array" br
\begin{array}{`!p
orient = ""
for _ in range(0, int(match.group(1))): orient += "l"
snip.rv = orient`}
`!p
snip.rv = create_matrix(match.group(1), match.group(2), "&", "\t", "\\\\\n")
`$0
\end{array}
endsnippet
```

to work for this 

https://github.com/SirVer/ultisnips/blob/master/doc/examples/tabstop-generation/demo1.gif?raw=true

This would make my day in Latex, and I would appreciate it.

**Comment by fannheyward** [comment]
https://github.com/neoclide/coc-snippets/issues/67
https://github.com/neoclide/coc-snippets/issues/205

**Comment by chemzqm** [comment]
Need communication between python and node process, should be possible, I think.

**Comment by SeniorMars** [comment]
Thank you for this! But like in the demo, I have `arr9x3` and I expect to be able to jump to the `$1` through `$27` and modify them -- is post jump implemented?

**Comment by SeniorMars** [comment]
Or is there a setting I'm missing?

**Comment by chemzqm** [comment]
No support for `post_jump` yet.
