### ISSUE TITLE
Stop $0 does not work

### ISSUE THREAD

**Issue by Avi-D-coder** [neoclide/coc-snippets#33]
snipmate
```
snippet imp
	import ${0:Data.Text}
```

Expected behavior
Selected `Data.Text` instead the cursor is before `Data.Text`

Changing the snippet fixes the problem.
```
snippet imp
	import ${1:Data.Text}
```

**Comment by chemzqm** [comment]
Becaue internal textmate doesn't support it.

**Comment by Avi-D-coder** [comment]
So are you saying that won't work with native ultisnips or snipmate? It's from vim-snippets. Should I submit a PR there?

**Comment by chemzqm** [comment]
No, it's problem of textmate snippet parse used by coc.nvim.

**Comment by chemzqm** [comment]
Fixed on master of coc.nvim

**Comment by Avi-D-coder** [comment]
Thanks.

**Comment by Avi-D-coder** [comment]
@chemzqm This is occurring again
