### ISSUE TITLE
Parse error while loading vscode snippets

### ISSUE THREAD

**Issue by Ishida0216** [neoclide/coc-snippets#331]
![image](https://github.com/neoclide/coc-snippets/assets/58908827/92dbafa2-2199-4ebb-9308-280b3a45afbf)

This is the code snippet that I created.
But when I run workspace.showOutput snippets command, I get the following error:

![image](https://github.com/neoclide/coc-snippets/assets/58908827/04778193-42a8-4a81-bf31-c65f309a419a)

How do I fix it?

**Comment by chemzqm** [comment]
Seems not well-formed json
