### ISSUE TITLE
choice tabstop does not work with some special characters

### ISSUE THREAD

**Issue by xi-lef** [neoclide/coc-snippets#332]
The following snippet:

```
snippet testchoice
this produces "1.2.0" instead of "2.0" if you select the second option: ${1|1.0,2.0|}
endsnippet
```

produces wrong output if the 2nd option is selected.  
It seems like the '.' is treated specially, and the "1." does not get removed because of that. This has not always been the case, but I am not sure if this is an issue with coc-snippets or maybe with coc in general.

Maybe you can help with this problem? :)

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
