### ISSUE TITLE
Does not work on neovim 0.7.2, what is the minimum version supported?

### ISSUE THREAD

**Issue by fflorent** [neoclide/coc-snippets#338]
When using coc-snippets on neovim 0.7.2 (version packaged on Debian), I could not manage to make the plugin work, I faced this issue: https://github.com/neoclide/coc-snippets/issues/322 (when attempting to use `<c-j>`, I get "<Plug>(coc-snippets-expand-jump)" printed).

When using neovim 0.9.1, everything works fine.

**Comment by fannheyward** [comment]
Tested with nvim 0.7.2, `C-j` can jump to next snippet position with default mapping. But failed with `imap <C-j> <Plug>(coc-snippets-expand-jump)`.

**Comment by chemzqm** [comment]
Something wrong with nvim 0.7.2, should be bug of nvim.
