### ISSUE TITLE
Snippet 'fori' cannot jump to the `type` placeholder

### ISSUE THREAD

**Issue by liuyehcf** [neoclide/coc-snippets#340]
snippet `fori` is like this:

```cpp
    for (int i = 0; i < count; i++) {

    }
```

 It has four placeholders, which respectively are `count`、`0`、`i++`、`int` of the above case.

When I use `coc-snippets`(`3.1.6`) to drive the snippet, it only iterate the first 3 placeholders.

And when I change to 'SirVer/ultisnips', it works fine for iterating the 4 placeholders.

And for lower version of `coc-snippets`, maybe `2.8.x`(not for sure, but must be 2.x), it also works fine.

**Comment by fannheyward** [comment]
Which language? can you post the snippet file?

**Comment by liuyehcf** [comment]
```
## Iteration
# for i
snippet fori
	for (int ${2:i} = 0; $2 < ${1:count}; $2${3:++}) {
		${4}
	}
```

**Comment by fannheyward** [comment]
Tested this snippet in cpp file, jumping follows the `count` - `i` - `++` - body placeholder, the 4th.
