### ISSUE TITLE
Do I have to install honza/vim-snippets?

### ISSUE THREAD

**Issue by tracyone** [neoclide/coc-snippets#341]
Q: Get error message ModuleNotFoundError: No module named 'vimsnippets'

A: Make sure [honza/vim-snippets](https://github.com/honza/vim-snippets) in your vim's &runtimepath.

I met the same question.  But I don't want to install honza/vim-snippets, I created my own snippets github repo base on honza/vim-snippets long time ago and modified snippets according my need.

**Comment by chemzqm** [comment]
You don't have to install honza/vim-snippets, but seems your snippet file use module named `vimsnippets`, copy the file `vimsnippets.py` to pythonx inside one of your vim's runtimepath.
