### ISSUE TITLE
Snippets after ':' & highlighting

### ISSUE THREAD

**Issue by lgick** [neoclide/coc-snippets#342]
I am using [honza/vim-snippets](https://github.com/honza/vim-snippets).
I have two problems:

1 Snippets are not displayed after pressing ':'

![Запись экрана 2023-09-21 в 16 48 46](https://github.com/neoclide/coc-snippets/assets/2997257/427e25dd-5082-49df-8880-8cc79af0d347)

2 Sometimes the selected snippet is not highlighted

![Запись экрана 2023-09-21 в 16 57 15](https://github.com/neoclide/coc-snippets/assets/2997257/0c1561b1-4382-4385-938c-d05042bc1a88)

**Comment by chemzqm** [comment]
> 1 Snippets are not displayed after pressing ':'

Use `"snippets.triggerCharacters": [":"]` in your coc-settings.json.

**Comment by lgick** [comment]
> Use `"snippets.triggerCharacters": [":"]` in your coc-settings.json.
> 
> >

I did this, but some snippets is not visible.


```
snippet :f "Object Method"
${1:method_name}: function`!p snip.rv = space_before_function_paren(snip)`(${3:attribute}) {
	${VISUAL}$0
}${10:,}
endsnippet
```

https://github.com/neoclide/coc-snippets/assets/2997257/d628d993-1899-447f-86b3-fdb81b8314c2

**Comment by kevin61416** [comment]
I think this issue is similar to my issue #330 :
snippets are also not displayed after pressing `#` or `#!`

**Comment by lgick** [comment]
> Use `"snippet.highlight": true` to enable highlight for current placeholder.

It has not solved the problem

with option:
<img width="678" alt="Снимок экрана 2023-09-21 в 19 03 17" src="https://github.com/neoclide/coc-snippets/assets/2997257/b79435cc-99c3-4745-ade5-6d2b58fc0dd9">

without option:
<img width="459" alt="Снимок экрана 2023-09-21 в 19 04 09" src="https://github.com/neoclide/coc-snippets/assets/2997257/5e4d3e24-a238-4208-942b-55079bee26c0">


My problem with snippets list:

work:
<img width="615" alt="Снимок экрана 2023-09-21 в 19 08 30" src="https://github.com/neoclide/coc-snippets/assets/2997257/b496fb72-26e1-49b7-bdba-55df2aa02399">

doesn't work:

<img width="586" alt="Снимок экрана 2023-09-21 в 19 11 58" src="https://github.com/neoclide/coc-snippets/assets/2997257/97fdda0e-1469-47a8-aaf8-c710d015d584">
