### ISSUE TITLE
snippets.json are not loaded if ts-snippet.json exists

### ISSUE THREAD

**Issue by JakeHedman** [neoclide/coc-snippets#35]
An upgrade of `vscode-es7-javascript-react-snippets` added a `ts-snippets.json` file with some extra snippets, this causes coc-snippets to only load `ts-snippets.json` and ignore `snippets.json`.

Example: https://github.com/dsznajder/vscode-es7-javascript-react-snippets/tree/master/snippets

**Comment by chemzqm** [comment]
https://github.com/dsznajder/vscode-es7-javascript-react-snippets/blob/master/package.json#L47 both loaded, they're used for different languageId.

**Comment by chemzqm** [comment]
Use `"snippets.extends"` to extend snippets.
