### ISSUE TITLE
:CocCommand snippets.editSnippets opens wrong file on windows+WSL

### ISSUE THREAD

**Issue by dylnmc** [neoclide/coc-snippets#37]
Hi, I use gvim.exe but I always start XLaunch, which essentially provides an X server, and I also have WSL. I don't exactly know how all of the pieces fit together, as it is quite a mess, but I do know this: when I type `:CocCommand snippets.editSnippets`, it opens "AppData/Local/coc/ultisnips/*.snippets" rather than "C:/Users/myuser/coc/ultisnips".

My `$VIMCONFIG` is "C:\Users\myuser/vimfiles" and I have `snippets.ultisnippets.directories = "C:/Users/myuser/vimfiles/coc/ultisnips/", but the editSnippets command still opens the appdata location.

Hopefully, you can spot something. Thanks,

**Comment by chemzqm** [comment]
It's expected, it always open ultisnips folder in your extension root, instead of folder from directories configuration.

**Comment by dylnmc** [comment]
@chemzqm how is it possible to create a snippet plugin or manage snippets in my vim config directory? every other snippets plugin allows you to specify where snippets go and this means that, for example, `:UltiSnipsEdit` will edit the correct files in the correct directories rather than a non-user-specified static path (which is particularly useless unless you only ever use one machine or are willing to copy additional files to various locations outside of git management to all of the machines you will work on in the future).

**Comment by chemzqm** [comment]
> This is both clean/simple and powerful and allows users to customize snippets at arbitrary locations.

Most user have multiple snippets file in different locations for single filetype,  use snippets list is reommended to edit them.

It's designed to have single directory for user's custom ultisnip snippets which opened by `CocCommand snippets.editSnippets`.

It's designed to not use any configuration of ultisnips, so there won't be support of `g:UltiSnipsSnippetsDir` or `:UltiSnipsEdit`, but it's ok support a custom root of user snippet directory.

**Comment by oblitum** [comment]
> use snippets list is reommended to edit them.

@dylnmc `:CocList snippets`

**Comment by chemzqm** [comment]
Use `snippets.userSnippetsDirectory`

**Comment by mulholio** [comment]
> Use snippets.userSnippetsDirectory

@chemzqm I'm confused by this recommendation

I've set this in my `coc-settings.json`:
```
{
  "snippets.userSnippetsDirectory": "~/.dot-files/vim/UltiSnips"'
}
```

But when I run `CocCommand snippets.editSnippets`, a file here opens instead: `/Users/jamesmulholland/.config/coc/ultisnips/typescript.snippets

I also fail to see any snippets in `~/.dot-files/vim/UltiSnips`  showing up in `CocList snippets` or the auto -complete popup.

How do I keep my snippets where I want them but get them loaded and editable with coc?

**Comment by chemzqm** [comment]
@mulholio I can't reproduce your problem

**Comment by mulholio** [comment]
Is that because I haven't added enough info or because it's just not doing the same thing on your machine?

I have a folder with all my snippets in `~/.dot-files/vim/Ultisnips`. This is also symlinked to my home directory. This folder contains multiple `.snippets` files

**Comment by Melkster** [comment]
@mulholio 
> I've set this in my `coc-settings.json`:
> 
> ```
> {
>   "snippets.userSnippetsDirectory": "~/.dot-files/vim/UltiSnips"'
> }
> ```

`"~/.dot-files/vim/UltiSnips"'` has a trailing `'`, could that be the problem?
