### ISSUE TITLE
Vim hangs when expanding some snippets

### ISSUE THREAD

**Issue by trygveaa** [neoclide/coc-snippets#38]
## Description

When using `coc-snippets-expand` to expand some snippets which only contain one placeholder, vim will hang for a long time. When it completes, the snippet will contain a `0` where the cursor was, in the middle of the snippet. E.g. `co0nsole.log();` instead of `console.log();`, and the cursor will be positioned one character too far to the left.

I can't confirm for sure that the issue only happens with snippets with only one placeholder, but I haven't experienced the issue with other snippets. The snippets that I have tested where the issue occurs are `cl`, `cd`, `ed`, `has` and `ret` for javascript files, and `ret` and `fut` for python files. All of these contain `${0}`, except for `ret` for javascript which contains `${0:result}`.

Other snippets I've tested which contains `${0:something}` doesn't trigger the issue, like `ct`, `/**` and `jsonp` for javascript and `"` for python. I've not experienced the issue with snippets that I've tested which contains more than one placeholder either, like `fun` and `let` for javascript and `cl` for python.

All of the mentioned snippets are from `honza/vim-snippets`. When using the completion menu to expand the snippet, the issue doesn't occur.

## Steps to reproduce

1. Create `mini.vim`:
```
set nocompatible
set runtimepath^=~/.vim/plugged/coc.nvim
set runtimepath^=~/.vim/plugged/vim-snippets
filetype plugin indent on
syntax on
set hidden
imap <C-l> <Plug>(coc-snippets-expand)
```
2. Run `vim -u mini.vim test.js`
3. Type `cl`
4. Press Ctrl-L

## CocInfo

```
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul  2 2019 20:06:04)
node version: v11.15.0
coc.nvim version: 0.0.72-4aee0cab77
term: dumb
platform: linux

## Messages
Messages maintainer: Bram Moolenaar <Bram@vim.org>
1 change; before #2  0 seconds ago
1 line less; before #1  2 seconds ago
Already at oldest change
## Output channel: snippets
```

**Comment by chemzqm** [comment]
Fixed on master of coc.nvim.

**Comment by trygveaa** [comment]
Thanks!
