### ISSUE TITLE
some UltiSnip go snippet expand error

### ISSUE THREAD

**Issue by fannheyward** [neoclide/coc-snippets#4]
```
Plug 'honza/vim-snippets'

imap <C-l> <Plug>(coc-snippets-expand)
```

Open `main.go`, input any snippet prefix, for example `func` or `if`, then `C-l` to expands:

```
func name(params)typetype {
         |
}
```

there is two `type`s.

```
if conditioncondition{
         |
}
```

there is two `condition`s. `C-j` jumps to `type`, only first part will be selected.

<img width="133" alt="1" src="https://user-images.githubusercontent.com/345274/51781816-2e0e3600-2159-11e9-9b3e-2fa922fd8221.png">

**Comment by chemzqm** [comment]
It's fixed on master of coc.nvim

**Comment by fannheyward** [comment]
The indentation error is fixed with `autocmd FileType go setlocal expandtab`.
