### ISSUE TITLE
conflict when i use php $var 

### ISSUE THREAD

**Issue by MaxJohnXiang** [neoclide/coc-snippets#40]
This is my snippets
```
snippet ifuca "Desc" b
     <?php if (Yii::$app->user->can('${1:string}')): ?>

     <?php endif; ?>
endsnippet

```

---------------------------------- output like this 

```
 <?php if (Yii::->user->can('string')): ?>

  <?php endif; ?>


```the result lose $app variable

**Comment by MaxJohnXiang** [comment]
i'm migrate from utilsnipeets,  this snippets work on Ultisnippets well,  But it doesn't work on coc-snippets

**Comment by chemzqm** [comment]
The ultisnips definition is confusing, you should excapse `$` with `\`

**Comment by chemzqm** [comment]
Fixed
