### ISSUE TITLE
coc-snippets not loading some vscode snippets

### ISSUE THREAD

**Issue by hamza0867** [neoclide/coc-snippets#41]
Hi,
I just installed [this angularjs snippets extension](https://github.com/johnpapa/vscode-angular1-snippets) using :CocInstall https://github.com/johnpapa/vscode-angular1-snippets.

While it does indeed show in the :CocList extensions, it is not loading snippets from the extension. 

I encountered this same issue with other vscode snippet extensions as well.

Can You please help me figure out what's the root of this issue and how to fix it ??

Thank you very much

**Comment by chemzqm** [comment]
Looks like you have disabled this feature

**Comment by hamza0867** [comment]
What do you mean by "disabled this feature" ??

I have other vscode snippets extensions working perfectly like [this one](https://github.com/dsznajder/vscode-es7-javascript-react-snippets)

I was thinking maybe the angularjs extension had a problem but it is working perfectly in vscode
Maybe there is some configuration needed somewhere ??

**Comment by chemzqm** [comment]
It works as expected for me, maybe you're using version of coc-snippets

**Comment by hamza0867** [comment]
How do I update coc-snippets please ??

And is it possible that an old version of coc-snippets would load some extension properly but not another one ?? 

Did you try installing the extension I mentioned but it still works perfectly ??

Thank you and sorry taking much of your time.

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions

> Did you try installing the extension I mentioned but it still works perfectly ??

Yes.

**Comment by chemzqm** [comment]
Updated faq https://github.com/neoclide/coc-snippets#faq
