### ISSUE TITLE
How can I stop snippets activating within snippets?

### ISSUE THREAD

**Issue by stevenhay** [neoclide/coc-snippets#42]
For example, I'm trying to use the 'meth' snippet in Golang which expands to

```go
func (receiver type) name(params) type {

}
```

When I'm trying to change the receiver placeholder to, say, 's'. When I press tab, it expands to sha256 and imports sha256 instead of moving to the next placeholder.

![output](https://user-images.githubusercontent.com/26744309/61200712-47d91080-a6da-11e9-9522-f18d62787de8.gif)

How can I stop this from happening? Thank you.

**Comment by chemzqm** [comment]
Use `<C-n>` to insert next complete item without auto import.
If you just want jump, use another keymap for jump to next placeholder, or not map `<tab>` like:
```
inoremap <silent><expr> <TAB>
      \ pumvisible() ? coc#_select_confirm() :
      \ coc#expandableOrJumpable() ? "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand-jump',''])\<CR>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
```
