### ISSUE TITLE
Wrongfully triggering snippet expand

### ISSUE THREAD

**Issue by sQVe** [neoclide/coc-snippets#43]
I noticed today that some of my snippets where triggered even though I didn't manually expand them. It seems to happens if I try to go the the "next item" very quickly, before or at the same time as the completion menu appears.

I've recorded this gif demonstrating it (The last snippet expand is happening by itself): 
![Peek 2019-07-17 22-43](https://user-images.githubusercontent.com/2284724/61411771-57797480-a8e7-11e9-8a80-269dfd78d15d.gif)

I'm unsure on when this was introduced as I'm currently on my summer vacation and do not code as much as I usually do.

**Comment by chemzqm** [comment]
It could happen when your completeopt doesn't have `menuone` and preselect is enabled.
Try add `"suggest.enablePreselect": false` in your `coc-settings.json`

**Comment by sQVe** [comment]
@chemzqm Setting `"suggest.enablePreselect"` to `false` does not solve the issue for me though.

**Comment by chemzqm** [comment]
Does `"snippets.autoTrigger": false` helps?

**Comment by sQVe** [comment]
@chemzqm No. Still same issue with `"snippets.autoTrigger": false`.

**Comment by chemzqm** [comment]
No idea then, don't know why confirm completion is triggered.

**Comment by sQVe** [comment]
@chemzqm Can I provide any more information or debug this in anyway to help out? It's a pretty annoying bug :(

**Comment by chemzqm** [comment]
Need the detail way to reproduce.

**Comment by sQVe** [comment]
@chemzqm Roger! Really late here now but I'll try to provide that to you tomorrow.

**Comment by sQVe** [comment]
@chemzqm I've been able to debug for a bit more now. I'm getting the issue as soon as I have `coc-snippets` and `coc-tsserver` installed. I downgraded `coc-tsserver` incrementally to see when the issue was introduced and I'm seeing it from version `1.2.1` and above. `coc-tsserver@1.2.0` and below works fine.

I'm using the following snippets: https://github.com/sQVe/dotfiles/tree/kodama/config/coc/ultisnips
I'm able to reproduce the issue by writing `con` and then `<Tab>` straight away before the completion menu appears. I'm getting the bug around every 6th try maybe.

**Comment by chemzqm** [comment]
@sQVe What's your keymap for `<Tab>`

**Comment by sQVe** [comment]
@chemzqm The default from the README.

```vim
" Use <Tab> to move to next completion item.
inoremap <silent><expr> <Tab>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<Tab>" :
      \ coc#refresh()
inoremap <expr><S-Tab> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1

  return !col || getline('.')[col - 1]  =~# '\s'
endfunction
```

**Comment by chemzqm** [comment]
@sQVe Whats from `:verbose imap <tab>`?

**Comment by chemzqm** [comment]
Can you try it with minimal vimrc?

**Comment by sQVe** [comment]
@chemzqm I can replicate it with only:

```vim
call plug#begin('$HOME/.local/share/nvim/plugged')

Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}

call plug#end()
```

and an empty CocConfig, using `<C-n>` :disappointed:

**Comment by chemzqm** [comment]
Try latest release of coc.nvim.

**Comment by sQVe** [comment]
@chemzqm Still the same. :cry:

**Comment by chemzqm** [comment]
Please paste `:CocInfo` and result of `:verbose imap <tab>`

**Comment by sQVe** [comment]
```vim
## versions

vim version: NVIM v0.4.0-1337-ga04e0c8db
node version: v10.16.0
coc.nvim version: 0.0.73
term: alacritty
platform: linux

## Messages

## Output channel: snippets
```

```
i  <Tab>       * pumvisible() ? "\<C-N>" : <SNR>18_check_back_space() ? "\<Tab>" : coc#refresh()
        Last set from ~/.config/nvim/keymap.vim
```

**Comment by chemzqm** [comment]
I have no idea, can you reproduce it by remap `<tab>` like 
```
  inoremap <silent><expr> <TAB>
        \ pumvisible() ? "\<C-n>" :
        \ "\<TAB>"
```

**Comment by sQVe** [comment]
@chemzqm Yes. I can even replicate it with regular `<C-n>` like I mentioned above.

**Comment by chemzqm** [comment]
Bug of vim, fixed on master of coc.nvim.

**Comment by sQVe** [comment]
@chemzqm Indeed fixed with latest `coc.nvim` :pray:. Thank you for all the awesome work you put into `coc`.
