### ISSUE TITLE
Add command/function for anonymous snippets

### ISSUE THREAD

**Issue by idanarye** [neoclide/coc-snippets#44]
An anonymous snippet (like in Ultisnips) is a snippet that is looked up in a file, but instead passed to the command as an argument. This will allow other plugins to generate the snippet at runtime and use coc-snippets as the frontend for filling it.

**Comment by chemzqm** [comment]
There is a internal CocCommand for this purpose, it's used by coc-snippets:  https://github.com/neoclide/coc.nvim/blob/master/src/commands.ts#L56

It can be called in vim by `:call CocAction('runCommand', 'editor.action.insertSnippet', edit)`

**Comment by chemzqm** [comment]
Use `strchars(strpart(getline('.'), 0, col('.')-1))` for `character` index.
