### ISSUE TITLE
after coc#_select_confirm(), have to wait ready, then input?

### ISSUE THREAD

**Issue by hyaray** [neoclide/coc-snippets#46]
after coc#_select_confirm(), press **`abcde`** immediately, there are kinds  of unexpected results as picture below。
snippets：
`
snippet this "this.a := a"
this.$1 := $1
endsnippet
`

![20190720115356](https://user-images.githubusercontent.com/10717703/61573692-84937600-aae5-11e9-882f-0b9443069557.jpg)

**Comment by chemzqm** [comment]
You have to wait the snippets ready, if it's slow, profile your vim.
