### ISSUE TITLE
Expanding snippets

### ISSUE THREAD

**Issue by mikeTWC1984** [neoclide/coc-snippets#47]
I'm trying to set some key mapping to expand all available snippets for current file language.
Pretty much what the readme file suggest:
```imap <C-l> <Plug>(coc-snippets-expand)```
The problem with this is that it's only working if cursor is next to some letter. If it's following space or new line nothing will happen until you start typing. Is there any way to tweak this to show all available snippets even if cursor is at the beginning of new line?

**Comment by chemzqm** [comment]
No, use snippets list
