### ISSUE TITLE
Repeat snippet expansion with dot command

### ISSUE THREAD

**Issue by anhari** [neoclide/coc-snippets#49]
When trying to repeat a snippet expansion using the `.` command, the repeated command will input the snippet trigger in place of its expanded content.

**Comment by chemzqm** [comment]
What do you mean by repeat snippet expansion.

**Comment by anhari** [comment]
Say you have the following snippet:

```
snippet .. "class" w
class="${0}"
endsnippet
```

![2019-07-30 12 26 43](https://user-images.githubusercontent.com/6628875/62147449-84edf700-b2c5-11e9-9280-8ce41c9bccf2.gif)

**Comment by chemzqm** [comment]
It doesn't have support for repeat.
