### ISSUE TITLE
How can I use tab to expand snippets and to jump to next placeholder?

### ISSUE THREAD

**Issue by purpleP** [neoclide/coc-snippets#5]
I've been able configure ultisnips to use tab to both expanding the snippet and jumping to next placeholder (`s-tab` to jump to previous).

Is this possible with your plugin?

**Comment by Avi-D-coder** [comment]
Yes, but only if tab is not used for completion, or you Just use `coc-snippets` without `coc-ultisnips`.

```
" To make completion works like VSCode
inoremap <expr> <TAB> pumvisible() ? "\<C-y>" : "\<TAB>"
let g:coc_snippet_next = '<TAB>'
let g:coc_snippet_prev = '<S-TAB>'
```

**Comment by Avi-D-coder** [comment]
If you want full `ultisnips` support you need a config like this:
```
let g:UltiSnipsExpandTrigger='<Nop>'
let g:UltiSnipsJumpForwardTrigger = '<TAB>'
let g:UltiSnipsJumpBackwardTrigger = '<S-TAB>'
let g:coc_snippet_next = '<TAB>'
let g:coc_snippet_prev = '<S-TAB>'
```

Tab cannot be used by both ultisnips and Coc to for everything at the same time. If you are using full `ultisnips` via `coc-ultisnips` with `honza/vim-snippets` you may not even need `coc-snippets`

**Comment by purpleP** [comment]
@Avi-D-coder Yes, I mean I use tab both for autocomplete and snippets. Is this possible with coc?

**Comment by Avi-D-coder** [comment]
@purpleP As far as I can tell it is only possible if you only use `coc-snippets` not `coc-ultisnips`. If you use ultisnips and coc it is not possible.

**Comment by purpleP** [comment]
@Avi-D-coder Well okay, how do I do this with coc-snippets?

**Comment by Avi-D-coder** [comment]
@purpleP you can use:

```
" To make completion works like VSCode
inoremap <expr> <TAB> pumvisible() ? "\<C-y>" : "\<TAB>"
let g:coc_snippet_next = '<TAB>'
let g:coc_snippet_prev = '<S-TAB>'
```

The problem is coc-snippets only implements some of  ultisnips features, and does not support snipmate snippets.

**Comment by chemzqm** [comment]
```
imap <tab> <Plug>(coc-snippets-expand)
let g:coc_snippet_next = '<TAB>'
```
Jump snippet only work when snippet is activated.  You also need to disable Ultisnippet from mapping `<tab>`.


>  I mean I use tab both for autocomplete and snippets. 

How could that work? What do you want `<tab>` to do when pum is not visible (trigger completion or expand snippet)?

**Comment by purpleP** [comment]
@chemzqm 
Your plugin shows pum even when there's a single letter have been input? It also shows snippets in pum, right? So there couldn't be a situation where you don't have pum but there exists a snippet bounded to particular combinations of letters.

It works fine. https://www.youtube.com/watch?v=WeppptWfV-0

**Comment by chemzqm** [comment]
> So there couldn't be a situation where you don't have pum but there exists a snippet bounded to particular combinations of letters.

Sometimes the snippet won't shown in the pum, ex: use `>` as trigger.
For short trigger like `if`, you will have to select it before expand, it would be faster if you just trigger expand.

**Comment by purpleP** [comment]
@chemzqm Well, that's why I'm almost always use single letter snippets or snippets that should come up before autocmpletion items. Like `try` for `try except`

**Comment by purpleP** [comment]
@chemzqm Okay, using `<TAB>` to select next completion item isn't working if I use it for snippet expansion. I this gonna be fixed or not?

**Comment by chemzqm** [comment]
> using <TAB> to select next completion item isn't working if I use it for snippet expansion. 

It's feature, you need condition imap for this case:
```
  inoremap <expr> <TAB> pumvisible() ? "\<C-n>" : coc#rpc#request('doKeymap', 'snippets-expand')
```

**Comment by purpleP** [comment]
@chemzqm You  

> > using  to select next completion item isn't working if I use it for snippet expansion.
> 
> It's feature, you need condition imap for this case:
> 
> ```viml
>   inoremap <silent><expr> <TAB>
>         \ pumvisible() ? "\<C-n>" :
>         \ <SID>check_back_space() ? "\<TAB>" :
>         \ coc#rpc#request('doKeymap', 'snippets-expand')
> 
> function! s:check_back_space() abort
>   let col = col('.') - 1
>   return !col || getline('.')[col - 1]  =~# '\s'
> endfunction
> ```

Thanks for you help, but this isn't working. If pum is visible it also needs to check whether or not currently typed letters are valid snippet it needs to expand it. Unfortunately I don't know the API to check whether current pum element.

In case you find this behaviour strange it's how deoplete, youcompleteme and ultisnips always worked when I them with supertab. After watching greg's video I also made `tab` to be the key to jump to next placeholder, but you've already showed how to achieve that.

**Comment by chemzqm** [comment]
>  If pum is visible it also needs to check whether or not currently typed letters are valid snippet it needs to expand it. 

You didn't mention that, it's not supported yet.

**Comment by purpleP** [comment]
@chemzqm 

That's what I meant in that [comment](https://github.com/neoclide/coc-snippets/issues/5#issuecomment-458007173) and you're probably very busy, but that's how it works in a video I gave link to.

Sorry I wasn't clear enough. To summarize. I'd like to use `<TAB>/<S-TAB>` as next/previous autocomplete item, expand snippet and jump to next/previous placeholder.

**Comment by chemzqm** [comment]
It's priority problem

**Comment by RobertBrunhage** [comment]
I had to do all of this to get it working, am I missing something, or is this correct?

```
let g:UltiSnipsExpandTrigger = '<Nop>'
"" Use <C-l> for trigger snippet expand.
imap <tab> <Plug>(coc-snippets-expand)
inoremap <silent><expr> <TAB>
	  \ pumvisible() ? coc#_select_confirm() :
      \ coc#expandableOrJumpable() ? "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand-jump',''])\<CR>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

let g:coc_snippet_next = '<tab>'
let g:coc_snippet_prev = '<s-tab>'
```

**Comment by CoderCowMoo** [comment]
Hey there's a solution here that worked for me.
https://github.com/neoclide/coc.nvim/issues/606#issuecomment-499095217

**Comment by therealmaxmoon** [comment]
> " To make completion works like VSCode
> inoremap <expr> <TAB> pumvisible() ? "\<C-y>" : "\<TAB>"
> let g:coc_snippet_next = '<TAB>'
> let g:coc_snippet_prev = '<S-TAB>'

Jumping to the next placeholder NEVER worked for me, even if I configured nvim from scratch. I watched youtube vids and read block articles for hours a day. No one explains how to do this!

But with this key bindings and the coc-snippet installed, it finally works.

What a relief! Thank you so much! @Avi-D-coder
