### ISSUE TITLE
coc-snippets delete one more line when using visual replacement

### ISSUE THREAD

**Issue by vimers** [neoclide/coc-snippets#51]
![ezgif-4-f8364e00f603](https://user-images.githubusercontent.com/16351989/62831019-2e7ca300-bc4b-11e9-8d15-b33f9d4c181d.gif)

It works well when delete 1 line.
But when select 2 or more lines, it replace N+1 lines

**Comment by chemzqm** [comment]
Please provide minimal vimrc, and result of `:echo eval('[&virtualedit, &selection]')`

**Comment by vimers** [comment]
```vim
imap <C-l> <Plug>(coc-snippets-expand)    
vmap <C-j> <Plug>(coc-snippets-select)                  
let g:coc_snippet_next = '<c-j>'   
let g:coc_snippet_prev = '<c-k>'  
imap <C-j> <Plug>(coc-snippets-expand-jump)
```

```shell
:echo eval('[&virtualedit, &selection]')
['', 'inclusive']
```

**Comment by vimers** [comment]
@chemzqm 
`set virtualedit=all` can solve the problem. thanks

**Comment by vimers** [comment]
@chemzqm 
I found the line `return 0;` duplicated after trigger snippet-expand when I use `virtualedit=all`.

**Comment by chemzqm** [comment]
Need minimal vimrc

**Comment by vimers** [comment]
vimrc setting:
<https://github.com/vimers/vimrc>

**Comment by chemzqm** [comment]
Minimal vimrc, I don't have time to install your plugins
