### ISSUE TITLE
fi expands with wrong set of ERB brackets 

### ISSUE THREAD

**Issue by kroyagis** [neoclide/coc-snippets#52]
in `.erb` file, `fi` expands to `%>Fixtures.identify(:) %>`

Also, other eruby Snippets such as `%` and `=` is not being shown in the list as well.

**Comment by chemzqm** [comment]
It's expected,they're not keywords

**Comment by kroyagis** [comment]
@chemzqm could you elaborate? Shouldn't it expand to
```
<% ... %>
```
instead of
```
%> ... %>
```

**Comment by chemzqm** [comment]
I don't have that snippet
