### ISSUE TITLE
Snippets are surrounded with 0

### ISSUE THREAD

**Issue by lightxue** [neoclide/coc-snippets#56]
Here is my config about snippets.

```vim
Plug 'honza/vim-snippets' " vim-plug

" Use <C-l> for trigger snippet expand.
imap <C-l> <Plug>(coc-snippets-expand)

" Use <C-j> for select text for visual placeholder of snippet.
vmap <C-j> <Plug>(coc-snippets-select)

" Use <C-j> for jump to next placeholder, it's default of coc.nvim
let g:coc_snippet_next = '<c-j>'

" Use <C-k> for jump to previous placeholder, it's default of coc.nvim
let g:coc_snippet_prev = '<c-k>'

" Use <C-j> for both expand and jump (make expand higher priority.)
imap <C-j> <Plug>(coc-snippets-expand-jump)

```

I got 2 problems.

1. Some snippets are surrounded with `0`.

![image](https://user-images.githubusercontent.com/4833740/64068905-d77a5480-cc71-11e9-9b7b-cd07a9aedf31.png)

![image](https://user-images.githubusercontent.com/4833740/64068916-f8db4080-cc71-11e9-888a-a0d56109d8b5.png)

2. Both `vim-snippets/snippets` and `vim-snippets/UltiSnips` are loaded, but I need `vim-snippets/UltiSnips` only. 

![image](https://user-images.githubusercontent.com/4833740/64068928-232cfe00-cc72-11e9-98e9-8e989250b42c.png)

Thanks for the great extension.

**Comment by chemzqm** [comment]
1. No idea, can't reproduce.
2. You have to didable snipmate snippet

**Comment by wenpengy** [comment]
> 
> 
> Here is my config about snippets.
> 
> ```viml
> Plug 'honza/vim-snippets' " vim-plug
> 
> " Use <C-l> for trigger snippet expand.
> imap <C-l> <Plug>(coc-snippets-expand)
> 
> " Use <C-j> for select text for visual placeholder of snippet.
> vmap <C-j> <Plug>(coc-snippets-select)
> 
> " Use <C-j> for jump to next placeholder, it's default of coc.nvim
> let g:coc_snippet_next = '<c-j>'
> 
> " Use <C-k> for jump to previous placeholder, it's default of coc.nvim
> let g:coc_snippet_prev = '<c-k>'
> 
> " Use <C-j> for both expand and jump (make expand higher priority.)
> imap <C-j> <Plug>(coc-snippets-expand-jump)
> ```
> 
> I got 2 problems.
> 
>     1. Some snippets are surrounded with `0`.
> 
> 
> ![image](https://user-images.githubusercontent.com/4833740/64068905-d77a5480-cc71-11e9-9b7b-cd07a9aedf31.png)
> 
> ![image](https://user-images.githubusercontent.com/4833740/64068916-f8db4080-cc71-11e9-888a-a0d56109d8b5.png)
> 
>     1. Both `vim-snippets/snippets` and `vim-snippets/UltiSnips` are loaded, but I need `vim-snippets/UltiSnips` only.
> 
> 
> ![image](https://user-images.githubusercontent.com/4833740/64068928-232cfe00-cc72-11e9-98e9-8e989250b42c.png)
> 
> Thanks for the great extension.

I met the same problems with you, have you find the reason and fix it?

**Comment by chemzqm** [comment]
Could be problem with your python, I guess.
