### ISSUE TITLE
"Convert to snippet" action appears alongside quickfixes

### ISSUE THREAD

**Issue by JeanMertz** [neoclide/coc-snippets#58]
If I do `:CocAction quickfixes`, I get the available quickfixes (indicated with `(quickfixes)` after them in the list). However, I also get a line stating `Convert to snippet [snippets]`. That seems unexpected and incorrect.

**Comment by fannheyward** [comment]
`Convert to snippet` is a default codeAction available in every document.

**Comment by JeanMertz** [comment]
> available in every document

You mean in every list, I suppose?

It's a bit strange to inject it all lists, even if they aren't related to anything to do with converting something to a snippet, though?

If I open the "quickfixes" list, I suspect to see quickfixes provided by LSP's. Or is it because converting to snippets is _also_ considered a "quickfix", which makes it show up?

I've disabled the plugin for now, I wasn't using it too much, and rather nog have it show up in those lists, so feel free to close this issue if it is working as intended 👍.

**Comment by chemzqm** [comment]
It should not be shown in quickfix list.

**Comment by chemzqm** [comment]
You have to use `CocAction quickfix`
