### ISSUE TITLE
Language specific from honza/vim-snippets not loaded

### ISSUE THREAD

**Issue by olalonde** [neoclide/coc-snippets#59]
As recommended, I installed `honza/vim-snippets` but it seems only global snippets are getting recommended. For example, when I type `:CocList snippets` in a javascript file, I only see following snippets:

```
c)
todo
modeline
..etc...
AGPL
ISC
```

**Comment by chemzqm** [comment]
You have to make sure `snippets.ultisnips.directories` configuration contains `UltiSnips`.

**Comment by olalonde** [comment]
Actually I fixed the issue by adding this to my `:CocConfig`: 

```json
{
  "snippets.extends": {
    "javascriptreact": ["javascript"],
    "typescriptreact": ["javascript"],
    "typescript": ["javascript"]
  }
}
```

**Comment by bushblade** [comment]
I'm having much the same issue, the only snippets that show for me with `:CocList snippets`
are.
```
  bbox                 A nice box over the full width ~/.config/nvim/plugged/vim-snippets/UltiSnips/all.snippets
  box                  A nice box with the current comment symbol ~/.config/nvim/plugged/vim-snippets/UltiSnips/all.snippets
  datetime             YYYY-MM-DD hh:mm ~/.config/nvim/plugged/vim-snippets/UltiSnips/all.snippets
  datetime              ~/.config/nvim/plugged/vim-snippets/snippets/_.snippets
  date                 YYYY-MM-DD ~/.config/nvim/plugged/vim-snippets/UltiSnips/all.snippets
  date                  ~/.config/nvim/plugged/vim-snippets/snippets/_.snippets
  lorem                Lorem Ipsum ~/.config/nvim/plugged/vim-snippets/UltiSnips/all.snippets
  lorem                 ~/.config/nvim/plugged/vim-snippets/snippets/_.snippets
  fold                 Insert a vim fold marker ~/.config/nvim/plugged/vim-snippets/UltiSnips/all.snippets
  foldc                Insert a vim fold close marker ~/.config/nvim/plugged/vim-snippets/UltiSnips/all.snippets
 ```

**Comment by chemzqm** [comment]
Make sure your filetype is expected.

**Comment by bushblade** [comment]
Thanks for the reply @chemzqm 
How would I do that?
I have also tried adding in 
```
 "snippets.extends": {
    "javascriptreact": ["javascript"],
    "typescriptreact": ["javascript"],
    "typescript": ["javascript"]
  }
```
As per @olalonde 's solution but still no luck.

**Comment by bushblade** [comment]
@chemzqm Can you explain what you mean by Make sure your filetype is expected. please?
I still can't get this to work.

**Comment by chemzqm** [comment]
`:echo &filetype` to check filetype of current buffer.

**Comment by powelleric** [comment]
> `:echo &filetype` to check filetype of current buffer.

Just a quick note that if this returns `javascript.jsx` that this will not work in your settings.  Instead use `javascriptreact`, as shown above.
