### ISSUE TITLE
New releases should be kept in sync with coc.nvim

### ISSUE THREAD

**Issue by nifoc** [neoclide/coc-snippets#6]
The currently released version of `coc-snippets` (1.0.5) does not work with the currently released version of `coc.nvim` (0.0.49). On startup, `coc-snippets` generates the following error:

```
[coc.nvim] Error on active extension coc-snippets: coc_nvim_1.workspace.createMru is not function
```

This seems to be because `createMru` was only added after 0.0.49 was released (https://github.com/neoclide/coc.nvim/commit/0ec7054d008411b5f1e55f804f56b3e420f73d4f).

Would it be possible to keep things in sync with released versions of `coc.nvim` in the future?

**Comment by chemzqm** [comment]
It's impossible unless we have auomation test .  But I don't have time for that.
Will be more carefull with new extension release.
