### ISSUE TITLE
Neovim puts spellfiles in wrong place

### ISSUE THREAD

**Issue by Avi-D-coder** [neoclide/coc-snippets#64]
With coc-snippets installed Neovim places spell files like so: `~/.config/coc/extensions/node_modules/coc-snippets/spell/en.utf-8.add`.

Can anyone else reproduce this problem? 
Type <kbd>z+g</kbd> to add a word to your `spellfile` and read the echo msg.

vim version: NVIM v0.5.0-91-g9af0fe529
node version: v12.11.1
coc.nvim version: 0.0.74
term: xterm-256color
platform: linux

**Comment by chemzqm** [comment]
Can't reproduce

**Comment by jclds139** [comment]
It's because coc-snippets is inserting `~/.config/coc/extensions/node_modules/coc-snippets/` as the first entry in `runtimepath`. Same thing happens in normal `vim`. If you can place what you're adding to the `runtimepath` at the end instead of the beginning this won't happen.
