### ISSUE TITLE
UltiSnips of coc-snippets with python script unexpected on nvim and vim

### ISSUE THREAD

**Issue by griffinqiu** [neoclide/coc-snippets#66]
``` snippet

global !p
def textmate_var(var, snip):
	snip.rv = var
endglobal


snippet % "<% $0 %>" i
`!p textmate_var('1', snip)` $0 `!p textmate_var('2', snip)`
`!p textmate_var('3', snip)` $1 `!p textmate_var('4', snip)`
endsnippet
```

vim + SirVer/ultisnips:

1 _ 2
3 4

nvim + SirVer/ultisnips:

1 _ 2
3 4

vim + neoclide/coc-snippets:

1 2
3 _ 4

nvim + neoclide/coc-snippets:

  2  3
  4 _  4

Issue:
1. The Cursor position is wrong place in the both of vim and nvim of coc-snippets.
2. The value is chaos in nvim coc-snippets.

**Comment by chemzqm** [comment]
> The Cursor position is wrong place in the both of vim and nvim of coc-snippets.

It's expected because we consider `$0` as last placeholder, so cursor is placed at `$1`

> The value is chaos in nvim coc-snippets.

Can't reproduce.
