### ISSUE TITLE
UltiSnips snippets won't load on Windows 10 + neovim

### ISSUE THREAD

**Issue by cf91** [neoclide/coc-snippets#70]
Have settings like this with `Plug 'honza/vim-snippets` installed.

```
  "snippets.priority": 100,
  "snippets.shortcut": "S",
  "snippets.autoTrigger": false,
  "snippets.triggerCharacters": [],
  "snippets.loadFromExtensions": false,
  "snippets.ultisnips.enable": true,
  "snippets.ultisnips.usePythonx": false,
  "snippets.snipmate.enable": false,
```

If I try to expand any honza snippet (I can see them suggested in completion) it fails silently. If I run `:CocCommand workspace.showOutput snippets` I see:

```
[Error 12:17:31 PM]: request error nvim_command - Vim(return):Error invoking 'python_execute' on channel 7 (python3-script-host):
  File "<string>", line 4
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
code: import re, os, vim, string, random
t = ('', 'function_name','argument')
fn = 'test.js'
path = 'C:\Users\xxx\Desktop\tmp\test.js'
context = {}
snip = SnippetUtil('', (1,0), (1,1), context)
```

Seems like it could be a path escape problem on Windows.

Thanks.

**Comment by chemzqm** [comment]
It's error of your python code.

**Comment by cf91** [comment]
Hmm, my neovim healthcheck for python3 is OK, and I have not touched any python otherwise. Something is using Windows path without escaping properly, and I'm only having problems with coc-snippets. 

Thanks for your awesome work by the way.
