### ISSUE TITLE
Ultisnips visual placeholder not working properly

### ISSUE THREAD

**Issue by milisims** [neoclide/coc-snippets#71]
Minimal vimrc:
``` vim
imap <C-y> <Plug>(coc-snippets-expand)
xmap <Tab> <Plug>(coc-snippets-select)
```
nvim version: v0.4.2
Only coc-nvim is installed (in packpath) with coc-snippets extension, and this snippet:
``` snippet
snippet fun "function" b
function! ${1:function_name}($2) abort " {{{1
	${0:${VISUAL:return}}
endfunction
endsnippet
```
Selecting a single line and pressing `<Tab>` then expanding the snippet works as expected.
Selecting two or more lines and pressing `<Tab>` then expanding the snippet does weird things with indentation.
Selecting nothing and expanding the snippet gives no default value, expected `return`.

If we change the `${0:${VISUAL:return}}` line to `${VISUAL:return}`, there is still no default, and if we finally change it to `${VISUAL}`, the indenting works properly, but there is no default and there is no ability to jump to the snippet location

**Comment by matthsims** [comment]
I started nvim with `--noplugins +packadd coc.nvim`, here are my scriptnames.
```
  1: /etc/xdg/nvim/sysinit.vim
  2: /usr/share/nvim/archlinux.vim
  3: ~/.config/nvim/init.vim
  4: /usr/share/nvim/runtime/filetype.vim
  5: /usr/share/vim/vimfiles/ftdetect/PKGBUILD.vim
  6: /usr/share/vim/vimfiles/ftdetect/augeas.vim
  7: /usr/share/nvim/runtime/ftplugin.vim
  8: /usr/share/nvim/runtime/indent.vim
  9: /usr/share/nvim/runtime/syntax/syntax.vim
 10: /usr/share/nvim/runtime/syntax/synload.vim
 11: /usr/share/nvim/runtime/syntax/syncolor.vim
 12: /usr/share/nvim/runtime/ftplugin/vim.vim
 13: /usr/share/nvim/runtime/indent/vim.vim
 14: /usr/share/nvim/runtime/syntax/vim.vim
 15: /usr/share/nvim/runtime/syntax/vim/generated.vim
 16: ~/.config/nvim/pack/a/start/coc.nvim/plugin/coc.vim
 17: ~/.config/nvim/pack/a/start/coc.nvim/autoload/coc/rpc.vim
 18: ~/.config/nvim/pack/a/start/coc.nvim/autoload/coc/util.vim
 19: ~/.config/nvim/pack/a/start/coc.nvim/autoload/coc/client.vim
 20: ~/.config/nvim/pack/a/start/coc.nvim/autoload/coc.vim
 21: /usr/share/nvim/runtime/autoload/provider/python3.vim
 22: /usr/share/nvim/runtime/autoload/provider/pythonx.vim
 23: /usr/share/nvim/runtime/autoload/remote/host.vim
 24: /usr/share/nvim/runtime/autoload/provider.vim
 25: /tmp/coc-114385.vim
 26: /usr/share/nvim/runtime/autoload/provider/clipboard.vim
 27: ~/.config/nvim/pack/a/start/coc.nvim/autoload/coc/snippet.vim
```

And the problem persists. The contents of `sysinit.vim` are source the archlinux.vim file, and all that does is `set rtp+=/usr/share/vim/vimfiles`. Everything else is standard stuff.

Do you have any recommendations for how I could continue investigating?

**Comment by chemzqm** [comment]
You can debug coc.nvim in chrome https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim

**Comment by wnyao** [comment]
HI, I am having some issue with the VISUAL placeholder as well. Here is my discovery:

Ultisnips and YouCompleteMe has the VISUAL placeholder working fine and as expected. However not so with coc-snippets. I am unsure whether it is the problem from ```$TM_SELECTED_TEXT``` although i try in looking at the source.

**nvim v0.4.3**

**Comment by coaxial** [comment]
I have the same issue, `${VISUAL}` seems to have no effect in snippets when using `coc-ultisnips`.

**Comment by filipmacek** [comment]
Same problem here, any solutions?

**Comment by coaxial** [comment]
> Same problem here, any solutions?

Couldn’t find any so I switched to you complete me + ultisnips + supertabs.

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
