### ISSUE TITLE
Auto Import Issue

### ISSUE THREAD

**Issue by ovidius72** [neoclide/coc-snippets#72]
In a typescript file, with auto import enalbled, auto completing a word that perform an auto import the snippets stops . You cannot step in into other tab stops and placehoders are not updated.
Is this the default behaviour or maybe there is something wrong with my configuration ? 
Thanks.

**Comment by chemzqm** [comment]
Can't reproduce.

**Comment by ovidius72** [comment]
This is a quick example.
![vim-snippets2](https://user-images.githubusercontent.com/3592928/71762825-d9307f00-2ed4-11ea-95af-349cf4e18913.gif)
The first time I select the item(membershipRoles) from the list just hitting Ctrl-J but it's not auto imported and it keeps working fine. 
The second time I press Return on the item so that the membersipRoles variable is auto imported but the snippets stops working. Clicking Ctrl-J or Ctrl-K to go to the next placeholder doesn´t work.

**Comment by chemzqm** [comment]
Fixed on coc.nvim.
