### ISSUE TITLE
Snippet preview does't close with <C-c>

### ISSUE THREAD

**Issue by amerov** [neoclide/coc-snippets#76]
![Peek 2019-11-30 11-14](https://user-images.githubusercontent.com/196747/69897064-2a929f00-1368-11ea-8c50-30563d15a4e9.gif)
vimrc:
```viml
call plug#begin('~/.local/share/nvim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'honza/vim-snippets'
call plug#end()
filetype indent on
filetype plugin on
```

**Comment by davidosomething** [comment]
vim tip: `<c-c>` is not a replacement for `<esc>` -- it doesn't trigger autocmds
use `<c-[>`

**Comment by chemzqm** [comment]
Can't fix, vim doesn't send autocmds when you hit `<C-c>`
