### ISSUE TITLE
Help troubleshooting issue: snippets starting with [ or < do not trigger the popup menu

### ISSUE THREAD

**Issue by jeromg** [neoclide/coc-snippets#79]
Hi there,

In Neovim 0.4.2, I installed coc-snippets with honza/vim-snippets. It works really well except in the following scenario:
- create a new blank **markdown** file
- some snippets work fine, e.g. "date", "blockquote", "youtube"
- but nothing happens for all **snippets starting with special chars** like "[" or "<" (i.e. no popup menu is triggered)

CocInfo: 
```
## versions

vim version: NVIM v0.4.2
node version: v13.2.0
coc.nvim version: 0.0.74-d83536aa4e
term: dumb
platform: win32
```

I've tried to eliminate any interference from other plugins or other settings to no avail.

Any idea or suggestion on how to troubleshoot this issue is warmly welcome.

Thanks in advance.

Cheers  /jerome

**Comment by chemzqm** [comment]
Configure `snippets.triggerCharacters`, on manual trigger completion.

**Comment by fannheyward** [comment]
@chemzqm Don't know if I understood correctly, looks like it's not `triggerCharacters` issue, but https://github.com/neoclide/coc.nvim/blob/master/autoload/coc/util.vim#L395 .

In `coc#util#get_complete_option`, only `isKeyword` is treated as `input`, so `[c` is `c` as input, this will not trigger snippet.

**Comment by fannheyward** [comment]
`"snippets.triggerCharacters": ["["]` will not trigger `[c` snippets.

**Comment by weiguoquan422** [comment]
@chemzqm 
I have the same problem, "snippets.triggerCharacters" dont work

**Comment by weiguoquan422** [comment]
> `"snippets.triggerCharacters": ["["]` will not trigger `[c` snippets.

Have you solved the problem?

**Comment by chemzqm** [comment]
Please provide an example snippet.

**Comment by weiguoquan422** [comment]
> Please provide an example snippet.

for example, I enter following in markdown:
$lambda
I want to lambda snippet display in popup menu, but not. Any other symbol (like . , ) preceding the lambda will not trigger the snippet display of the pop menu.

my lambda snippet:
snippet lambda "\lambda"
\lambda
endsnippet

my json setting:
    "snippets.extends": {
        "markdown": ["tex"],
        "cpp": ["c"]
    },
    "snippets.triggerCharacters": ["$"]
