### ISSUE TITLE
Is visual placeholder working?

### ISSUE THREAD

**Issue by purpleP** [neoclide/coc-snippets#8]
I do `vmap <tab> <Plug>(coc-snippets-expand)`, and select text visually, and then trigger the snippet. But visual placeholder is empty.

**Comment by jsrojoo** [comment]
Hi @purpleP, did you get this to work? I am also experiencing the same issue.

**Comment by chemzqm** [comment]
Make sure your keymap is expected

**Comment by jsrojoo** [comment]
This is the mapping I have : 

```
inoremap <silent><expr> <TAB>
      \ pumvisible() ? coc#_select_confirm() :
      \ coc#expandableOrJumpable() ? "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand-jump',''])\<CR>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

let g:coc_snippet_next = '<tab>'
```

But it does not seem to work. Do I need to add the default mapping as well to make the visual placeholder work?

**Comment by chemzqm** [comment]
You have use keymap to visual select the text first, please read Readme.

**Comment by jsrojoo** [comment]
Yes, I've read the readme. Visually selecting then hitting the default
<C-j> mapping lets me go to insert mode.

Then after hitting tab, the VISUAL text does not get replaced with the text
that was visually highlighted before.

Not sure what I'm doing wrong.

**Comment by chemzqm** [comment]
> then hitting the default <C-j> mapping lets me go to insert mode.

It's not default, you need add it to your vimrc.

**Comment by jsrojoo** [comment]
```

" Use <C-l> for trigger snippet expand.imap <C-l> <Plug>(coc-snippets-expand)
" Use <C-j> for select text for visual placeholder of snippet.vmap
<C-j> <Plug>(coc-snippets-select)
" Use <C-j> for jump to next placeholder, it's default of coc.nvimlet
g:coc_snippet_next = '<c-j>'
" Use <C-k> for jump to previous placeholder, it's default of
coc.nvimlet g:coc_snippet_prev = '<c-k>'
" Use <C-j> for both expand and jump (make expand higher
priority.)imap <C-j> <Plug>(coc-snippets-expand-jump)

```

This configuration is added before the tab support mapping config which
lets me use <Ctrl-j>.

What else do I need to do to make the visual placeholder to work?

**Comment by chemzqm** [comment]
Don't know, can't reproduce, you can debug the plugin in chrome https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim
