### ISSUE TITLE
Visual placeholder doesn't work

### ISSUE THREAD

**Issue by dianlujitao** [neoclide/coc-snippets#82]
![demo](https://i.imgur.com/gqd2Cos.gif)
(Maybe) minimal vimrc:
```vim
call plug#begin('~/.vim/plugged')
 Plug 'honza/vim-snippets'
 Plug 'neoclide/coc.nvim', {'branch': 'release'}
 " Plug 'SirVer/ultisnips'
call plug#end()

" Use <C-l> for trigger snippet expand.
imap <C-l> <Plug>(coc-snippets-expand)

" Use <C-j> for select text for visual placeholder of snippet.
vmap <C-j> <Plug>(coc-snippets-select)

" Use <C-j> for jump to next placeholder, it's default of coc.nvim
let g:coc_snippet_next = '<c-j>'

" Use <C-k> for jump to previous placeholder, it's default of coc.nvim
let g:coc_snippet_prev = '<c-k>'

" Use <C-j> for both expand and jump (make expand higher priority.)
imap <C-j> <Plug>(coc-snippets-expand-jump)

inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm() : 
                                           \"\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
```

**Comment by chemzqm** [comment]
Can't reproduce

**Comment by dianlujitao** [comment]
FYI coc-texlab 1.9.8 and coc-snippets 2.1.13 are active extensions, and the version is VIM 8.1 8.1.2268 from official archlinux repo, do I need to provide more details?

**Comment by dianlujitao** [comment]
Temp switched to `coc-ultisnips`+`ultisnips` as a workaround, but it doesn't provide preview to the snippets, should I open an issue there?

**Comment by chemzqm** [comment]
>  but it doesn't provide preview to the snippets, should I open an issue there?

I don't think I will make that would work unless ultisnips provide a api for preview,

**Comment by dianlujitao** [comment]
> > but it doesn't provide preview to the snippets, should I open an issue there?
> 
> I don't think I will make that would work unless ultisnips provide a api for preview,

Thanks for the clarification.

Back to the original issue, to make sure it's reproducible from a clean environment, I pulled latest Debian buster docker image:
```
docker pull debian:buster
```
and started a bash shell there. Then, install `vim-nox` (compiled with py3 support) with apt and nodejs 13.x following the instructions [here](https://github.com/nodesource/distributions/blob/master/README.md#debinstall):
```
curl -sL https://deb.nodesource.com/setup_13.x | bash -
apt-get install -y nodejs
```

With the .vimrc above it behaves exact the same as the gif.
