### ISSUE TITLE
Some "special" snippets are not expanded as expected

### ISSUE THREAD

**Issue by dianlujitao** [neoclide/coc-snippets#83]
For this snippet:
https://github.com/honza/vim-snippets/blob/a7a7d4d2dd252b71b904d362ba74572c660da67f/UltiSnips/tex.snippets#L73-L82

The following gif demonstrates how https://github.com/SirVer/ultisnips expands it
![ultisnips](https://user-images.githubusercontent.com/5774651/70438531-02721100-1ac9-11ea-9477-89f9d70c79e8.gif)
```vim
call plug#begin('~/.vim/plugged')
 Plug 'honza/vim-snippets'
 Plug 'SirVer/ultisnips'
call plug#end()
```
This is how coc-snippets does
![coc](https://user-images.githubusercontent.com/5774651/70438560-10c02d00-1ac9-11ea-9b31-973ae218f61e.gif)
The minimal vimrc is exact the same as https://github.com/neoclide/coc-snippets/issues/82

The question mark expression or whatever (I'm unfamiliar with it thus can't use a proper word to denote) is expanded as plain text, while with ultisnips "tabular" is replaced with "array" when I press "a".

**Comment by dianlujitao** [comment]
https://github.com/neoclide/coc-snippets/issues/67

**Comment by chemzqm** [comment]
Reformat placeholder on type is not supported, it's documented.
