### ISSUE TITLE
Option to disable ultisnip and/or snipmate when lsp provides snippets

### ISSUE THREAD

**Issue by BonaBeavis** [neoclide/coc-snippets#84]
Ulti or snipmate have to be enabled for filetypes with no lsp support, but then filetypes with lsp support show duplicate snippets.

An improvement would be to only load snipmate and ulti when the lsp plugin provides no snippets.

Disabling either snipmate or ulti  as default would also provide cleaner suggestion with no duplicates out of the box.

**Comment by chemzqm** [comment]
No, they're different things.
