### ISSUE TITLE
[Question] Configure S-TAB to jump to previous placeholder

### ISSUE THREAD

**Issue by mvcouwen** [neoclide/coc-snippets#87]
I was wondering whether there is some way to configure S-TAB to jump to the previous placeholder when inside a snippet.

I am looking for something similar to coc#rpc#request('doKeymap', ['snippets-expand-jump','']).

What are the other options I can replace "snippets-expand-jump" with?

Awesome work by the way!

**Comment by chemzqm** [comment]
```
let g:coc_snippet_prev = '<s-tab>'
```

**Comment by mvcouwen** [comment]
I am aware of this option but probably I didn't pose my question right. I am sorry.

I want <s-tab> to have the following behaviour. If pum is visible, I want <s-tab> to cycle through the suggested completion in reverse order. If pum is not visible but I am inside a snippet, I want <s-tab> to jump to the previous placeholder. If none of the above, I want <s-tab> to remove a tab. So basically I want <s-tab> to behave more or less as the opposite of:

```vim
inoremap <silent><expr> <TAB>
      \ pumvisible() ? coc#_select_confirm() :
      \ coc#expandableOrJumpable() ? "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand-jump',''])\<CR>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
```

**Comment by mvcouwen** [comment]
I came up with the following solution by doing some digging in the source code.

```vim
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ coc#jumpable() ? "\<C-r>=coc#rpc#request('snippetNext',[])\<CR>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()

inoremap <silent><expr> <S-TAB>
    \ pumvisible() ? "\<C-p>" :
    \ coc#jumpable() ? "\<C-r>=coc#rpc#request('snippetPrev',[])\<CR>" :
    \ "\<C-h>"
```

Any comments are improvements are still welcome.

**Comment by ryuta69** [comment]
It's kinda old but really thank you for this information
