### ISSUE TITLE
Unable to load VSCode snippet 

### ISSUE THREAD

**Issue by justrajdeep** [neoclide/coc-snippets#88]
Hi 
I am trying to use some `VSCode` snippets from the below location

https://github.com/gvekony/sv-1800-2012/tree/master/snippets

Updated my `coc-settings.json`

    {
      "snippets.ultisnips.directories": [
          "/local_vol1_nobackup/user/ramondal/home/sv-1800-2012/snippets/"
      ]
    }

When I open an `sv`/`svh` file and run `:CocCommand snippets.openSnippetFiles` it reports 

`[coc.nvim] No related snippet file found`.

Did I miss any config steps?

**Comment by chemzqm** [comment]
You have to make sure you filetype is `systemverilog`.

**Comment by justrajdeep** [comment]
Hi 

The `filetype` is set to [verilog_systemverilog](https://github.com/vhda/verilog_systemverilog.vim) ? Is it possible to use the plugin with that filetype since I want to have the syntax highlighting and indentation from that plugin.

**Comment by chemzqm** [comment]
Use filetype map configuration

**Comment by justrajdeep** [comment]
Hi 

A couple of doubts, this is what I have in my `coc-settings.json`

    {
      "snippets.ultisnips.directories": [
          ,"~/.vim/mysnippets"
          ,"/local_vol1_nobackup/user/ramondal/home/sv-1800-2012"
      ]
      ,"tsserver.trace.server": "verbose"
      ,"snippets.extends": {
        "systemverilog": ["verilog_systemverilog"]
      }
    }

`~/.vim/mysnippets` points to https://raw.githubusercontent.com/justrajdeep/dotvim/master/mysnippets and it has an `all.snippets` which I assumed should be available to all filetypes. 

But when I run `:CocCommand snippets.openSnippetFiles` I dont see `all.snippets` in that list.

`:CocCommand workspace.showOutput snippets` is always blank even with `"tsserver.trace.server": "verbose"`, what am i doing wrong?

`/local_vol1_nobackup/user/ramondal/home/sv-1800-2012` points to https://github.com/gvekony/sv-1800-2012 since that contains `package.json` which tells the completion details. Should I point it to https://github.com/gvekony/sv-1800-2012/tree/master/snippets? 

Even with the `snippets.extends` mapping, I dont see the  https://github.com/gvekony/sv-1800-2012 snippets available to me for a `verilog_systemverilog` filetype.

Thanks for helping me with this issue. Really appreciate the time you are putting in for this.

**Comment by chemzqm** [comment]
Should be bug with snippets configuration in package.json.

**Comment by justrajdeep** [comment]
Just a follow up observation, if I do `CocList snippets` I am able to see snippets from `all.snippets` but `CocCommand snippets.openSnippetFiles` just shows `[coc.nvim] No related snippet file found`.

**Comment by chemzqm** [comment]
You have to install VSCode snippet extension by use `:CocInstall` checkout https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#install-extensions
