### ISSUE TITLE
snippets not loaded for filetype typescript/typescript.tsx

### ISSUE THREAD

**Issue by ruanyl** [neoclide/coc-snippets#9]
I use `yats.vim` for typescript & tsx syntax file, it sets `*.tsx` file as `typescript.tsx`, and `*.ts` file as `typescript`

And I have  `SirVer/ultisnips` `honza/vim-snippets` installed.

Issues of using coc for snippets completion:
1. For `*.tsx` file, it seems only `all.snippets` from `vim-snippets` is loaded.
2. For `*.ts` file, `typescript.snippets` is loaded.(which extends javascript)
3. Neither of them load library snippets, for example: `javascript-jasmine-arrow.snippets`

If I use `SirVer/ultisnips`, all of the snippets mentioned above are loaded for both `ts` and `tsx` file.

I can see from `:CocInfo` that all the snippets are loaded.

**Comment by chemzqm** [comment]
Coc use `typescriptreact` internal, checkout `:h g:coc_filetype_map`.

`honza/vim-snippets` add `extends typescript` in `snippets/typescriptreact.snippets`, but that folder is not loaded by coc-snippets, you have to configure extends yourself, like https://github.com/neoclide/coc-snippets#options

**Comment by ruanyl** [comment]
Thanks! Solved by adding:
```
  "snippets.extends": {
    "javascriptreact": ["javascript"],
    "typescriptreact": ["javascript", "javascript-jasmine-arrow"],
    "typescript": ["javascript", "javascript-jasmine-arrow"]
  }
```

**Comment by esetnik** [comment]
I ran into the same issue. Is it possible to have the extended snippets automatically loaded by `coc-snippets`?

**Comment by lai32290** [comment]
hi @ruanyl , where should I put these configuration codes?

**Comment by lvjian700** [comment]
hey @lai32290   try 

```
:CocConfig
```
