### ISSUE TITLE
snippets not loading?

### ISSUE THREAD

**Issue by endlist** [neoclide/coc-snippets#94]
Not sure if this is a config issue, but I can't seem to get the plugin to be able to set up or recognize snippets anywhere.

When I run `:CocList snippets` I get the message `[coc.nvim] List snippets not found` and `:CocCommand workspace.showOutput snippets` similarly tells me `[coc.nvim] Channel "snippets" not found`.

I'm using `vim-plug` to install `neoclide/coc.nvim`, `neoclide/coc-snippets`, and `honza/vim-snippets` into a custom directory (`~/.local/share/nvim/plugged`) and it seems like the basic autocomplete is working and some commands (`:CocConfig` definitely works, as does `:CocCommand` itself, at least to pull up a list).

But trying to create a new snippet with `:CocCommand snippets.editSnippet` similarly gives me `[coc.nvim] Command: snippets.editSnippets not found`.

**Comment by fannheyward** [comment]
The extension is not installed correctly, please check the wiki page: https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions

**Comment by chemzqm** [comment]
Make sure the coc-snippets is build successfully by command `yarn install`
