### ISSUE TITLE
Snipmate snippets expanding incorrectly

### ISSUE THREAD

**Issue by JonnyHaystack** [neoclide/coc-snippets#96]
Hi,

Some of my TeX snippets are not expanding correctly, notably these ones which I use very often:
```
snippet ita italic text
	\\textit{${1:${VISUAL:text}}}${0}
snippet bf bold face text
	\\textbf{${1:${VISUAL:text}}}${0}
```

When I type `bf` and expand it, I should get something like:
```
\textbf{}
```
And I would be editing the text between the braces.

But what I am actually getting is this:
```
\textbf{:text}}
```
With `:text` highlighted and editable, but I end up with an extra closing brace on the end which I have to remove manually.

I don't remember having this issue before recently, although I haven't been doing a huge amount of LaTeX since I switched to coc-snippets so I'm not entirely sure if this is a new bug or not.

**Comment by mvcouwen** [comment]
I have the same issue. Also the preview of the snippet is wrong. It shows for example "\textbf{TM_SELECTED_TEXT:text}}". Maybe this helps figuring out where things go wrong?

**Comment by Melkster** [comment]
I'm still having problems with the `sec` UltiSnips snippet using `coc-snippets`. On expanding `sec` I get the following output:
```tex
\section{}%
\label{sec:${1/\\w+{(.*?)}|\(.)|(\w+)|([^\w\]+)/(?4:_:\L${1/\\w+{(.*?)}|\(.)|(\w+)|([^\w\]+)/(?4:_:\L\E)/ga\E)/ga}}
```
