### ISSUE TITLE
Vim beeps when selecting text for visual placeholder

### ISSUE THREAD

**Issue by mvcouwen** [neoclide/coc-snippets#98]
Suppose I have configured `<C-j>` to select text for the visual placeholder when in visual mode.
```vim
vmap <C-j> <Plug>(coc-snippets-select)
```
If I go into visual mode, select some text and press `<C-j>` then the the text disappears and will be placed in the visual placeholder of the following snippet (so everything works as expected). However, upon executing `<C-j>`, vim beeps. Why is this? Is this expected behaviour? How can I turn it off?

Just to be clear, I don't want to turn off vim beeping completely. It just don't want vim to beep when the behaviour is exactly as I would expect.

**Comment by chemzqm** [comment]
`set novisualbell` could help.

**Comment by mvcouwen** [comment]
The problem already happens with the following minimal vimrc.

```vim
call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'honza/vim-snippets'
call plug#end()

" Use <C-l> for trigger snippet expand.
imap <C-l> <Plug>(coc-snippets-expand)

" Use <C-j> for select text for visual placeholder of snippet.
vmap <C-j> <Plug>(coc-snippets-select)

" Use <C-j> for jump to next placeholder, it's default of coc.nvim
let g:coc_snippet_next = '<c-j>'

" Use <C-k> for jump to previous placeholder, it's default of coc.nvim
let g:coc_snippet_prev = '<c-k>'

" Use <C-j> for both expand and jump (make expand higher priority.)
imap <C-j> <Plug>(coc-snippets-expand-jump)
```

The only coc-extension installed is coc-snippets. Setting `set novisualbell` did not help. Is there a way to find out why vim beeps?

**Comment by mvcouwen** [comment]
Apparently, `<Plug>(coc-snippets-select)` by default runs the function `coc#rpc#notify('doKeymap',['snippets-select'])`. If I use `request` instead of `notify`, I get the same result but it doesn't put me in insert mode. So if I use the following mapping, it seems to give the same result but without the bell.
```vim
vmap <C-j> :call coc#rpc#request('doKeymap',['snippets-select'])<cr>i
```
Does this help identifying the problem? What is the difference between `request` and `notify`?

**Comment by chemzqm** [comment]
Notify doesn't block your vim.

**Comment by mvcouwen** [comment]
If I set
```vim
:set belloff=esc
```
then there is no bell notification. So it seems that somewhere in the code the escape-key is pressed in normal mode.

**Comment by mvcouwen** [comment]
I have no clue why but the problem seems to be solved. Maybe there was something wrong in my vimrc. Closing this issue.

**Comment by mvcouwen** [comment]
I remember what I did to solve it. I removed line 289 of the file `src/index.ts`. The keymap 'snippets-select' is defined over there.
```typescript
  subscriptions.push(workspace.registerKeymap(['v'], 'snippets-select', async () => {
    let doc = await workspace.document
    if (!doc) return
    let mode = await nvim.call('visualmode')
    if (['v', 'V'].indexOf(mode) == -1) {
      workspace.showMessage(`visual mode ${mode} not supported`, 'warning')
      return
    }
    await nvim.call('feedkeys', [String.fromCharCode(27), 'in']) // this line can be removed
    await nvim.command('normal! `<')
    let start = await workspace.getCursorPosition()
    await nvim.command('normal! `>')
    let end = await workspace.getCursorPosition()
    end = Position.create(end.line, end.character + 1)
    let range = Range.create(start, end)
    let text = doc.textDocument.getText(range)
    await nvim.call('feedkeys', ['i', 'in'])
    if (mode == 'v') {
      await doc.applyEdits(workspace.nvim, [{ range, newText: '' }])
    } else {
      // keep indent
      let currline = doc.getline(start.line)
      let indent = currline.match(/^\s*/)[0]
      let lines = text.split(/\r?\n/)
      lines = lines.map(s => s.startsWith(indent) ? s.slice(indent.length) : s)
      text = lines.join('\n')
      range = Range.create(Position.create(start.line, indent.length), end)
      await doc.applyEdits(workspace.nvim, [{ range, newText: '' }])
    }
    await nvim.setVar('coc_selected_text', text)
    await workspace.moveTo(range.start)
  }, { silent: true, sync: false, cancel: true }))
```
At this line, the escape key is fed to vim in order to go to normal mode. However, vim is already in normal mode at that point. Vim automatically switches to normal mode when doing mappings and you have to manually restore the visual selection if you want to. You can check this by putting the following line in front.
```typescript
await nvim.command('echom mode()')
```
Therefore, there is no need for the extra escape.
